### ISSUE TITLE
defaultOptions leftButtonColor and rightButtonColor are not respected

### ISSUE THREAD

**Issue by MakhouT** [wix/react-native-navigation#6583] opened 2020-09-14 12:02 UTC
### Issue Description
I have set a setDefaultOption, where I am defining my colors for the properties `leftButtonColor` and `rightButtonColor`. 
However they are not being respected when opening a new screen and setting a new rightButton in the `useEffect` of that component. However if in my `useEffect` I define a `mergeOptions` and set my `rightButtonColor` then it's working. However this is not intended otherwise you need to do it for every component, while I would like to have it in the defaultOptions

[Expected]
That the `leftButtonColor` and `rightButtonColor` are being used through the app if they are defined in the `defaultOptions`

### Environment
* React Native Navigation version: 0.63.2
* React Native version: 7.0
* Platform(s) (iOS, Android, or both?): Only tried it on ios
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, IOS, debug

**Comment by danilobuerger** [comment] 2020-09-14 15:34
I just tried this with `leftButtonColor` in the playground app on iOS and it worked without a problem. Please provide a minimal reproducible sample (preferably based on the playground app) for further debugging.

**Comment by robrechtme** [comment] 2020-10-09 07:39
Duplicate of #5165 and I have a similar issue. If you use 
```js
Navigation.mergeOptions(componentId, {
  topBar: {
    leftButtonColor: color,
  },
});
```
it does not change the color. I will provide a playground example soon.

**Comment by robrechtme** [comment] 2020-10-09 16:31
This is a simplified version which can help you reproducing the issue:
```js

const Screen = ({ componentId }) => {

  const changeButtonColor = () => {
    Navigation.mergeOptions(componentId, {
      topBar: {
        leftButtonColor: 'blue', // this should turn the button blue, but it doesn't
      },
    })
  }

  return (
    <View>
      <Button label="Change button color" onPress={changeButtonColor} />
    </View>
  );
}

Screen.options = {
  topBar: {
    leftButtons: [
      {
        id: 'LEFT',
        icon: require('../../img/clear.png'),
      },
    ],
    leftButtonColor: 'red',
  },
}

export default Screen;
```
Tested on Android 11 and iOS 14.  
It is also easily testable in the `ButtonsScreen` of the playground. Make sure you remove the `color` prop on the individual buttons.

**Comment by danilobuerger** [comment] 2020-10-09 16:43
@robrechtme I don't understand how this is related to the ops issue? The op has problems setting the color via `defaultOptions`.

**Comment by robrechtme** [comment] 2020-10-09 16:56
Woops I misread ops issue, my bad! Anyway, what I describe is also an issue, I shall create a new one.

**Comment by danilobuerger** [comment] 2020-12-02 12:06
no reproduction supplied.

**Closed by danilobuerger** 2020-12-02 12:06 UTC
Labels: user: requires reproduction
