### ISSUE TITLE
[v3] TopBar behind StatusBar on push with visible flag change

### ISSUE THREAD

**Issue by danilobuerger** [wix/react-native-navigation#5285] opened 2019-07-15 12:03 UTC
### Issue Description

When pushing a Screen on a Stack that was `topBar: { visible: false }` becoming `topBar: { visible: true }`, the TopBar is rendered behind the StatusBar:

![Screenshot_1563192104](https://user-images.githubusercontent.com/996231/61214773-1deb1280-a709-11e9-8354-0e5cc4d9063c.png)
 

### Steps to Reproduce / Code Snippets / Screenshots

To reproduce, use v3 playground app with following diff:

```diff
diff --git a/playground/src/screens/PushedScreen.js b/playground/src/screens/PushedScreen.js
index 23d7990d..38a9b8bb 100644
--- a/playground/src/screens/PushedScreen.js
+++ b/playground/src/screens/PushedScreen.js
@@ -30,7 +30,9 @@ class PushedScreen extends React.Component {
           id: 'singleBtn',
           text: 'single',
           testID: TOP_BAR_BTN
-        }
+        },
+        drawBehind: true,
+        visible: true,
       }
     };
   }
diff --git a/playground/src/screens/StackScreen.js b/playground/src/screens/StackScreen.js
index 002a8de2..8b33701b 100644
--- a/playground/src/screens/StackScreen.js
+++ b/playground/src/screens/StackScreen.js
@@ -24,7 +24,9 @@ class StackScreen extends React.Component {
         testID: STACK_SCREEN_HEADER,
         title: {
           text: 'Stack'
-        }
+        },
+        drawBehind: true,
+        visible: false,
       }
     }
   }
```

Steps:
1) Press "Stack" Button
2) Press "Push" Button

---
### Environment
* React Native Navigation version: v3 alpha 2
* React Native version: 0.60
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator API 28

**Comment by Frekansapp** [comment] 2019-07-15 12:12
Same here https://github.com/wix/react-native-navigation/issues/5228#issuecomment-508996552. Thank you for reproduce in playground app. Because i could not find time to reproduce in the playground app.

**Comment by guyca** [comment] 2019-07-15 12:21
@danilobuerger This might be caused by [this line](https://github.com/wix/react-native-navigation/blob/v3/lib/android/app/src/main/java/com/reactnativenavigation/presentation/StackPresenter.java#L505)

**Comment by danilobuerger** [comment] 2019-07-15 13:44
@guyca Uncommenting that line works for the playground app. The top bar is then displayed beneath the status bar. I don't know about any side effects though that this will have.

**Comment by cesarm16** [comment] 2019-07-17 21:54
any solution to this?

**Comment by guyca** [comment] 2019-07-20 05:48
Should be fixed in `.alpha-4`. Thanks for reporting @danilobuerger 👍

**Closed** 2019-07-20 15:57 UTC
Labels: platform: Android, type: accepted/bug, 📌 pinned
