### ISSUE TITLE
[V2][Android] Popping a screen quickly after pushing will mess up navigation options

### ISSUE THREAD

**Issue by Jazqa** [wix/react-native-navigation#4972] opened 2019-04-11 10:08 UTC
### Issue Description

Popping a screen quickly after pushing will mess up navigation options and topBar

### Steps to Reproduce / Code Snippets / Screenshots

1. Push a screen
2. Pop the new one as quickly as possible
3. You will end up on the first screen with the navigation options (and topBar) of the second screen **(if animations.push.waitForRender is enabled the whole screen apart from the topBar of the second screen will be white and your app will be completely stuck)**
---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Multiple devices (Androids versions 7 - 9)

**Comment by ItsNoHax** [comment] 2019-04-29 08:45
Closing as it's a duplicate of: https://github.com/wix/react-native-navigation/issues/4405

**Closed by ItsNoHax** 2019-04-29 08:45 UTC
