### ISSUE TITLE
Tab bar text cut off and ellipsized on iPadOS 14

### ISSUE THREAD

**Issue by reidab** [wix/react-native-navigation#6533] opened 2020-09-03 02:28 UTC
### Issue Description

When rendering a tab bar on an iPad running iPadOS Public Beta 6, text labels for tab bar items are truncated. 

### Steps to Reproduce / Code Snippets / Screenshots

![IMG_0292](https://user-images.githubusercontent.com/13192/92064301-15f99200-ed52-11ea-9b84-7dad655eb52e.png)

---
### Environment
* React Native Navigation version: Reproduced on playground app built from `master`
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS: iPadOS 14 Public Beta 6
* Device info (Simulator/Device? OS version? Debug/Release?): iPad Pro 11" 2018

**Comment by danilobuerger** [comment] 2020-09-11 13:19
I can reproduce this. However, I am not sure if it is worth pursuing as this could very well just be an iPadOS beta bug. Maybe we should circle back on this once the GM is out.

**Comment by bennettk** [comment] 2020-09-14 17:30
FWIW- this is also an issue when running on an Apple Silicon Mac, since that effectively runs your app as an iPad. No GM there yet either, but it seems like we're nearing the end of the beta period.

**Comment by danilobuerger** [comment] 2020-09-16 09:35
Confirmed on iPadOS 14 GM

**Comment by danilobuerger** [comment] 2020-09-16 10:25
@yogevbd This seems to be caused by applying `NSForegroundColorAttributeName` to the `UITabBarItem` `standardAppearance`. When removing the color, the labels are not truncated. However, on a fresh iOS project (no rn) this doesn't happen. Suggesting we have some further code that modifies this behavior. Any idea?

**Comment by yogevbd** [comment] 2020-09-17 09:54
That's weird.. I will give it a look today

**Comment by yogevbd** [comment] 2020-09-22 08:58
This issue really looks like a bug in iOS itself.. I will open a ticket for apple.

**Comment by LeeJunhui** [comment] 2020-10-12 02:14
@yogevbd Does Apple give some solution about this issue😂

**Comment by guyca** [comment] 2020-10-18 04:16
@yogevbd Can you please add a link to the ticket? Thanks! 👍

**Comment by bennettk** [comment] 2020-10-19 18:31
FWIW- a team member found a workaround for this by adding an NSForegroundColorAttributeName to the titleTextAttributes in setTitleAttributes / setSelectedTitleAttributes in TabBarItemAppearanceCreator:

```
    if (@available(iOS 14.0, *)) {
      UIColor *color = [selectedTitleAttributes valueForKey:@"NSColor"];
      if (color) {
        tabItem.standardAppearance.inlineLayoutAppearance.selected.titleTextAttributes = @{NSForegroundColorAttributeName: color};
      }
    }
```

not sure if this fixes all cases, but it works for us so far so we're swizzling the RNN implementation for now... but obviously if the fix landed in RNN, we'd much prefer to use that. :)

**Comment by danilobuerger** [comment] 2020-10-19 18:58
@bennettk Nice, do you want to create a PR for it?

**Comment by bennettk** [comment] 2020-10-19 20:04
@danilobuerger can do- https://github.com/wix/react-native-navigation/pull/6690

**Comment by guyca** [comment] 2020-10-20 08:28
Reopening as #6690 was reverted. @bennettk let's reproduce the regression pointed out by @danilobuerger and submit a new PR?

**Comment by bennettk** [comment] 2020-10-23 22:23
@guyca hi, sorry- been buried with a lot of day job work :) should have a chance to take a look early next week.

**Comment by zzorba** [comment] 2020-11-14 17:20
Curious if there is a workaround that anyone has found around this issue. I've started hearing more complaints from users as more people update to IOS 14.

**Closed** 2020-11-21 13:44 UTC
Labels: iOS 14, platform: iOS, type: accepted/bug

**Comment by Adegeminas** [comment] 2021-01-11 15:53
Hi guys!

Looks like there is a way to reproduce this even after bugfix in iOS 14.2 (simulator and production)

"react-native": "^0.63.3"
"react-native-navigation": "^7.4.0-snapshot.1328" (and same story with 7.8.1)

I'm re-setting root after going to background (using hardware button) and back again like this:
`
Navigation.events().registerAppLaunchedListener(async () => {
    const state = await store.getState();
    that.startApp(state.global.root);
});
`
So, for the first time i'm returning from background state i see truncated text of bottom tabs.

Any idea?

**Comment by kabus202** [comment] 2021-01-18 08:46
@Adegeminas, i have the sam on iOS/* and i have this only on the first resume. 

To reproduce:
background -> resume app -> { ellipsis dots } -> click on each tab -> background -> resume -> all visible

What i also discovered is: when you remove fontSize from bottomTab options, it's also working without any problems

**Comment by Adegeminas** [comment] 2021-01-18 10:25
@kabus202 thanks for fontSize tip. Removing that options works, but i need it)

**Comment by kabus202** [comment] 2021-01-18 10:29
@Adegeminas thanks for confirming this. @guyca can we reopen this one?

**Comment by Brett-Best** [comment] 2021-01-28 03:34
Related to https://github.com/Tencent/QMUI_iOS/issues/1110 which was fixed by https://github.com/Tencent/QMUI_iOS/blob/09cdc055f63a4ef88a75cfeefc3e5521eef7bbd1/QMUIKit/UIKitExtensions/UITabBar%2BQMUI.m#L198-L226.

I also was able to workaround the issue in a blank project by setting the attribute `paragraphStyle` to `NSParagraphStyle.default` of the `titleTextAttributes`.

**Comment by wilsontr** [comment] 2021-02-10 15:34
I was able to get this working by reverting the change made in #6784, per @ryanbourneuk's [comment](https://github.com/wix/react-native-navigation/pull/6784#issuecomment-756791679). I will be using patch-package to handle this for now, but maybe that PR should be entirely reverted?

**Comment by brsaylor2** [comment] 2021-03-01 23:17
Removing fontSize does not work for me.

**Comment by ddcrobert** [comment] 2021-03-03 19:54
In case that helps someone, I had a similar issue like @Adegeminas, fixed it by changing default appareance's custom font / fontsize. I added this line in AppDelegate.m, ahead of RNN initialization.
[[UITabBarItem appearance] setTitleTextAttributes:@{NSFontAttributeName: [UIFont fontWithName:@“SomeFont-Bold” size:10.0f]} forState:UIControlStateNormal];

**Comment by priyak-sdei** [comment] 2021-04-05 05:42
Issue is still replicating.
I have even upgraded the latest library version
 "react-native-navigation": "7.11.3",
 But still issue is happening, when switching the Apps from background and then come back.
 
![Simulator Screen Shot - iPhone 11 - 2021-04-05 at 11 09 59](https://user-images.githubusercontent.com/70944781/113541350-a86f5600-95ff-11eb-8cfc-6e97ce2b64b4.png)

**Comment by kabus202** [comment] 2021-05-27 13:12
@priyak-sdei  i opened a separate issue for this a while ago see:  https://github.com/wix/react-native-navigation/issues/6923

**Comment by kabus202** [comment] 2021-09-22 21:05
@Brett-Best can you share your example pls?

**Comment by Brett-Best** [comment] 2021-09-22 23:39
@kabus202
```swift
func configure(itemAppearance: UITabBarItemAppearance) -> UITabBarItemAppearance {
  with(itemAppearance) {
    // Setting a paragraph style worksaround an issue where the tab title would be truncated on iPadOS.
    //
    // SEE: https://github.com/Tencent/QMUI_iOS/issues/1110 & https://github.com/wix/react-native-navigation/issues/6533
    let paragraphStyle = NSParagraphStyle.default

    with($0.normal) {
      $0.iconColor = .asset(.tabBarUnselectedTint)
      $0.titleTextAttributes.merge([
        .foregroundColor: UIColor.asset(.tabBarUnselectedTint),
        .paragraphStyle: paragraphStyle
      ]) { _, new in new }
    }

    with($0.selected) {
      $0.iconColor = .asset(.tabBarTint)
      $0.titleTextAttributes.merge([
        .foregroundColor: UIColor.asset(.tabBarTint),
        .paragraphStyle: paragraphStyle
      ]) { _, new in new }
    }
  }
}
```

**Comment by kabus202** [comment] 2021-09-23 04:59
@Brett-Best where to put this?

**Comment by kabus202** [comment] 2022-02-01 12:10
Did you guys find a proper solution for this?

**Comment by arcziby** [comment] 2022-02-13 10:07
Bug is still appearing on iPhones.

Properly view:
![Screenshot 2022-02-13 at 10 47 54](https://user-images.githubusercontent.com/73952992/153748232-6f9a7255-fe4f-4eaa-9537-fe855cc67d0d.png)

Bug:
![Screenshot 2022-02-13 at 10 48 18](https://user-images.githubusercontent.com/73952992/153748236-0f5c2578-1017-4d68-9773-87028321bae5.png)

any updates ?

**Comment by doublerebel** [comment] 2022-02-25 23:45
Here's a fix that is working for us:
```swift
self.tabBar.subviews.forEach {
    if let label = $0.subviews[1] as? UILabel {
        label.lineBreakMode = .byClipping
    }
}
```
We set the tab bar titles in `viewWillAppear` for our UITabBar subclass, calling this code after setting the label title works every time.  It's a bit of a hack but it seems simpler than most of the other solutions.  This fix is inspired by a solution [posted in StackOverflow](https://stackoverflow.com/questions/58641202/ios-tabbar-item-title-issue-in-ios13/61197199#61197199).

**Comment by piuholo** [comment] 2022-03-16 12:19
This issue still persists on iOS 15.4 with react-native-navigation 7.26.0 and React Native version 0.67.4. 
Strangely, if no text or icon color is applied to selected or unselected tabs, the text is not truncated but selecting tabs makes the text and icon move around / change size.

**Comment by haveneersrobin** [comment] 2022-03-30 08:21
Happening for me as well...
- `react-native`: 0.66.1
- `react-native-navigation`: 7.25.11

**Comment by zzorba** [comment] 2022-03-31 20:25
Yeah, this is definitely still happening on iOS with the recent react-native + react-native-navigation.

**Comment by leejunhui** [comment] 2022-04-01 02:35
On iOS 15.4, this issue happens again 😂

**Comment by olegderecha** [comment] 2022-06-20 16:59
Ok, guys, let's solve it together here: https://github.com/wix/react-native-navigation/issues/7506#issuecomment-1160668701

**Comment by skuzoluk** [comment] 2023-01-18 13:08
I have a simple solution. It is weird but just works :)
Why not just add some extra space after text like:

```
const extraSpace = '         ';
bottomTab: {
    text: 'Screen Title' + extraSpace
}
```

Otherwise the issue still exists even after i have tried the solutions above.
