### ISSUE TITLE
navBarHidden changes top of ScrollViews to -20 on iOS11

### ISSUE THREAD

**Issue by MrLoh** [wix/react-native-navigation#1975] opened 2017-10-05 15:39 UTC
### Issue Description

When `navBarHidden: true` is set on a screen the ScrollViews are broken and start with an initial value of -20 and can also scroll further up. When switching to another screen and going back the issue is solved, it just happens on the first render of a screen. 

### Steps to Reproduce / Code Snippets / Screenshots

Set `navBarHidden: true` and log the scrollPosition of a ScrollView, I can setup a demo repo, if that helps. 

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.47.2
* Platform(s) (iOS, Android, or both?): iOS11
* Device info (Simulator/Device? OS version? Debug/Release?): Device (production), simulator (debug)

**Comment by MrLoh** [comment] 2017-10-05 15:41
@gran33 could this be related to #1858?

**Comment by malcevicius** [comment] 2017-10-24 18:06
I have the same issue. See below example.
![statusbar-bug](https://user-images.githubusercontent.com/4559249/31960045-2cee89e6-b8ff-11e7-8c95-edc763697348.gif)

**Comment by chenweigh** [comment] 2017-11-06 08:19
The same Problem for me. so how to fix it? any one  know?

**Comment by devey** [comment] 2017-11-16 16:23
Same problem here:
It seems to be something that needs to be fixed on the repo side cause by trying to run and open the `Push List Screen`  in this repos `example` app, it's broken there too.

https://github.com/wix/react-native-navigation/blob/master/example/src/screens/NavigationTypes.js#L110

**Comment by Royce** [comment] 2017-11-30 14:23
Our app came across these kind-of iOS 11 ScrollView issues.

#1859 is an attempt to fix this, but it runs on `viewWillAppear`, so it fails to fix ScrollViews that are created after the first render of the Screen.

Our solution, was to upgrade to React Native version: 0.50.0 where the issue is fixed _properly_ at ScrollView creation.  (And then upgrade all our other dependencies...)  One could alternatively fork RN at 0.48.x and cherry-pick the commit for fixing this ...

**Comment by MrLoh** [comment] 2017-12-05 07:18
Yes it seems fixed in react native 0.50 🎉

**Comment by MrLoh** [comment] 2017-12-05 07:18
Yes it seems fixed in react native 0.50 🎉

**Closed** 2017-12-05 07:18 UTC
