### ISSUE TITLE
Build Fails: Plugin with id 'kotlin-android' not found and compileSdkVersion is not specified.

### ISSUE THREAD

**Issue by ahmedhammad97** [wix/react-native-navigation#6341] opened 2020-06-27 21:04 UTC
The build fails using version 6.8.0. I also tried to downgrade to 6.7.5 and 6.7.1, but the same happens.

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\Hammad\Desktop\PROJECT_NAME\node_modules\react-native-navigation\lib\android\app\build.gradle' line: 4

* What went wrong:
A problem occurred evaluating project ':react-native-navigation'.
> Plugin with id 'kotlin-android' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-navigation'.
> compileSdkVersion is not specified.
```

To reproduce:
 - `yarn add react-native-navigation`
- `npx react-native run-android`

---
### Environment
* React Native Navigation version: 6.8.0
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device/Debug

**Comment by jinshin1013** [comment] 2020-06-28 00:32
Hi @ahmedhammad97, it seems like you may have followed the installation process on the doc. Closing now as I cannot reproduce the issue.

However if the problem still persists, could you provide a minimal reproduction on Github for me to have a look? Cheers!

**Closed by jinshin1013** 2020-06-28 00:32 UTC

**Comment by guyca** [comment] 2020-06-28 08:09
@ahmedhammad97 [You need link the library after installing it](https://wix.github.io/react-native-navigation/docs/installing#installing-with-npx-rnn-link)
