### ISSUE TITLE
[Android] [7.9.0 - 7.12.0] - bottomTabs is not visbile again if it was invisibled on a child tab

### ISSUE THREAD

**Issue by sanghavan** [wix/react-native-navigation#7063] opened 2021-03-26 08:00 UTC
## 🐛 Bug Report

I'm facing the issue:
On my Android app, there is 5 bottom tabs, one of them (e.g.: the screen at tabIndex = 3) set `visible: false`, `drawBehind: true` as below:
``` javascript
static options(_props: Props): Options {
    return {
        bottomTabs: {
            visible: false,
            drawBehind: true
        }
    };
}
```
On that screen I have a button for switching back to the Home tab (tabIndex = 0). When switching back it got the issue.

- Expected: bottomTabs with buttons should be visible again.
- Actual:  bottomTabs visbile background only, not showing buttons.

That issue is on RNN version v7.9.0 or later including latest version. It worked as expected with RNN v7.8.4 or prior.

## Your Environment

- React Native Navigation version: v7.9.0 or later including latest version 7.12.0
- React Native version: 0.64.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, the both Debug & Release.

**Comment by yahveh** [comment] 2021-03-27 08:18
```
# RN0.64, RNN 7.12.0
Navigation.setDefaultOptions({
  bottomTabs: {
    // tabsAttachMode: 'onSwitchToTab', //if `onSwitchToTab` not trigger RNN's ComponentDidAppear
    // animate: false, //if `false`, push then back, bottomtabs not showing buttons
  }
})
```

**Comment by solonifer** [comment] 2021-03-29 15:29
Same issue RNN 7.12.0

**Comment by dzenglyuk** [comment] 2021-04-30 14:34
Same issue on android RNN 7.13.0

**Comment by asymptotik** [comment] 2021-07-13 01:54
Same issue on android RNN 7.17.1

**Comment by solonifer** [comment] 2021-12-01 13:25
Same issue on android RNN 7.23.1

**Comment by swabbass** [comment] 2021-12-01 15:59
can you try 7.24.0 and report back :]

**Comment by solonifer** [comment] 2021-12-01 16:42
@swabbass, just tried now, still not working on 7.24.0 :(

Only background visible, but no tabs icons.

**Comment by swabbass** [comment] 2021-12-01 16:51
@solonifer can you please reproduce that on our playground, or with a minimal project, and share it here so we can debug what flows you are trying?

**Comment by Derron210** [comment] 2021-12-02 10:25
@swabbass Hello, i also had this issue and was able to fix it by overriding restoreBottomNavigation method in BottomTabs.java

    @Override
    public void restoreBottomNavigation(boolean withAnimation) {
        super.restoreBottomNavigation(withAnimation);
        if (!withAnimation) setVisibility(View.VISIBLE);
    }

**Comment by solonifer** [comment] 2021-12-02 13:05
@swabbass can confirm that fix by @Derron210 works.

**Comment by swabbass** [comment] 2021-12-02 18:29
> @swabbass can confirm that fix by @Derron210 works.

We need to check that first, I'll try to deduce the problem from the solution and your description above, but, normally a minimal demo or modification on our playground will make such bug fix faster even merged and released faster.

**Comment by swabbass** [comment] 2021-12-06 09:24
Well, i created a demo which simulates the behaviour described, with 'animate' enabled or not, hiding navigation within static options of a tab will not trigger it back, since static options are calculated once, and whatever `attachMode` you are choosing, the child is going to be attached to the parent, so no options will be applied once the view is attached to the bottom tabs.

The problem is that calling `mergeOptions` changing `selectedTab` will not trigger applying options, since the merge options is done on `this` or `this.props.componentId` which is not bottomTabs, while you want to change the bottomTabs behaviour, so, whenever you want to change the bottom tab options via merge options you need to assign an id to the bottom tabs and call merge options with visibility change on it, 
```
 Navigation.mergeOptions('MainBottomTabs', {
              bottomTabs: {
                currentTabIndex: 0,
                visible: true,
              },
            });
```

and setRoot code would be:

```
 Navigation.setRoot({
    root: {
      bottomTabs: {
        id: 'MainBottomTabs',
        options: {
```        
branch: 
https://github.com/wix/react-native-navigation/compare/bottom_bar_visibility

**Comment by swabbass** [comment] 2021-12-06 10:22
Keep in mind, no one shared with us a reproducible demo, which can point to what is misbehaving, so what I'm doing is trying to guess, so, kindly, provide us with sufficient info in order to have meaningful issue diagnoses.

**Comment by swabbass** [comment] 2021-12-06 13:47
The issue is fixed, here, https://github.com/wix/react-native-navigation/pull/7389.

**Closed** 2021-12-06 14:21 UTC
Labels: platform: Android, type: accepted/bug

**Comment by swabbass** [comment] 2021-12-06 18:44
checkout 7.24.0-snapshot.459, report here if it fixed, soon 7.24.1 will be released

**Comment by johnhaup** [comment] 2021-12-07 00:02
@swabbass I copied the changes in the above branch into my local node module for this repo and it fixed the issue :)

Do you have an estimate on when 7.24.1 will be published?

Thanks!

**Comment by swabbass** [comment] 2021-12-07 05:50
This week, I'll close a couple of bugs and release a new one. Thx for the feedback.
