### ISSUE TITLE
[V2]TopBar icon button dosen't work

### ISSUE THREAD

**Issue by jarrx** [wix/react-native-navigation#3525] opened 2018-07-09 18:44 UTC
### Issue Description

Trying to set a rightButton to topBar that is an icon.
I've tried different icons but all gets white and the title and other topBar buttons get aligned incorrectly.

### Steps to Reproduce / Code Snippets / Screenshots

```
  static get options() {
    return {
      topBar: {
        title: {
          text: 'Screen',
        },
        rightButtons: [
          {
            icon: require('../../manIcon.png'),
            id: 'buttonId'
          },
        ]
      },
    };
  }
```

This is what it looks like 
![skarmavbild 2018-07-09 kl 20 41 37](https://user-images.githubusercontent.com/31743687/42469630-91a6ae20-83b8-11e8-8127-bf37aabc634b.png)

---
### Environment
* React Native Navigation version: ^2.0.2394
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): IOS, android?
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, debug

**Comment by danhilltech** [comment] 2018-07-12 14:14
I have the same issue. Both debug and release builds.

**Comment by danhilltech** [comment] 2018-07-12 14:19
Ok, this is caused by the disableIconTint: false option. Setting this to true results in the icon rendering correctly.

**Comment by yogevbd** [comment] 2018-08-23 08:14
Should be fixed in latest versions

**Closed by yogevbd** 2018-08-23 08:14 UTC
Labels: platform: iOS, v2
