### ISSUE TITLE
Android navigation doesn't work (after statusbar style : dark)

### ISSUE THREAD

**Issue by webforuse** [wix/react-native-navigation#6398] opened 2020-07-14 15:17 UTC
### Issue Description

If you install statusbar style dark on Android, navigation doesn't work

1. SetRoot(Screen1)
2. Push(Screen2) statusBar : {style: dark}
3. Pop(Screen1)
4. Push(Screen2)  doesn't work (if statusbar style set to : default or light = perfect work)

Simulator Android also work perfect

---
### Environment
* React Native Navigation version: 6.9.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): ONLY Android 
* Device info (Simulator/Device? OS version? Debug/Release?): Real Device (Redmi 6A - 8.1.0)

**Comment by jinshin1013** [comment] 2020-07-16 04:36
@webforuse Hi there, I cannot reproduce this problem, would you be able to provide a minimal reproduction on Github and some error logs you are getting? Cheers!

**Comment by webforuse** [comment] 2020-07-16 07:47
Hi @jinshin1013 sure

my test repo 
https://github.com/webforuse/sandbox

pay attention!
detailScreen.js

 statusBar: {
          style: 'dark',
          visible: true,
          drawBehind: true,
          backgroundColor: 'transparent',
        },


nowScreen.js

statusBar: {
          visible: true,
          drawBehind: true,
          backgroundColor: 'transparent',
          style: 'light',
        },

and video
![Screenrecorder-2020-07-16-10-38-05-89](https://user-images.githubusercontent.com/37406224/87641803-4ad56980-c751-11ea-9b7b-09a90d838cf7.gif)

**Comment by jinshin1013** [comment] 2020-07-16 09:40
Hi @webforuse I pulled down your repo and ran it on my emulator AND my android device but just cannot reproduce what you are experiencing. I haven't changed any code FYI. It could be an issue with your local setup or that specific android device. I'm not sure how I would be able to assist you further so going to close this issue for now.

Feel free to provide us with some more info like native logs (you can get this from Android Studio).

![Kapture 2020-07-16 at 19 34 58](https://user-images.githubusercontent.com/17612922/87655429-94e33d00-c79b-11ea-9adc-51a6a61b9949.gif)

**Closed by jinshin1013** 2020-07-16 09:40 UTC
Labels: user: more info needed, user: requires reproduction

**Comment by guyca** [comment] 2020-07-16 09:49
I think this is an Android bug which only reproduces on Android 8 and below. If this is indeed the case, there's not much we can do about it.

**Comment by webforuse** [comment] 2020-07-16 09:49
@jinshin1013 thanks.
My logs from Android Studio

2020-07-16 12:47:06.919 1848-5075/? I/ADB_SERVICES: post waitpid (pid=5074) status=0000
2020-07-16 12:47:06.987 1848-5078/? I/ADB_SERVICES: post waitpid (pid=5077) status=0000
2020-07-16 12:47:08.045 523-563/? D/connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
2020-07-16 12:47:08.272 1137-1589/? D/NetworkController.MobileSignalController(1): getDataNetTypeFromServiceState slotId=0  isUsingCarrierAggregation=false
2020-07-16 12:47:08.273 1137-1589/? D/NetworkTypeUtils: getDataNetTypeFromServiceState:srcDataNetType = 0, destDataNetType 0
2020-07-16 12:47:08.275 1137-1589/? D/MobileSignalController: updateDataType mSelectedDataTypeIcon[0]=0, mSelectedDataActivityIndex=0
2020-07-16 12:47:08.275 1137-1589/? D/TelephonyIcons: getSignalStrengthIcon: slot=0, inetCondition=1, level=4, roaming=false
2020-07-16 12:47:08.278 1137-1589/? D/TelephonyIcons: null signal icon name: drawable/stat_sys_signal_null
2020-07-16 12:47:08.279 1137-1589/? D/TelephonyIcons: getDataTypeIcon sub=0
2020-07-16 12:47:08.280 1137-1589/? D/TelephonyIcons: null signal icon name: drawable/stat_sys_signal_null
2020-07-16 12:47:08.290 393-564/? I/BufferQueueProducer: [StatusBar#0](this:0xa3f48000,id:3,api:1,p:1137,c:393) queueBuffer: fps=1.29 dur=1545.98 max=974.17 min=571.81
2020-07-16 12:47:08.305 393-393/? I/DisplayDevice: [Built-in Screen (type:0)] fps:1.291620,dur:1548.44,max:976.39,min:572.05
2020-07-16 12:47:08.456 393-429/? I/BufferQueueProducer: [com.sandbox/com.sandbox.MainActivity#0](this:0xa4188000,id:1023,api:1,p:3968,c:393) queueBuffer: fps=2.01 dur=8974.71 max=8704.93 min=12.05
2020-07-16 12:47:08.593 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.createReactContextInBackground()
2020-07-16 12:47:08.593 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-16 12:47:08.600 3968-4297/com.sandbox I/ReactNativeJS: Running "app.DetailScreen" with {"initialProps":{"componentId":"Component42"},"rootTag":191}
2020-07-16 12:47:09.042 525-525/? I/thermal_repeater: [recvMdThermalInfo] ret=33, strLen=127,  2, 32767, -127, 101, 32767, 3745
2020-07-16 12:47:09.063 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.createReactContextInBackground()
2020-07-16 12:47:09.063 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-16 12:47:09.068 3968-4297/com.sandbox I/ReactNativeJS: Running "app.DetailScreen" with {"initialProps":{"componentId":"Component44"},"rootTag":201}
2020-07-16 12:47:09.315 393-393/? I/DisplayDevice: [Built-in Screen (type:0)] fps:50.494175,dur:1010.02,max:161.09,min:15.25
2020-07-16 12:47:09.468 393-564/? I/BufferQueueProducer: [com.sandbox/com.sandbox.MainActivity#0](this:0xa4188000,id:1023,api:1,p:3968,c:393) queueBuffer: fps=60.27 dur=1012.03 max=34.78 min=9.51
2020-07-16 12:47:09.469 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.createReactContextInBackground()
2020-07-16 12:47:09.470 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-16 12:47:09.478 3968-4297/com.sandbox I/ReactNativeJS: Running "app.DetailScreen" with {"initialProps":{"componentId":"Component46"},"rootTag":211}
2020-07-16 12:47:09.479 523-568/? D/connsyslogger: new boot up file : /data/connsyslog/bootupLog/WIFI_FW_2020_0714_181238.clog
2020-07-16 12:47:09.479 523-568/? D/connsyslogger: Close log file: Success.
2020-07-16 12:47:09.479 523-568/? D/connsyslogger: File's new name is: /data/connsyslog/bootupLog/WIFI_FW_2020_0714_181238.clog
2020-07-16 12:47:09.485 523-568/? I/connsyslogger: thrLogWriter: LogBuf=225.088867KB,idx=0
2020-07-16 12:47:09.549 3968-3989/com.sandbox I/zygote: Background concurrent copying GC freed 341361(10MB) AllocSpace objects, 3(60KB) LOS objects, 72% free, 4MB/16MB, paused 216us total 117.665ms
2020-07-16 12:47:09.725 940-1064/? D/WifiStateMachine:  MtkL2ConnectedState 131155 196 0, mShouldDeferDisableWifi = false, mState = MONITORING
2020-07-16 12:47:09.732 4805-4805/? I/MemoryTrimmer: Trimming objects from memory, since app is in the background.
2020-07-16 12:47:09.848 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.createReactContextInBackground()
2020-07-16 12:47:09.848 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-16 12:47:09.853 3968-4297/com.sandbox I/ReactNativeJS: Running "app.DetailScreen" with {"initialProps":{"componentId":"Component48"},"rootTag":221}
2020-07-16 12:47:10.046 523-563/? D/connsyslogger: SD_LOG_ROOT is /mnt/sdcard/mtklog/connsyslog/fw.
2020-07-16 12:47:10.325 393-393/? I/DisplayDevice: [Built-in Screen (type:0)] fps:61.375938,dur:1010.17,max:17.75,min:14.98
2020-07-16 12:47:10.345 940-1048/? D/MtkDataShapingUtils: openLteGateByDataShaping datashaping instance is null
2020-07-16 12:47:10.358 1884-2288/? W/PushService: 2020-07-16 12:47:10,356 - [WARN::PushService] - [Thread:93] JOB: Handle intent action = com.xiaomi.push.timer
2020-07-16 12:47:10.360 1884-2288/? W/PushService: 2020-07-16 12:47:10,359 - [WARN::PushService] - [Thread:93] Service called on timer
2020-07-16 12:47:10.366 1884-2288/? W/PushService: 2020-07-16 12:47:10,366 - [WARN::PushService] - [Thread:93] [Slim] SND ping id=0
2020-07-16 12:47:10.388 1884-31085/? W/PushService: 2020-07-16 12:47:10,388 - [WARN::PushService] - [Thread:198] [Slim] RCV ping id=0
2020-07-16 12:47:10.392 1884-2288/? W/PushService: 2020-07-16 12:47:10,390 - [WARN::PushService] - [Thread:93] TinyData TinyDataCacheProcessor.pingFollowUpAction ts:1594892830390
2020-07-16 12:47:10.393 1884-2288/? W/PushService: 2020-07-16 12:47:10,393 - [WARN::PushService] - [Thread:93] TinyData TinyDataCacheProcessor.pingFollowUpAction !canUpload(uploader) ts:1594892830393
2020-07-16 12:47:10.478 393-428/? I/BufferQueueProducer: [com.sandbox/com.sandbox.MainActivity#0](this:0xa4188000,id:1023,api:1,p:3968,c:393) queueBuffer: fps=61.39 dur=1009.92 max=19.39 min=13.34
2020-07-16 12:47:10.529 4805-5070/? W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: lu@92a2d8a
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1502)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1649)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:713)
        at cg.b(:com.google.android.gms.dynamite_measurementdynamite@202414046@20.24.14 (040306-0):1)
        at cg.a(:com.google.android.gms.dynamite_measurementdynamite@202414046@20.24.14 (040306-0):6)
        at lv.A(:com.google.android.gms.dynamite_measurementdynamite@202414046@20.24.14 (040306-0):10)
        at lg.a(:com.google.android.gms.dynamite_measurementdynamite@202414046@20.24.14 (040306-0):3)
        at ea.run(:com.google.android.gms.dynamite_measurementdynamite@202414046@20.24.14 (040306-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at jb.run(:com.google.android.gms.dynamite_measurementdynamite@202414046@20.24.14 (040306-0):6)
2020-07-16 12:47:10.663 498-1115/? D/AALLightSensor: newLux = 15, [18, 17] -> 15
2020-07-16 12:47:10.718 393-429/? I/BufferQueueProducer: [StatusBar#0](this:0xa3f48000,id:3,api:1,p:1137,c:393) queueBuffer: fps=0.82 dur=2428.25 max=1998.61 min=429.65
2020-07-16 12:47:11.218 523-565/? E/connsyslogger: Bootup Log before deleted: 9 log files!
2020-07-16 12:47:11.218 523-565/? E/connsyslogger: remove Log: /data/connsyslog/bootupLog/WIFI_FW_2020_0712_124032.clog in data!
2020-07-16 12:47:11.222 523-565/? E/connsyslogger: Bootup Log after deleted: 8 log files!
2020-07-16 12:47:11.222 523-565/? E/connsyslogger: Bootup Log: 8 log files! 
2020-07-16 12:47:11.356 505-548/? I/thermald: inotify_add_watch error!
2020-07-16 12:47:11.356 505-548/? I/thermald: Error 2: No such file or directory
2020-07-16 12:47:11.730 393-429/? I/BufferQueueProducer: [StatusBar#0](this:0xa3f48000,id:3,api:1,p:1137,c:393) queueBuffer: fps=0.99 dur=1011.87 max=1011.87 min=1011.87
2020-07-16 12:47:11.744 393-393/? I/DisplayDevice: [Built-in Screen (type:0)] fps:17.615429,dur:1419.21,max:1012.90,min:15.16

**Comment by webforuse** [comment] 2020-07-16 09:53
> I think this is an Android bug which only reproduces on Android 8 and below. If this is indeed the case, there's not much we can do about it.

I think this is still specific to the device and launcher (Mi Xiaomi)

Because the simulator does not have such a problem.

Thank you all for your research

In the logs only this is mentioned about StatusBar
You can also see that the screen should be shown

2020-07-16 12:47:08.279 1137-1589/? D/TelephonyIcons: getDataTypeIcon sub=0
2020-07-16 12:47:08.280 1137-1589/? D/TelephonyIcons: null signal icon name: drawable/stat_sys_signal_null
2020-07-16 12:47:08.290 393-564/? I/BufferQueueProducer: [StatusBar#0](this:0xa3f48000,id:3,api:1,p:1137,c:393) queueBuffer: fps=1.29 dur=1545.98 max=974.17 min=571.81
2020-07-16 12:47:08.305 393-393/? I/DisplayDevice: [Built-in Screen (type:0)] fps:1.291620,dur:1548.44,max:976.39,min:572.05
2020-07-16 12:47:08.456 393-429/? I/BufferQueueProducer: [com.sandbox/com.sandbox.MainActivity#0](this:0xa4188000,id:1023,api:1,p:3968,c:393) queueBuffer: fps=2.01 dur=8974.71 max=8704.93 min=12.05
2020-07-16 12:47:08.593 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.createReactContextInBackground()
2020-07-16 12:47:08.593 3968-3968/com.sandbox D/ReactNative: ReactInstanceManager.attachRootViewToInstance()
2020-07-16 12:47:08.600 3968-4297/com.sandbox I/ReactNativeJS: Running "app.DetailScreen" with {"initialProps":{"componentId":"Component42"},"rootTag":191}

**Comment by jinshin1013** [comment] 2020-07-16 10:26
Hmm yeah I see. You could try using StatusBar component from react-native to see if it can be worked around.

**Comment by webforuse** [comment] 2020-07-16 10:29
Thanks for replying
