### ISSUE TITLE
[android] open remote debug , react-native-navigation not work

### ISSUE THREAD

**Issue by Hanruis** [wix/react-native-navigation#281] opened 2016-09-06 07:36 UTC
like the title ...  when i disable remote debug , it work greate.  but when enabled,  both Navigation.startSingleScreenApp, and Navigation.startTabBasedApp not work ..

i trace it ,and find that it calls `NativeReactModule.startApp(activityParams);` , so may be something  wrong in native code ....

RN0.31

**Comment by DanielMaly** [comment] 2016-09-06 09:25
I am seeing this issue too. The native logs read:

`09-06 11:23:11.741 24440-24467/com.sanofibabyfe W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
09-06 11:23:11.742 24440-24467/com.sanofibabyfe W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {2634651} sending message to a Handler on a dead thread
                                                                java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {2634651} sending message to a Handler on a dead thread
                                                                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                    at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                    at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                    at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                    at android.os.Handler.post(Handler.java:326)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                    at java.lang.Thread.run(Thread.java:818)
09-06 11:23:11.742 24440-24467/com.sanofibabyfe W/unknown:React: Tried to enqueue runnable on already finished thread: 'native_modules... dropping Runnable.
09-06 11:23:11.742 24440-24467/com.sanofibabyfe W/MessageQueue: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {2634651} sending message to a Handler on a dead thread
                                                                java.lang.IllegalStateException: Handler (com.facebook.react.bridge.queue.MessageQueueThreadHandler) {2634651} sending message to a Handler on a dead thread
                                                                    at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
                                                                    at android.os.Handler.enqueueMessage(Handler.java:631)
                                                                    at android.os.Handler.sendMessageAtTime(Handler.java:600)
                                                                    at android.os.Handler.sendMessageDelayed(Handler.java:570)
                                                                    at android.os.Handler.post(Handler.java:326)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.runOnQueue(MessageQueueThreadImpl.java:61)
                                                                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                    at android.os.Looper.loop(Looper.java:148)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
                                                                    at java.lang.Thread.run(Thread.java:818)
09-06 11:23:11.778 24440-24459/com.sanofibabyfe E/Surface: getSlotFromBufferLocked: unknown buffer: 0xaa0c3260
09-06 11:23:11.849 24440-24459/com.sanofibabyfe E/Surface: getSlotFromBufferLocked: unknown buffer: 0xaa0c3260
09-06 11:23:11.888 24440-24541/com.sanofibabyfe E/BluetoothAdapter: Bluetooth binder is null
09-06 11:23:11.894 24440-24541/com.sanofibabyfe E/ReactNativeJNI: Unable to load script from file`

**Comment by DanielMaly** [comment] 2016-09-06 13:10
I think it's caused by https://github.com/facebook/react-native/issues/9436. Anything that calls native code during the initial JS load gets dropped by the executor. It should be fixed in 0.33. I'm trying to find a workaround but I'm currently unable to find one.

**Comment by Hanruis** [comment] 2016-09-12 02:38
@DanielMaly  thx.....  it said this bug caused by this line of code ... so do you have any idea that how to rebuild react-native  package ?  so we can just delete the line of code and get it work??

i had try npm rebuild react-native & react-native upgrade...but it not work ..

**Comment by guyca** [comment] 2016-09-12 06:22
@Hanruis https://facebook.github.io/react-native/releases/0.31/docs/android-building-from-source.html

**Comment by DanielMaly** [comment] 2016-09-12 06:31
@guyca Is there perhaps a workaround we could put into RNN? Like firing an event in JS when the initial load is complete?

**Comment by guyca** [comment] 2016-09-12 09:03
@DanielMaly I'll try and look into it today/tomorrow but no promises, I got lots of stuff to do in our other projects.

**Comment by Hanruis** [comment] 2016-09-12 09:41
@guyca  thx.. i know it ... so it seems there is no simpler way to fixed this problem.

**Closed** 2016-12-07 14:27 UTC
