### ISSUE TITLE
[Android] Exit app when call function Navigation.pop() on componentDidmount() 

### ISSUE THREAD

**Issue by vietnguyen402** [wix/react-native-navigation#7192] opened 2021-07-17 02:52 UTC
## 🐛 Bug Report

i have two screens, when i press button to move from screen A to screen B and make call function Navigation.pop(componentId) in componentDidMount() on screen B, function the screen freezes and doesn't show screen B and cannot back to screen A, then I press the phone's back button, the app is exited. in two screens I only show one letter to know which screen I'm on

## To Reproduce

1. Create two screens, A and B, on screen A create button to Navigation to screen B, on screen B  call function Navigation.pop(componentId) in componentDidMount().
2. Press the exit button on the phone.
4. app exited.

## Expected behavior

when i call the function Navigation.pop() the screen freezes and nothing can be done. then I press the back button on the phone, the app is exited

## Your Environment

- React Native Navigation version: 3.0.0
- React Native version: 0.60.5
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Device  version Debug & Release

**Comment by yogevbd** [comment] 2021-07-18 09:10
@vietnguyen402 why you try to pop the screen in `componentDidMount`? it doesn't make a lot of sense
Can you elaborate more on your use case?

**Comment by vietnguyen402** [comment] 2021-07-18 12:27
> @vietnguyen402 why you try to pop the screen in `componentDidMount`? it doesn't make a lot of sense
> Can you elaborate more on your use case?

more clearly my problem is when i open any screen and press the back button of this screen the same problem occurs!

**Comment by yogevbd** [comment] 2021-07-18 12:58
I couldn't reproduce this issue. Tried to invoke `Navigation.pop()` in B screen `componentDidMount`.
Could you please submit a reproduction demo? It would be super helpful.

**Comment by vietnguyen402** [comment] 2021-07-18 16:06
> I couldn't reproduce this issue. Tried to invoke `Navigation.pop()` in B screen `componentDidMount`.
> Could you please submit a reproduction demo? It would be super helpful.

i'll create video for this issue, and put to this post

**Comment by vietnguyen402** [comment] 2021-07-27 06:43
https://user-images.githubusercontent.com/34331469/127107975-ccb9968d-db89-403c-acf5-ed11dd6d68e5.mp4

this is description my error

**Comment by vietnguyen402** [comment] 2021-07-27 06:49
this is description my error.

https://user-images.githubusercontent.com/34331469/127108486-c8cb203f-2064-4b5f-b631-568aedab17b1.mp4

**Comment by swabbass** [comment] 2021-08-02 10:39
Hey I tried to reproduce your flow see in a [branch](https://github.com/wix/react-native-navigation/compare/didMountIssue) 
and it did not freeze when animations are disabled all works as expected see:

https://user-images.githubusercontent.com/7227793/127848048-6c793b1a-2cac-4ed7-ac69-b689731f1e94.mov

and when animations are enabled, there is an issue with topbar options, but no freeze the screen got closed:

https://user-images.githubusercontent.com/7227793/127848113-5e9a7f1d-0f14-4140-a1a5-c2d0ef56b1f3.mov

and when calling `Navigation.pop` inside `componentDidAppear()` all flows works correctly:

https://user-images.githubusercontent.com/7227793/127848287-8d135c52-9030-4191-8784-857586863125.mov


Now, I don't understand your use case where you open a screen and when it appears/mounted you need to close it, in my branch I tried to mimic what you described, and the main question is why do you push a screen and close it right away when it once mounted/appeared? It's more elegant and easier to just not open the screen.

either way, you can clone the branch and write a minimal reproducible code that causes your issue, since I could not reproduce it (freezing).

**Comment by vietnguyen402** [comment] 2021-08-04 09:33
@swabbass  Thank you for your help. currently i am using v3. I can't fix it yet but I have a solution for it.

**Closed** 2021-08-04 10:56 UTC
Labels: user: requires reproduction
