### ISSUE TITLE
How to disable nav bar globally for all screens?

### ISSUE THREAD

**Issue by msathis** [wix/react-native-navigation#1217] opened 2017-05-08 19:52 UTC
I tried 
`{
   appStyles: {
     navBarHidden: true
  }
}`

But that doesn't seem to work. Any other way?

**Comment by junedomingo** [comment] 2017-05-09 00:32
@msathis , add `navBarHidden: true` inside `navigatorStyle` object

**Comment by msathis** [comment] 2017-05-09 04:57
Thanks for the reply. But it works only if i have 
`static navigatorStyle = { navBarHidden: true }` in each screen component. How do i disable it globally for all screens at one place? @junedomingo

**Comment by junedomingo** [comment] 2017-05-09 05:12
You don't have to declare it on each screen.
you can add that to the root.
`ex.`
```js
Navigation.startSingleScreenApp({
  screen: {
    ...
    navigatorStyle: {
		navBarHidden: true
	}
  },
  drawer: {
    ...
  },
  ...
});
```

**Comment by msathis** [comment] 2017-05-09 06:00
@junedomingo That's the exact code i have. But it works only for the initial screen which is mentioned in `startSingleScreenApp ` call. Subsequent screens have navBar enabled.  I'm pushing the subsequent screens like this

`this.props.navigator.push({screen: 'myapp.nextscreen'})`

**Comment by junedomingo** [comment] 2017-05-09 06:17
I see. 
my solution for this is, all my global configs for navigator are stored in single file ex. `navigatorStyle.js` which contains
```js
export const navigatorStyle = { 
	navigationBarColor: 'black',
	tabBarButtonColor: 'red',
	tabBarSelectedButtonColor: 'red',
	tabBarBackgroundColor: 'white',
	statusBarColor: '#102642',
	navBarTextColor: 'white',
	navBarButtonColor: 'white',
	navBarBackgroundColor: '#163258',
	statusBarTextColorScheme: 'light',
        navBarHidden: true
};

```

and in my component, every time i push to new screen i will include my navigator styles using spread operator
```js
import { navigatorStyle } from '../_global/navigatorStyles';
...
this.props.navigator.push({
	screen: 'ScreenOne',
	title: '',
	navigatorStyle: {
	  ...navigatorStyle
	}
});
...
```

**Comment by msathis** [comment] 2017-05-09 20:36
This is sad :(  I have to make this change in 100 odd places.

**Comment by braco** [comment] 2017-05-22 22:23
@msathis: you can also do something ugly like this

```
const navigatorStyles = { ... }

const registerScreen = (name, component, styles) => {
   component.navigatorStyle = { ...navigatorStyles, ...styles };
   Navigation.registerComponent(name, () => component)
}

registerScreen('Name', component, { })
```

**Comment by pqkluan** [comment] 2018-02-02 10:44
@braco I don't think it's that ugly. Just one more step and it'll turn into HOC pattern.
I'll close this issue since the problem is solved.

**Closed by pqkluan** 2018-02-02 10:44 UTC

**Comment by voidstarfire** [comment] 2018-08-07 17:31
Anyone else woundering how to do this simply and elegantly.

```
const screenConfig: any = {
  screen: {
    screen: 'SomeScreen',
  },
  appStyle: {
      navBarHidden: true
  }
}

Navigation.startSingleScreenApp(screenConfig)
```
