### ISSUE TITLE
White blank after resume app Android

### ISSUE THREAD

**Issue by moonjava2005** [wix/react-native-navigation#1954] opened 2017-10-01 01:38 UTC
Dear all,
After app sleep in background for a while (note, DO NOT kill app, just press home and open other apps), then, press App icon on launcher screen, the app resume and stuck in white blank screen. You can not press back or any operation. The only way to kill app and start again, it OK

### Steps to Reproduce / Code Snippets / Screenshots

- Open app, using for a white, press HOME to sleep app (DO NOT kill app)
- Open others app in order to system re-take the resource from our app. Choose some heavy apps to open
- Then, touch icon on launcher screen of phone to resume our app
- White blank screen
We using with HeadlessJS as example
`Promise.resolve(Navigation.isAppLaunched())
  .then(appLaunched => {
    if (appLaunched) {
      startApp(); // App is launched -> show UI
    } else {
      new NativeEventsReceiver().appLaunched(startApp); // App hasn't been launched yet -> show the UI only when needed.
    }
  });

function startApp() {
  Navigation.startTabBasedApp({ ... });
}`

---
### Environment
* React Native Navigation version: 1.1.235
* React Native version: 0.48.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Asus Zenfone 4 Pro, Android 7.0, Debug

**Comment by guyca** [comment] 2017-10-01 14:40
Hey @moonjava2005 

Try changing your startup code to the following:

```js
Navigation.isAppLaunched()
      .then((appLaunched) => {
        if (appLaunched) {
          startApp();
        }
        new NativeEventsReceiver().appLaunched(() => {
          startApp();
        });
      });
```

I assume what happens is that the app launched event is dispatched but the receiver isn't registered.

**Comment by moonjava2005** [comment] 2017-10-02 02:41
Dear @guyca 
As I posted in my question, I already used that code when startApp. However, sometimes still white blank screen

**Comment by guyca** [comment] 2017-10-02 04:21
Remove the `else` statement from your code.

**Comment by moonjava2005** [comment] 2017-10-02 04:25
Dear @guyca 
It may be my misunderstood. I think "if" app launched, we call start, else we need to listen until app start
Thanks for your kindly support

**Comment by guyca** [comment] 2017-10-03 07:35
@moonjava2005 I'm closing the issue as it reproduces only with Fabric beta. Lets reopen if you have more information an the matter.

**Closed by guyca** 2017-10-03 07:35 UTC

**Comment by rohanraarora** [comment] 2018-01-18 09:35
@guyca I am also facing the same issue with wix/react-native-notification. In my case the app the app is stuck on white screen if I am launching it for the first time or again after closing the app completely and if I just minimize it and open it again, it runs properly. 

```
let store = configureStore();

    persistStore(store, null, () => {

      console.log("store persisted");
      setupPushMessageListeners(store);
      setupAxiosInterceptor(store);

      if (Platform.OS === 'ios') {
        this.startApp(store)
      }
      else {
        Navigation.isAppLaunched()
          .then(appLaunched => {

            if (appLaunched) {
              console.log("App launched",appLaunched)
              this.startApp(store); // App is launched -> show UI
            }
            new NativeEventsReceiver().appLaunched((event) => {
              console.log("App launched event",event)
              this.startApp(store)
            }); // App hasn't been launched yet -> show the UI only when needed.
          });
      }
    });
```

**Comment by baona95** [comment] 2018-02-25 15:36
@rohanraarora Right, I got the same issue

**Comment by noambonnie** [comment] 2018-02-26 17:58
Experiencing the same issue. 

react-native: 0.51.0
RNN: 1.1.381

My code:

```
    if (Platform.OS === 'android') {
        const appLaunched = await Navigation.isAppLaunched();
        if (appLaunched) {
            startApp(); // App is launched -> show UI
        }
        new NativeEventsReceiver().appLaunched(startApp); // App hasn't been launched yet -> show the UI only when needed.
    }
    else {
        startApp();
    }

```

**Comment by baona95** [comment] 2018-02-26 18:01
@noambonnie You may want to read this as well https://github.com/wix/react-native-navigation/issues/2610

**Comment by noambonnie** [comment] 2018-02-26 18:42
Thanks, @baona95 - I tried overriding clearHostOnActivityDestroy() as proposed by @guyca in https://github.com/wix/react-native-navigation/issues/1022#issuecomment-329432373

But hitting back from root results in blank screen - so that's actually even worse off than where I am now...

Did you find any solution that worked for you?

**Comment by baona95** [comment] 2018-02-26 18:46
It actually worked for me, so I think the v1 has various unexpected results
and edge cases. If your app does not require much I suggest you to check v2
or see the issues section and look for similar bugs.

**Comment by davidliu** [comment] 2018-07-31 01:04
I think the issue is with redux-persist, rather than react-native-navigation.

https://github.com/rt2zz/redux-persist/issues/851

**Comment by kaiiserni** [comment] 2018-10-14 14:44
I have had a similar issue, apparently also with release builds, I think my issue had something to do with how android restores activities and RN.
Anyhow adding a simple key check like so did the trick for me:
``` 
if (store.getState()._persist) {
  _restore();
} else {
  persistStore(store, null, _restore);
}
```
