### ISSUE TITLE
[v2] Bottom tabs visibility problem

### ISSUE THREAD

**Issue by yusufyildirim** [wix/react-native-navigation#3545] opened 2018-07-12 15:30 UTC
### Issue Description

We have an app with bottom tabs. We want to navigate to another screen with hiding the bottom tabs. It's working but causes a UI bug when we go back, appears a white area (exact same height as bottom tabs). You can see below.

### Steps to Reproduce / Code Snippets / Screenshots
Let's assume first screen is HomeScreen (with bottom tabs) and second screen is CommentsScreen. Just pass ```{ bottomTabs: { visible: false, animated: true } }``` to CommentsScreen to hide bottom tabs.

![2018-07-12 18 21 09](https://user-images.githubusercontent.com/22980987/42643030-da25ac42-8600-11e8-98f4-ecdb5e477a00.gif)
![2018-07-12 18 21 57](https://user-images.githubusercontent.com/22980987/42643032-da4f9a0c-8600-11e8-97b2-3ab440b76137.gif)

---
### Environment
* React Native Navigation version: v2 latest
* React Native version: 0.55.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?):  All

**Comment by jp928** [comment] 2018-07-13 08:18
+ 1 same issue here

**Comment by jp928** [comment] 2018-07-13 08:30
@yusufyildirim 
I found if set 
{
   bottomTabs: {
    drawBehind: true
  }
}

will be better

**Comment by yusufyildirim** [comment] 2018-07-13 09:59
@jp928 i tried that too, still same

**Comment by hisothreed** [comment] 2018-07-13 21:12
the same here

**Comment by JohnCdf** [comment] 2018-07-15 16:06
Similar issue here.

Bottom tabs cover content and sometimes cause whitespace mid-drag.
-

![simulator screen shot - iphone 6 - 2018-07-15 at 11 33 38](https://user-images.githubusercontent.com/30275860/42735715-03d567da-8827-11e8-926c-8808b52c9e4b.png)

![600d0472-3402-4cb0-8b37-f315c03f9f5e](https://user-images.githubusercontent.com/30275860/42735739-6e651e42-8827-11e8-888c-26e37acd8971.jpg)

**Comment by InternetExplorer8** [comment] 2018-07-16 12:56
Happens if a ScrollView with scrollbar is available in the parent view. It seems that the ScrollView height is calculated too early or too late.

**Comment by jp928** [comment] 2018-07-16 23:44
@yusufyildirim 
my temporary solution is when pushing to next screen, I declare the bottoms status explicitly so as when I do pop
```javascript
Navigation.push(this.props.componentId, {
      component: {
        name: 'main.Leads',
        options: {
          bottomTabs: {
            visible: false,
            animate: false
          }
        }
      }
    });
```

While pop

```javascript

Navigation.pop(this.props.componentId, {
      options: {
        bottomTabs: {
          visible: true,
          drawBehind: true
        }
      }
    });
```
I am using "react-native-navigation": "^2.0.2411",

Hope this help.

**Comment by phuongwd** [comment] 2018-07-20 08:08
@jp928 thank you, it works on iOS. use drawBehind: true for Android

```
Navigation.push(componentId, {
  component: {
    name   : componentName,
    options: {
      bottomTabs: {
        visible   : false,
        drawBehind: true, // for Android
        animate   : true
      }
    }
  }
});
```

I am using "react-native-navigation": "^2.0.2418"

**Comment by Neilgebbie** [comment] 2018-07-26 10:59
I had this problem in our app and added 

`automaticallyAdjustContentInsets={false}`

To the Scrollview - and it seems to have resolved the issue.

**Comment by manosim** [comment] 2018-07-30 08:43
@Neilgebbie We are having exactly the same issue and unfortunately `automaticallyAdjustContentInsets` or `drawBehind` fixes the problem.

**Comment by Neilgebbie** [comment] 2018-07-30 09:23
@manosim Are you using Flatlist or ScrollView? 

I have the problem on Flatlist but not ScrollView. I'll probably spend tomorrow trying to find a fix for Flatlist.

**Comment by manosim** [comment] 2018-07-30 10:42
@Neilgebbie Using `Flatlist` as well. Tried this but the issue persists:

```javascript
<FlatList
  automaticallyAdjustContentInsets={ false }
  ...
/>
```

Will let you know if I find a workaround!

**Comment by Neilgebbie** [comment] 2018-07-30 11:37
@manosim Ok - I have a feeling that the flstlist is not inheriting the prop I suggested above - because adding it to the scroll view in our other views fixed the bug.

Tomorrow I'll have a dig around and if I find anything I'll let you know.

**Comment by stafak** [comment] 2018-07-30 15:55
I'm using `ScrollView` and the `automaticallyAdjustContentInsets` fix does unfortunately not work for me. In one screen where I've had the flickering issue, there is no difference. In another where I've had the blank area (that is flickering in the GIF above) persist after popping, it started flickering instead.

**Comment by hisothreed** [comment] 2018-07-30 21:43
found something that may help fix this issue,
just give the parent <VIew>  of the <ScrollView> this style 

```js 
style={{
   height: Dimensions.get("window").height, 
   paddingBottom: DEVICE_MODEL === "iPhone X" ? 70 : 50 /// i needed to push the content up because it was hidden behind the tabBar
}}
```

when you push:

```js 
options: {
  bottomTabs: {
      visible: false,
      animate: true,
      drawBehind: true
   }
}
```

**Comment by Vincenttbk** [comment] 2018-07-31 03:46
Is there a fix for V1? Im using V1 right now and encountering the same issue...

**Comment by stafak** [comment] 2018-08-01 15:04
This doesn't actually seem to be related to `ScrollView` in my case - even with a screen that only consists of an empty view I have this problem as long as it has `flex: 1` or `height: '100%'`. @hisothreed's workaround works for me although it is very hacky.

**Comment by pribeh** [comment] 2018-08-02 16:36
I've been using height of the window but I'm finding that across devices (especially new ones with different window areas like the X and newer androids) it is not scaleable. With each new device that now sports a larger screen area than traditional devices requires different offsets. The more complex your design requirements, meaning the more different each screen is, the more superfluous the offsets will have to be. So not only do you need different offset values per device type but per screen. I cannot figure out another option. 

I believe this is now the third or fourth issue posted about the same issue now. If the maintainers of the module have any suggestions as to where we could look to try and solve the underlying cause with RNN it would be much appreciated.

**Comment by kfroemming** [comment] 2018-08-03 03:40
@stafak I can confirm you can reproduce it this way. Good catch.

**Comment by henrikra** [comment] 2018-08-10 06:53
I am also experiencing this with RNN 2.0.2460. I am using `FlatList` Here is video of my bug https://drive.google.com/file/d/1lqfa194el91lAdeqiR1256hSoof-zMzN/view

**Comment by JoMizu** [comment] 2018-08-15 15:04
Can reproduce it very rarely in the simulator. On a real device, always. ```automaticallyAdjustContentInsets={false}``` on ScrollView didn't fix it for me. Any other workarounds?

**Comment by henrikra** [comment] 2018-08-16 05:52
@JoMizu I guess @silyevsk is working on this since he assigned his self to this :)

**Comment by yogevbd** [comment] 2018-08-16 09:37
Fixed `bottomTabs` flakiness.
Hiding bottomTabs is now possible on iOS when pushing screens only.
Shouldn't be any reason to use `bottomTabs.animate`.

**Comment by henrikra** [comment] 2018-08-16 10:27
I have just tested version 2.0.2476 and your fix didn't help @yogevbd . Can other people try also if this helped them?

**Comment by yogevbd** [comment] 2018-08-16 12:07
@henrikra What's your use case? We added e2e tests for it and it looks fine

**Comment by henrikra** [comment] 2018-08-16 13:28
Screen A and B. Both of them have simple `FlatList`. I push new screen B from A. Screen B has `bottomTabs` hidden. When coming back from screen B the screen A's `FlatList` bottom flashes or is cut off like in the Gif above.

**Comment by stafak** [comment] 2018-08-16 13:45
Can confirm the issue still exists.

**Comment by silyevsk** [comment] 2018-08-16 15:43
@henrikra @stafak Somehow, I can't reproduce it. Can you please create a simple project where we can see this happening?

**Comment by henrikra** [comment] 2018-08-17 06:37
Sure here is minimum reproduction repo: https://github.com/henrikra/rnn-bottom-tabs-bug

Here also video with where I can still see the bug with new repo: https://drive.google.com/open?id=1TSn9g3xT_O8J4BmIaQtPUxhOVVd_IcjC

I hope this helps you 👍

**Comment by silyevsk** [comment] 2018-08-18 14:57
@henrikra Thanks! It helped, especially the video (I realised I have to try it many times to reproduce). I still didn't see it on simulator, but after several tries it reproduced on a device. I'll look into it in the coming days.

**Comment by geastwood** [comment] 2018-08-22 13:53
@silyevsk When you checking on the fix, would you also think of possibility to port it to V1? Thanks.

**Comment by yogevbd** [comment] 2018-08-30 09:15
@yusufyildirim Should be solved now. Can you please verify? thanks!

**Comment by geastwood** [comment] 2018-08-30 09:49
@yogevbd what would be the fix for V1? Would you provide a fix for V1 or probably give us a direction how to fix it? Thanks

**Comment by guyca** [comment] 2018-08-30 10:06
@geastwood Sorry but v1 is not supported.

**Comment by geastwood** [comment] 2018-08-30 10:09
@guyca Thanks for the quick response. I know it's not supported. But I guess there is a number of people still suffering from this issue on V1. Not asking to fix it on V1, just to spear a thought on what would be the possible fix and provide us with a direction. That would be much appreciated.

**Comment by guyca** [comment] 2018-08-30 11:26
@yogevbd Can you please explain how you resolved the issue?

**Comment by pribeh** [comment] 2018-08-30 13:41
@yogevbd is this the pull request?

https://github.com/wix/react-native-navigation/commit/0769f6e4dab5e9569ed6298af3860cb2645c8d4a

**Comment by pribeh** [comment] 2018-08-30 13:55
@yogevbd I just tested this but unfortunately it didn't work on my end RNNv2. 

https://github.com/wix/react-native-navigation/commit/feab91de5c248294a4c4cdc613fcf1150aeda155

I just noticed on v2 that if you employ react native tabview on the base screen that it begins flickering and becomes unusable when this issue occurs.

**Comment by yogevbd** [comment] 2018-08-30 14:48
Sorry, my bad, pushed another fix.. will be released in few minutes

**Comment by geastwood** [comment] 2018-08-30 15:12
@yogevbd would you give us a hint how to fix this on V1? Thanks

**Comment by Neilgebbie** [comment] 2018-08-30 15:30
@geastwood - Hey, we have this problem, but we're on the V2 branch. While I have never contributed to a large open source project like this I would assume the steps would be:

Once the fix is confirmed for V2:
- check the release log
- match up the commit or commits that worked to fix this issue
- implement it on the V1 Branch 
- Create a PR

Good luck.

**Comment by pribeh** [comment] 2018-08-30 16:47
@yogevbd actually, it looks like it mostly solves the issue but there still is a very brief flicker. it's a single flash now.

**Comment by stafak** [comment] 2018-08-30 20:31
Yep, still flashing a little unfortunately :(

**Comment by henrikra** [comment] 2018-08-31 10:52
I think this issue should be closed when people have validated that it actually works

**Comment by silyevsk** [comment] 2018-09-02 07:39
This issue  comes from a collision between iOS behaviour with non-translucent tabBar and the way react-native works: If translucency is disabled for tabBar, then for some reason setFrame is called twice on RCTRootView - once with an incorrect (smaller) height, and then with the correct one after that. On iOS native it's not an issue, because only the last one is used. With React-native however, every setFrame triggers an update that is going to UIManager thread and then back to the main thread - which  means it doesn't happen right away. In some cases it causes kind of a race condition (I'm not sure why exactly, need to go deeper to RN code to understand this) that may cause re-rendering with the wrong height, or even endless flickering - looks like changing the height from RN re-triggers additional RN update (but again, I'm not sure how exactly it happens in RN).
Anyways, the problem is not with RNN but with iOS+RN . If tabBar is translucent this won't happen. @yogevbd added a workaround at our side so that the size becomes correct after at most one flickering (which is still annoying but much better than what was sometimes happening until now).

**Comment by pribeh** [comment] 2018-09-02 14:44
@silyevsk looks like setting translucent: true for the tabBar does rectify the problem! Your explanation makes sense. It does suck but at least this "trick" works. And, from my testing just now, you can set the tabBar to translucent and yet have a color and not permit drawing underneath the tabBar so this shouldn't interfere with anyone's design objectives.

**Comment by howg0924** [comment] 2018-09-05 08:55
#1393 Discussion thread for same issue on v1.

**Closed** 2018-11-04 09:37 UTC
Labels: platform: iOS, type: accepted/bug, v2

**Comment by farazirfan47** [comment] 2020-04-13 19:34
Anybody solved this issue for FlatList ?

**Comment by Gavin97Dmello** [comment] 2020-06-01 06:28
From all the testing i have done yet, I can clearly say that the problem is not of the ScrollView or the Flatlist.
The flicker is visible with or without any Flatlist/ScrollView been added to the Screen.

**Comment by Gavin97Dmello** [comment] 2020-06-01 07:20
> ### Issue Description
> We have an app with bottom tabs. We want to navigate to another screen with hiding the bottom tabs. It's working but causes a UI bug when we go back, appears a white area (exact same height as bottom tabs). You can see below.
> 
> ### Steps to Reproduce / Code Snippets / Screenshots
> Let's assume first screen is HomeScreen (with bottom tabs) and second screen is CommentsScreen. Just pass `{ bottomTabs: { visible: false, animated: true } }` to CommentsScreen to hide bottom tabs.
> 
> ![2018-07-12 18 21 09](https://user-images.githubusercontent.com/22980987/42643030-da25ac42-8600-11e8-98f4-ecdb5e477a00.gif)
> ![2018-07-12 18 21 57](https://user-images.githubusercontent.com/22980987/42643032-da4f9a0c-8600-11e8-97b2-3ab440b76137.gif)
> 
> ### Environment
> * React Native Navigation version: v2 latest
> * React Native version: 0.55.4
> * Platform(s) (iOS, Android, or both?): iOS
> * Device info (Simulator/Device? OS version? Debug/Release?):  All


Here's the solution: Set your naviagtions to this configurations.
`"react-navigation-drawer": "^2.3.3",
    "react-navigation": "^4.0.10",
        "react-navigation-stack": "^1.10.3",
        "react-navigation-tabs": "^2.6.2",`

This must fix your issues.

**Comment by AlexChaseJones** [comment] 2022-07-08 18:19
is there another solution for this? going back 4 versions doesn't sound like the best idea

**Comment by AlexChaseJones** [comment] 2022-07-08 18:53
for anyone looking to solve this without downgrading and on v6, instead of using 
```
tabBarStyle: { 
          display: 'none' 
}
```

you can just offset it off screen and it appears to work fine 

```
tabBarStyle: { 
          position: 'relative',
          top: 200  
}
```
