### ISSUE TITLE
bottomtabs icon  become small when i click multi time in ios

### ISSUE THREAD

**Issue by ruchi1234** [wix/react-native-navigation#4420] opened 2018-12-09 05:59 UTC
### Issue Description

When i click multi time on bottomtabs icon of setRoot({bottomTabs}) in ios size of icon is continuously decreasing. and size of icon in ios and android is also not same. Is their any method for animation on click

### Steps to Reproduce / Code Snippets / Screenshots

Click multi time on same icon
---
### Environment
* React Native Navigation version: "^2.2.0"
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT![screen shot 2018-12-09 at 11 28 14 am](https://user-images.githubusercontent.com/273250/49693902-8b4c2900-fba5-11e8-9904-40513ea13e4f.png)

**Comment by chrise86** [comment] 2018-12-09 11:44
I currently have the opposite issue, but only when testing on iOS 10.2 on iPhone 5s. I've not tested any other older devices / OS versions yet, but it does not happen on iOS 12 on iPhone 5s or any of the newer devices with latest OS.

![simulator screen shot - iphone 5s 10 2 - 2018-12-09 at 11 40 16](https://user-images.githubusercontent.com/616956/49696826-c2bbd500-fba7-11e8-8337-3d1ad245b1e0.png)

**Comment by chrise86** [comment] 2018-12-09 12:35
Resolved my issue by balancing the icon insets as explained here https://stackoverflow.com/questions/23306963/ios-tab-bar-icons-keep-getting-larger

**Comment by ruchi1234** [comment] 2018-12-10 10:02
I have resolve this issue in of large icon in ios. But my current problem is when user click on multi time on same icon. icon size is decreasing  on each click 
And in android icon size to smal

**Comment by vshkl** [comment] 2018-12-10 11:45
@ruchi1234 could you please share some core?

**Comment by ruchi1234** [comment] 2018-12-10 14:13
Navigation.setRoot({
      root: {
        bottomTabs: {
          id: 'BottomTabsId',
          children: [
            {
              stack: {
                children: [
                  {
                    component: {
                      name: Constant.Screens.HOME_SCREEN.screen,
                    }
                  }],
                options: {
                  topBar: {
                    visible: false,
                    drawBehind: true,
                    
                  },
                  bottomTab: {
                    icon: Constant.Images.HOME_SCREEN_UNSELECTED,
                    selectedIcon: Constant.Images.HOME_SCREEN_SELECTED,
                    iconInsets: { top: 5 },
                    //fontSize: 20,
                    selectedIconColor: Constant.Colors.appTheme,
                  },
                }

              }
            },
            {
              stack: {
                children: [
                  {
                    component: {
                      name: Constant.Screens.SEARCH_SCREEN.screen,
                    }
                  }],
                options: {
                  topBar: {
                    visible: false,
                    drawBehind: true
                  },
                  bottomTab: {
                    icon: Constant.Images.SEARCH_UNSELECTED,
                    selectedIcon: Constant.Images.SEARCH_SELECTED,
                    iconInsets: { top: 5 },
                    //fontSize: 20,
                    selectedIconColor: Constant.Colors.appTheme,
                  },
                }

              }
            },

            {
              stack: {
                children: [
                  {
                    component: {
                      name: Constant.Screens.PROFILE_SCREEN.screen,
                    },
                  }
                ],
                options: {
                  topBar: {
                    visible: false,
                    drawBehind: true
                  },
                  bottomTab: {
                    icon: Constant.Images.PROFILE_UNSELECTED,
                    selectedIcon: Constant.Images.PROFILE_SELECTED,
                    iconInsets: { top: 5 },
                    selectedIconColor: Constant.Colors.appTheme,
                  }
                }
              },
            },
            {
              stack: {
                children: [
                  {
                    component: {
                      name: Constant.Screens.NOTIFICATION_SCREEN.screen,
                    }
                  }],
                options: {
                  topBar: {
                    visible: false,
                    drawBehind: true
                  },
                  bottomTab: {
                    icon: Constant.Images.NOTIF_TAB_UNSELECTED,
                    selectedIcon: Constant.Images.NOTIF_TAB_SELECTED,
                    iconInsets: { top: 5 },
                    //fontSize: 20,
                    selectedIconColor: Constant.Colors.appTheme,
                  },
                }

              }
            },
            {
              stack: {
                children: [
                  {
                    component: {
                      name: Constant.Screens.SETTING_SCREEN.screen,

                    },
                  }
                ],
                options: {
                  topBar: {
                    visible: false,
                    drawBehind: true
                  },
                  bottomTab: {
                    icon: Constant.Images.SETTING_UNSELECTED,
                    selectedIcon: Constant.Images.SETTING_SELECTED,
                    iconInsets: { top: 5 },
                    selectedIconColor: Constant.Colors.appTheme,
                  },

                },
              }
            },
          ],
        }
      }
    });

**Comment by vshkl** [comment] 2018-12-10 14:52
@ruchi1234 hmm... quite a weird bottom tab definition as for me. Let me share how it done in our app:

```es6
const iconChart = require('src/resources/icons/chart.png')

...

options: {
  bottomTab: {
    text: 'Chart',
    icon: iconCahrt,
  },
  ...
}
```

and default options related to tab:
```es6
bottomTab: {
    iconColor: colors.grayOslo,
    selectedIconColor: colors.blueCerulean,
    textColor: colors.grayOslo,
    selectedTextColor: colors.blueCerulean,
    fontSize: fonts.size.tiny,
  },
```

And that's the icons:
<img width="119" alt="image" src="https://user-images.githubusercontent.com/7419173/49739682-8cfc1680-fca3-11e8-951d-770ab289e921.png">

The same way it's done in the native iOS project and it works well w/o any glitches like that.

**Comment by guyca** [comment] 2018-12-11 12:22
Hey guys, Is this issue reproducible this issue on the playground app?

**Comment by vshkl** [comment] 2018-12-11 17:55
@guyca I managed to reproduce it on my app. The issue it the `iconInsets: { top: 5 },`. As I added it, it started to decrease the icon size with every tap on the tab bar item. Looks like it adds that inset every time.

@ruchi1234 you can fix your issue by removing that `iconInsets: { top: 5 },`, but in general it still an issue.

**Comment by ruchi1234** [comment] 2018-12-12 09:47
Thanks vshkl
Animation issue has been resolve by removing iconInsets: { top: 5 }.  But Icon size in android is still small in compare of ios and in ios Selected icon size is looking larger than unselected icon
![screen shot 2018-12-12 at 3 13 47 pm](https://user-images.githubusercontent.com/273250/49860987-e50c5780-fe20-11e8-83b8-453a981f4b11.png)

**Comment by chrise86** [comment] 2018-12-12 13:14
Yes, if you use 5px inset for top then balance with a -5px inset for bottom:

```
iconInsets: { top: 5, bottom: -5 }
```

**Comment by ruchi1234** [comment] 2018-12-13 06:18
Thanks chrise86 
 The issue of ios Selected icon size is looking larger than unselected icon has been resolve 
 but in android bottom bar icon is still looking  small in compare of Ios
![screen shot 2018-12-13 at 11 46 33 am](https://user-images.githubusercontent.com/273250/49919558-0296fb00-fecd-11e8-9937-cd13cfa17a78.png)

**Comment by Deepaknathtiwari** [comment] 2018-12-17 19:04
Is there any solution for above problem or it is bug of rect native navigation

**Comment by bneigher** [comment] 2019-08-06 18:39
this is still happening on v3.  clicking many times on an icon with insets stacks the insets

**Comment by tiempham** [comment] 2019-11-29 08:39
Same for me!

**Comment by guyca** [comment] 2020-02-07 07:54
Hey guys, I'm closing the issue as icon insets were added to help users center bottomTabs icons when tabs had no titles. We've since fixed the issue and using hardcoded insets isn't needed.
To align your icons use the following:
```js
bottomTabs: {
  titleDisplayMode: 'alwaysHide'
}
```

**Closed by guyca** 2020-02-07 07:54 UTC
Labels: platform: iOS, type: accepted/bug, user: good first task, 📌 pinned
