### ISSUE TITLE
IOS back gesture not working

### ISSUE THREAD

**Issue by maurovisitin** [wix/react-native-navigation#930] opened 2017-03-25 12:30 UTC
After i updated RNN to 2.0.0-experimental.256, swipe gesture to pop screen on IOS is not working anymore. I tried to add "disabledBackGesture: false,"  (wich should be default to false anyway) but no luck. Any suggestion?

---
### Environment
* React Native Navigation version: 2.0.0-experimental.256
* React Native version: 0.43.0-rc.4
* Platform: IOS (both simulator/device and debug/release)

**Comment by Kureev** [comment] 2017-04-06 12:26
Seems it's related to https://github.com/wix/react-native-navigation/commit/03d380f8a9d2fba5d4baf6815201fcebdcfa18c9. If you add it back, it "works".

Although, if you push multiple times and then pop to the very first VC, you can't push anymore.

**Comment by gran33** [comment] 2017-04-08 07:12
@sexykodo Thanks for reporting, can u plz share your `static navigatorStyle = {...}` and your 
```
this.props.navigator.push({
...
navigatorStyle = {...}
...
})

**Comment by sexykodo** [comment] 2017-04-08 09:39
@gran33 
static navigatorStyle = {
    drawUnderNavBar: true,
    navBarTransparent: true,
    navBarTranslucent: true,
    navBarHidden: true,
    tabBarHidden: true,
    drawUnderTabBar: true,
    statusBarTextColorScheme: 'light',
    screenBackgroundColor: SituaColors.darkBg,
    navBarButtonColor: SituaColors.action,
  };

**Comment by Kureev** [comment] 2017-04-08 17:45
In my case I used defaults

**Comment by guyca** [comment] 2017-04-23 09:09
Hey guys,
I wasn't able to reproduce this in the example app. Tried clean install (RN 0.43.3, `latest` rnn), running on simulator. I disabled the `drawer` component and pushed a screen, pop gesture worked as expected.  Perhaps someone can upload an example where the issue reproduces?

**Comment by Kureev** [comment] 2017-04-23 19:49
Sure! I'll make an example this week and let you know! Thanks for keeping an eye on this, really appreciate it

**Comment by Kureev** [comment] 2017-04-23 20:48
Ok, I tried `304` and it worked like a charm! 
@sexykodo, can you try to upgrade to the latest version? Looks like it is fixed now 🙌

**Comment by guyca** [comment] 2017-04-24 06:25
@Kureev Switch to `latest` in package.json, .304 is a pretty old release :)

**Comment by Kureev** [comment] 2017-04-24 07:57
@guyca For some reasons, `latest` & `next` installs a `1.1.x` version 🤔

**Comment by guyca** [comment] 2017-04-24 08:05
In order not to break everyone, `next` points to `latest` for now, but it will be deprecated soon. 👍

**Comment by Kureev** [comment] 2017-04-24 08:12
Great! May I wonder how should I install the latest version now (2.x)?

**Comment by guyca** [comment] 2017-04-24 08:38
2.x isn't published to npm yet. You could clone the repo and checkout v2 branch, then point to that from package.json (`file:../react-native-navigation` I think). Just keep in mind it's a work in progress, a lot features currently supported in v1 still aren't implemented 😃 .

**Comment by Kureev** [comment] 2017-04-24 08:42
@guyca I'd like to help with it, actually. Is there a roadmap or something? Probably community (and me in person) can invest some efforts to bridge missing features and release v2 faster?

**Comment by zhantx** [comment] 2017-04-26 03:20
the back gesture doesn't work when navbar is hidden

**Comment by IamMonkey** [comment] 2017-04-26 09:11
@zhantx How enable the back gesture when navbar is hidden?

**Comment by zhantx** [comment] 2017-04-26 09:30
@IamMonkey Well, that's beyond my capability. Have you reproduced my situation on your project?
BTW, on NavigatorIOS's document there is a prop called [interactivePopGestureEnabled](https://facebook.github.io/react-native/docs/navigatorios.html#interactivepopgestureenabled), which basically is to enable back gesture when navbar is hidden. So facebook developers have faced the same problem when making that component and came up with this prop.
Let's hope collaborators can solve this issue in the future. I have to stick with Navigator cuz I really need back gesture without navbar

**Comment by IamMonkey** [comment] 2017-04-26 09:49
@zhantx thanks

**Comment by messense** [comment] 2017-05-12 10:09
Same issue when navbar is hidden.

**Comment by grundmanise** [comment] 2017-05-22 13:20
Guys, to fix it, I've added https://github.com/wix/react-native-navigation/commit/03d380f8a9d2fba5d4baf6815201fcebdcfa18c9 back and also applied this fix https://github.com/wix/react-native-navigation/issues/428#issuecomment-278268928 on top of it.

@guyca May you recheck this commit please https://github.com/wix/react-native-navigation/commit/03d380f8a9d2fba5d4baf6815201fcebdcfa18c9 it is causing this issue now.

**Comment by thanhzusu** [comment] 2017-08-30 10:37
Hi guys,
After some hours investigating, I found that this bug occurred if your component has called `this.props.navigator.toggleNavBar`, `this.props.navigator.setStyle`, etc. that will call `performAction` in native, then `setStyleOnAppearForViewController` will be called more times. So `originalInteractivePopGestureDelegate` value will be changed incorrectly. When the view controller disappeared, wrong value of `originalInteractivePopGestureDelegate` will continue assign to `self.navigationController.interactivePopGestureRecognizer.delegate`. From now, your app can't execute pop gesture.
I has created a PR for this fixing, please take a look at [1763](https://github.com/wix/react-native-navigation/pull/1763)

**Comment by guyca** [comment] 2017-08-31 11:20
Closing the issue as #1763 is merged. Will reopen if issue persists. Thanks @thanhzusu

**Closed by guyca** 2017-08-31 11:20 UTC
