### ISSUE TITLE
statusBar became to black when push view

### ISSUE THREAD

**Issue by JuoCode** [wix/react-native-navigation#400] opened 2016-10-26 14:39 UTC
### statusBar became to black when push view

Use the following style, first started it's very well, statusBar is transparent and the like `position: fixed` in CSS, when i do a push action it would become black : (

```
  // In component
  static navigatorStyle = {  
    navBarHidden: true,  
    drawUnderNavBar: true,  
    navBarTransparent: true
  }
```

I don't know this is caused by `react-native-navigation` or `react-native`, is there any advices?

### Environment
* React Native Navigation version: 1.0.30
* React Native version: 0.31
* Platform(s) (iOS, Android, or both?): Android
* Device info: Samsung s7, Smartisan t1, both in `Release`

**Comment by guyca** [comment] 2016-10-26 15:02
which platform?

**Comment by kanzitdinov** [comment] 2016-10-27 00:47
@guyca It also happened to me on iOS. As I understand it happens because of ```navBarHidden: true```. On an init screen status bar is light but when you try to push another screen, it becomes black. I've fixed it by adding the following (for iOS only, NavigatorStyle.ios.js file):
```
...
Auth: {
    navBarButtonColor: Colors.white,

    navBarTransparent: true,
    navBarTranslucent: true,
    drawUnderNavBar: true,
    navBarNoBorder: true,

    statusBarTextColorScheme: 'light'
  },
...
```

On the component import NavigatorStyle file and add:
```
...
static navigatorStyle = NavigatorStyle.Auth;
...
```

**Comment by JuoCode** [comment] 2016-10-27 05:33
@guyca On Android

**Comment by guyca** [comment] 2016-10-27 05:55
Thansk @kanzitdinov 
@JuoCode I'm not able to reproduce this. (Maybe I didn't understand you correctly)
I declared
```js
navBarHidden: true,  
drawUnderNavBar: true,  
navBarTransparent: true
```
on two screens, pushed one on top of the other and I don't see any black TopBar. I'll gladly look into this further if you can provide an example project where this issue is reproducible. Thanks.

**Comment by JuoCode** [comment] 2016-10-27 10:03
@guyca I have already improvement the issue description, and i will provide more information about this problem, thanks

**Comment by guyca** [comment] 2016-10-27 10:39
@JuoCode I just noticed you're using v1.0.30 which is deprecated. I'm closing the issue since the bug is fixed in v2.0.
I recommend you upgrade to the experimental v2.0 version. We use it in production for quit some time.
* [Installation guide iOS](https://github.com/wix/react-native-navigation/wiki/Installation---iOS#installation---ios)
* [Installation guide Android](https://github.com/wix/react-native-navigation/wiki/Installation---Android)

**Closed by guyca** 2016-10-27 10:39 UTC

**Comment by JuoCode** [comment] 2016-10-27 10:41
Thanks! I will try it now.

**Comment by guyca** [comment] 2016-10-27 10:48
Great. Let me know if you run into any issues.

**Comment by JuoCode** [comment] 2016-10-27 12:04
After updated to 2.0, i got the following error message when running the app in debug mode.

I found another [StackOverflow thread](http://stackoverflow.com/questions/38870710/error-could-not-get-batchedbridge-make-sure-your-bundle-is-packaged-properly). There is no solution in the thread,  Do you have any suggestion about it? 
```
FATAL EXCEPTION: main
Process: com.zuiqt.duotai, PID: 2901
java.lang.RuntimeException: Could not get BatchedBridge, make sure your bundle is packaged correctly
    at com.facebook.react.cxxbridge.CatalystInstanceImpl.loadScriptFromAssets(Native Method)
    at com.facebook.react.cxxbridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:37)
    at com.facebook.react.cxxbridge.CatalystInstanceImpl.runJSBundle(CatalystInstanceImpl.java:177)
    at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:888)
    at com.facebook.react.XReactInstanceManagerImpl$4.call(XReactInstanceManagerImpl.java:881)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$1.run(MessageQueueThreadImpl.java:74)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    at android.os.Looper.loop(Looper.java:148)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by guyca** [comment] 2016-10-27 12:33
Maybe you missed something in steps 4 or 5 from the [installation guide](https://github.com/wix/react-native-navigation/wiki/Installation---Android)?

Can you show me your `MainAppication.java`?

**Comment by JuoCode** [comment] 2016-10-27 13:21
@guyca That caused by method `isDebug`, I hard code it to return false 😭 . 

But the main problem of the status bar not succeed, it still became black.

I found another problem of `navigatorStyle`, it may be not effect, because when I remove the `StatusBar` component from render method(following), the status bar no longer be transparent
```
<StatusBar barStyle='light-content' translucent={true} backgroundColor={Colors.TRANSPARENT} />
```

**Comment by guyca** [comment] 2016-10-27 13:34
Yeah that's what I thought. 👍 

You don't need to define a `StatusBar` component in your render method.

**Comment by JuoCode** [comment] 2016-10-27 13:45
When i remove the `StatusBar` from render method, the styles status bar is not effect.

**Comment by guyca** [comment] 2016-10-27 14:01
Can you add a screen shot and some code snippets of your navigator style? thanks.

**Comment by guyca** [comment] 2016-10-27 14:11
@JuoCode I read to [docs](https://facebook.github.io/react-native/docs/statusbar.html) for this StatusBar component. It seems just evil and I don't think it will work nicely with RNN - try removing **ALL** `StatusBar` declarations from your JSX.

From the docs:
> It is possible to have multiple StatusBar components mounted at the same time. The props will be merged in the order the StatusBar components were mounted.

That sounds just wrong.

**Comment by JuoCode** [comment] 2016-10-27 14:26
My initial screen is `Update`:
```
Navigation.startSingleScreenApp({
  screen: {
    screen: 'Update'
  },
  portraitOnlyMode: true
})


export class Update extends Component<P & Actions, S> {

  // I declared this in all my component.
  // At the same time, i remove all StatusBar component from all component's render method
  static navigatorStyle = {
    navBarHidden: true,
    drawUnderNavBar: true,
    navBarTransparent: true
  }

  componentDidMount () {
    // check update
    // if there is no update, invoke cancel method to show next screen
  }

  cancel() {
    setTimeout(() => {
      this.props.navigator.resetTo({
        screen: this.props.user.user_token ? 'Dashboard' : 'SignIn'
      })
    }, 1000);
  }
  
  // ... other methods
}
```

When the `Update` show, the status bar is black.
When the `Dashboard` show, the status still black.

![image](https://cloud.githubusercontent.com/assets/3771860/19770918/a77cc0c6-9c93-11e6-9a16-485d219a9998.png)

And i noticed that, the status bar may occupied `content area` and squeeze content down(The circle button in bottom and bottom edge should have more space)

**Comment by JuoCode** [comment] 2016-10-28 05:52
As the above, StatusBar styles that specified use `static navigatorStyle` no effect.

I found and comment [Screen.java#setStatusBarColor](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/screens/Screen.java#L126-L130).

Then use the official `StatusBar` component, it become what I want.
```
<StatusBar backgroundColor={Colors.TRANSPARENT} translucent={true} />
```

![image](https://cloud.githubusercontent.com/assets/3771860/19796246/7a78a3b0-9d15-11e6-86d5-4f0eeaeda10f.png)

**Comment by guyca** [comment] 2016-10-28 08:02
I don't think using `StatusBar` component alongside RNN is a good. Since we have multiple screens mounted at the same time and RN merges `StatusBar` components of all mounted screens you're bound to get unexpected behaviour.

I just spoke to @drorbiran about adding proper support for [Immersive mode](https://developer.android.com/training/system-ui/immersive.html) which is what you're actually looking for.

**Comment by JuoCode** [comment] 2016-10-28 08:37
Sorry, I did not explain it clearly 😭 .

I will use RNN for **Immersive mode** when it's implemented.

**Comment by guyca** [comment] 2016-10-28 10:13
It's ok, no harm done 😄
