### ISSUE TITLE
Statically calling handleDeepLink doesn't work

### ISSUE THREAD

**Issue by jacobjuul** [wix/react-native-navigation#1785] opened 2017-09-03 08:16 UTC
### Issue Description
Calling: 
```javascript
import { Navigation } from 'react-native-navigation'
Navigation.handleDeepLink({ link: 'some/link', payload })
```
from anywhere; doesn't trigger `setOnNavigatorEvent`. 
if I hover call it by from a screens props, it works `this.props.navigator.handleDeepLink({})`

---
### Environment
* React Native Navigation version: 1.1.210
* React Native version: 0.44.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator Iphone7

**Comment by guyca** [comment] 2017-09-03 08:50
Hey @jacobjuul 
Can't reproduce in the example app. In `Drawer.js` I dispatch a deep link statically:

```js
  onPushToFirstTab = () => {
    this.toggleDrawer();
    Navigation.handleDeepLink({
      link: 'tab1/example.Types.Push',
      payload: {title: 'It just works!'}
    });
  };
```

Maybe there's another error in Js that prevents the link from being dispatched. I'm closing for now since this seems to work.

**Closed by guyca** 2017-09-03 08:50 UTC

**Comment by jacobjuul** [comment] 2017-09-04 03:56
Right, I was too quick. The issue is that components aren't mounted when you open a push notification.

**Comment by guyca** [comment] 2017-09-04 05:35
right, I guess you're better off using flux for this flow.

**Comment by srameshr** [comment] 2017-10-15 13:42
@guyca When my app opens from background or cold start it lands on ```Screen A``` now I want to broadcast a ```handleDeepLInk``` event to ```Screen B```. But it never fires. At this point screen B is never mounted or has been visited but```registerScreens``` has been called. How do I solve this?

**Comment by guyca** [comment] 2017-10-15 14:10
@srameshr 
deepLinks are broadcasted to mounted screens. I'm not familiar with your use case, but If a screen is not mounted, you should use redux to handle data flow.

**Comment by srameshr** [comment] 2017-10-15 14:17
Here is my use case:
1. I cold start the app
2. The app opens up and the first screen is ```Screen A```
3. Inside the ```componentDidMount``` of ```Screen A``` I call ```this.props.navigator.handleDeepLink({ link: '/screenB' });
4. Now I want ```Screen B```'s ```onNavigatorEvent``` to be called. But it never does.

**Comment by fullhdpixel** [comment] 2017-12-28 21:58
Can you let me know how you know a particular screen is active?

I have a drawer with several links and I want to add active state to it
