### ISSUE TITLE
3D touch stops working after "Peeking" a view without popping it

### ISSUE THREAD

**Issue by charliesbox** [wix/react-native-navigation#2445] opened 2017-12-30 15:31 UTC
### Issue Description

If a view is "Peeked", without popping it, and then you actually try to pop a view, it will trigger the transition animation, but it won't change to the new view.

At this point, if you press normally to any view that can trigger a navigation, that won't occur anymore.

### Steps to Reproduce

1) Peek a view
2) Don't pop it
3) Peek a view again, and then press harder to pop it
4) The transition won't happen
5) Press that view to navigate
6) Again, the transition won't happen anymore

![demo](https://user-images.githubusercontent.com/10927770/34455385-c33e3324-ed43-11e7-8cff-a8db86f4ced9.gif)

![demo2](https://camo.githubusercontent.com/cfde9283f2f246d6d14daf092389e1dfe21d600f/687474703a2f2f672e7265636f726469742e636f2f54545649754e735243592e676966)

---
### Environment
* React Native Navigation version: v1.1.322
* React Native version: 0.51
* Platform: iOS
* Device info: Simulator/Debug mode

**Comment by guyca** [comment] 2018-01-03 12:50
ping @birkir :)

**Comment by habovh** [comment] 2018-01-09 17:20
I have the same issue. It's kind of funny even the `onPress` event fails though 🤔
I first thought the issue happened because I was calling the same `push()` function in both `onPress` and `onPressIn`, including `preview*` parameters, but I tried calling with completely separate parameters and the issue persists.

**Comment by birkir** [comment] 2018-01-19 19:23
Thanks for the bug report!

This may be a iOS quirk (or not), but when logging out which controller we are previewing, xcode shows the correct one, when committing it also logs the correct one but commits the wrong one. Pretty weird.

I'm investigating this! Funny thing is, sometimes when testing other methods of pushing the preview (like using onLongPress or similar) it works 99% of the time.

So maybe its a timing issue but something has to be fixed on the ObjC side of things.

**Comment by karlsander** [comment] 2018-03-06 11:50
I'm also struggling with this issue. Is there a fix forthcoming? And in the meantime, has anyone found a decent workaround?

**Comment by birkir** [comment] 2018-03-06 13:12
I am busy with other things at the moment.

Use `onLongPress` in stead of `onPressIn` that works!

**Comment by karlsander** [comment] 2018-04-08 14:10
It works, but it doesn't provide a proper Peek & Pop experience. It would be a shame if this never gets fixed, as the Peek and Pop support in react-native-navigation is otherwise great. I understand that theres a lot on your plate and maybe I should just investigate the issue myself. Is fixing this on the map for v2 at least?

**Comment by birkir** [comment] 2018-04-09 19:08
Why doesn't it provide a proper Peek & Pop experience? Too slow?

I always seem to get to a dead end when looking into this issue. AFAIK this hasn't been implemented in V2, and I have a feeling that this won't be an issue in V2.

There is something fundamentally wrong with the navigation controller in V1.

**Comment by habovh** [comment] 2018-06-05 09:38
I believe this issue does not deserve being marked as stale... What do you guys think? Any idea on how to fix this, or do you plan on leaving it as-is in favor of V2?

**Comment by guyca** [comment] 2018-06-05 09:43
Since @birkir implemented this in v2 as well 🙇 and we're not supporting v1 anymore I'm opting to close. @habovh You can easily migrate to v2 using this [library](https://github.com/wix-playground/react-native-navigation-v1-v2-adapter).

**Closed by guyca** 2018-06-05 09:43 UTC

**Comment by habovh** [comment] 2018-06-05 09:46
@guyca that's good news! Thanks for the tip, looking forward to updating to v2!

**Comment by birkir** [comment] 2018-06-05 14:56
V2 does not have *any* issues like V1 has, I think the fundamental changes in how the VC's are managed in V1 vs V2 was the root cause.
