### ISSUE TITLE
[v2] Screen Component loaded 3 times on Android only

### ISSUE THREAD

**Issue by jeprojects** [wix/react-native-navigation#2826] opened 2018-03-07 10:12 UTC
### Issue Description

When application is started it loads the first screen 3 times by the looks of it because the constructor and componentDidMount is called 3 times.

I tested in iOS and I wasn't able to reproduce this issue

### Steps to Reproduce / Code Snippets / Screenshots

1. Create sideMenu, and center stack with topBar
2. Add console.log('test') or alert to constructor or componenetDidMount

---
### Environment
* React Native Navigation version: 2.0.2160
* React Native version: 0.54.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, Debug

**Comment by guyca** [comment] 2018-03-07 12:09
duplicate of #2286

**Closed by guyca** 2018-03-07 12:09 UTC
