### ISSUE TITLE
[RNN2 Android bottomTab Switch labels afterward hide Tabs style problem]

### ISSUE THREAD

**Issue by qiepeipei** [wix/react-native-navigation#3101] opened 2018-04-24 09:35 UTC
### Issue Description

[RNN2 Android bottomTab Switch labels afterward hide Tabs style problem]

### Steps to Reproduce / Code Snippets / Screenshots

Navigation.setRoot({

      bottomTabs: {
          children: [
            {
              component: {
                name: 'navigation.GoodsScreen',
                passProps: {
                  text: 'This is tab 1',
                },
                options: {
                  bottomTab: {
                    title: 'aaa',
                    icon: require('../images/transport.png'),
                    testID: 'FIRST_TAB_BAR_BUTTON1'
                  }
                }
              }
            },
            {
              component: {
                name: 'navigation.GoodsScreen',
                passProps: {
                  text: 'This is tab 1',
                },
                options: {
                  bottomTab: {
                    title: 'bbb',
                    icon: require('../images/contacts.png'),
                    testID: 'FIRST_TAB_BAR_BUTTON3'
                  }
                }
              }
            }
  
          ],
          options: {
            bottomTabs: {
              tabColor: 'rgba(163,165,168,1)',
              selectedTabColor: 'rgba(38,152,243,1)',
              backgroundColor: 'white',
              fontSize: 12,
              testID: 'BOTTOM_TABS_ELEMENT'
            }
          }
        }
});

<View style={{flex:1,backgroundColor:"#f0f0f0"}}>
      <View style={{flexDirection:'row'}}>

            <Button style={{marginRight:10}} onPress={()=>{this.onClickRegPush(false)}}>
            <Text >hide</Text>
            </Button>
            <Button onPress={()=>{this.onClickRegPush(true)}}>
              <Text >show</Text>
            </Button>

        </View>
 </View>

onClickRegPush = async (state)=>{

    await Navigation.mergeOptions(this.props.componentId, {
      bottomTabs: {
        visible:state,
        animate: true
      }
    });

}

[FILL THIS OUT - It will be extremely helpful]
![555](https://user-images.githubusercontent.com/16110628/39563522-232e6fdc-4ee3-11e8-816a-b632dd1f0100.gif)

---
### Environment
* React Native Navigation version: 2.0.2241
* React Native version: 0.54.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by guyca** [comment] 2018-04-25 19:53
@qiepeipei Can you please add more info regarding the issue - it's a bit hard trying to understand an issue from a gif and a mouse gestures.

**Comment by qiepeipei** [comment] 2018-05-03 07:04
gif  already edited

**Comment by qiepeipei** [comment] 2018-05-03 07:05
@guyca Request help

**Comment by qiepeipei** [comment] 2018-05-03 07:06
@guyca gif already edited  please help me

**Comment by guyca** [comment] 2018-05-03 08:48
Hey @qiepeipei 
If you intend to hide the Bottomtabs, you need to layout the screen behind the BottomTabs. Add the following to your screen's options:

```js
bottomtabs: {
  drawBehind: true
}
```

Just note that it's still not implemented - will try to implement it asap

**Comment by qiepeipei** [comment] 2018-05-03 09:03
@guyca thanks   topBar There is also such a bug.

**Comment by qiepeipei** [comment] 2018-05-03 09:05
@guyca thanks topBar Have the same bug

**Comment by qiepeipei** [comment] 2018-05-03 09:28
thank you happy

**Comment by guyca** [comment] 2018-05-14 16:34
From what I understand this is a duplicate of #2996 which will be addressed soon.

**Closed by guyca** 2018-05-14 16:34 UTC
Labels: Android, v2

**Comment by yusufyildirim** [comment] 2018-05-15 20:01
@qiepeipei set translucent true works for you bro, am I wrong @guyca ? I tried and it's working fine

**Comment by yusufyildirim** [comment] 2018-05-15 20:01
Related with https://github.com/wix/react-native-navigation/issues/3209

**Comment by qiepeipei** [comment] 2018-05-16 03:08
@guyca The problem is still .  drawBehind fields Not working .  Click on the click there will be a problem

**Comment by qiepeipei** [comment] 2018-05-16 03:09
@guyca The problem is still . drawBehind fields Not working . Click on the tab will be a problem
