### ISSUE TITLE
navigator.setTitle does not work (RN 0.46.3)

### ISSUE THREAD

**Issue by Maydar** [wix/react-native-navigation#1513] opened 2017-07-16 17:09 UTC
### Issue Description

this.props.navigator.setTitle({ title: '123'}) - does not work properly, I see empty line instead of title

---
### Environment
* React Native Navigation version: 1.136
* React Native version: 0.46.3
* Platform(s) (iOS, Android, or both?): Tested on Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device, Android 5.1 Meizu m2 mini

### Solution

Downgrade version to 1.134

**Comment by masterpetit** [comment] 2017-07-17 15:27
I encountered the same bug on the latest React Native version (0.46.3) and the latest react-native-navigation version (1.1.136).

Bug only occurs on Android:

![android](https://user-images.githubusercontent.com/9072458/28275679-eddecd34-6b14-11e7-9429-e84f9abddf3c.png)
![ios](https://user-images.githubusercontent.com/9072458/28275688-f76f2cc2-6b14-11e7-9d66-f9cb994c5461.png)

**Comment by 8BallBomBom** [comment] 2017-07-17 16:09
+1 same RN version and Nav version.

**Comment by neogermi** [comment] 2017-07-18 10:22
Isn't this a duplicate of #1515 ?

**Comment by masterpetit** [comment] 2017-07-18 10:31
Yes @neogermi .

PR to fix it (not merged yet): https://github.com/wix/react-native-navigation/pull/1516

Quick fix for now, set appStyle:
```appStyle: {  navBarTextFontSize: 12 }```

**Comment by bobmulder** [comment] 2017-07-18 11:12
Thanks @masterpetit for the quick fix. Any idea about the default fontsize? Size `12` looks kinda small...

![image](https://user-images.githubusercontent.com/5465074/28314408-c4a558ce-6bba-11e7-84b3-ff3e61f5635b.png)

**Comment by guyca** [comment] 2017-07-18 11:15
Fixed in v1.1.137 - Thanks @masterpetit

**Closed by guyca** 2017-07-18 11:15 UTC

**Comment by peterlau** [comment] 2018-01-12 21:49
Ran into the issue of `setTitle()` not working on Android with a much later build (1.1.284). Turns out it must be called in `componentDidMount()` and **not** in the component `constructor()`, which is too early.

Just a heads up for anyone encountering this behavior.
