### ISSUE TITLE
warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

### ISSUE THREAD

**Issue by helenachallitanumu** [wix/react-native-navigation#7708] opened 2023-05-04 09:48 UTC
### What happened?

**I'm getting the following warning on app startup after updating the react-native library to 0.71.7:**

warn Package react-native-navigation contains invalid configuration: "dependency.assets" is not allowed,"dependency.hooks" is not allowed. Please verify it's properly linked using "react-native config" command and contact the package maintainers about this.

### What was the expected behaviour?

Run without warnings

### Was it tested on latest react-native-navigation?

- [X] I have tested this issue on the latest react-native-navigation release and it still reproduces.

### Help us reproduce this issue!

- Update react-native library to v0.71.7
- run the app

### In what environment did this happen?

React Native Navigation version: 7.32.1
React Native version: 0.71.7
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 20.0.0

**Comment by fotos** [comment] 2023-06-11 22:10
Duplicate of #7647.

**Closed** 2023-08-22 12:03 UTC
Labels: type: accepted/bug, needs triage
