### ISSUE TITLE
SharedElementTransition some components disappear after animation is complete

### ISSUE THREAD

**Issue by bneigher** [wix/react-native-navigation#6150] opened 2020-04-22 08:46 UTC
### Issue Description

It seems that whenever I return to a page that has had an element transitioned, the text disappears (or the image is blocking it covers it.

![ezgif-4-31026e38ede2](https://user-images.githubusercontent.com/4627728/79960195-fc5a4c80-8439-11ea-9498-29f1c7b419f1.gif)

### Steps to Reproduce / Code Snippets / Screenshots

```javascript
Navigation.push("screen", {
  component: {
    name: "Test",
    passProps: {},
    options: {
      animations: {
        push: {
          sharedElementTransitions: [
            {
              fromId: `image${id}`,
              toId: `image${id}Dest`,
              duration: 500,
            },
            {
              fromId: `title${id}`,
              toId: `title${id}Dest`,
              duration: 500,
            },
          ],
        }
      }
    }
  }
})
```

source
```javascript
<ImageBackground
  nativeID={`image${this.props.id}`}
  style={cardStyle}
  imageStyle={{ borderRadius: 4, resizeMode: 'stretch' }}
  source={{ uri: this.state.bgImage }}>
  <View style={{ flex: 1, flexDirection: 'row' }}>
    <View style={{ flex: 2 }}>
      <Text
        nativeID={`title${this.props.id}`}
        adjustsFontSizeToFit={true}
        allowFontScaling={true}
        numberOfLines={4}
        minimumFontScale={0.6}
        style={[textStyle, textColorStyle]}>
        {meta.friendlyName}
      </Text>
    </View>
    <View style={{ flex: 1 }}></View>
  </View>
</ImageBackground>
```

target
```javascript
<ImageBackground
  nativeID={`image${id}Dest`}
  source={{
    uri:image,
  }}
  style={styles.imageStyle}
  imageStyle={{
    resizeMode: 'stretch',
  }}>
  <View
    style={{
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: 15,
    }}>
    <Text
      style={textColorStyle}
      nativeID={`title${id}Dest`}
      adjustsFontSizeToFit={true}
      allowFontScaling={true}
      numberOfLines={2}
      minimumFontScale={0.6}>
      {meta.friendlyName}
    </Text>
  </View>
  <TouchableOpacity
    style={styles.navButton}
    onPress={() => {
      pop(this.props.componentId);
    }}
    hitSlop={{ top: 20, bottom: 20, left: 20, right: 20 }}>
    <FontAwesome5
      size={26}
      solid
      style={[textColorStyle]}
      name="chevron-left"
    />
  </TouchableOpacity>
</ImageBackground>
```

I've noticed something potentially similar with animation end states not being correct with modal dismisses.. so potentially related?

When adding the pop animation, I can see it moving all the way back correctly, but when it completes, it disappears

---
### Environment
* React Native Navigation version: 6.4.0
* React Native version:  0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): ALL

**Comment by guyca** [comment] 2020-04-23 05:15
@bneigher Can you please try to remove some of the properties in the `<Text>` component so we know if one of the is the culprit.

Also, please inspect the layout after the pop transition using [Xcode's layout inspector](https://developer.apple.com/library/archive/documentation/ToolsLanguages/Conceptual/Xcode_Overview/ExaminingtheViewHierarchy.html) to confirm your suspicions that the Text is blocked by the Image.
It could be that the text is there but some of it's properties are incorrect causing it to appear invisible.

Have you tried adding logs to `render()` to check if this is an issue with props?

**Comment by guyca** [comment] 2020-04-23 05:20
@yogevbd Do we even manipulate elements in the from screen? 🤔

**Comment by bneigher** [comment] 2020-04-23 05:54
@guyca:

> I've noticed your layout is problematic to being with. Having a shared element is a child of another shared element can lead to unexpected results. Please refactor your layout so the to elements are siblings and don't have parent-child relationships. We'll update the docs with this information.

On this, I've already tried to remove the shared element behavior on the text value (only sharing the ImageBackground component) and the upon return to the source the text still disappears, so I think we can eliminate the suspicion of shared element child / parent being the issue.

Running over the other suggestions now.

**Comment by bneigher** [comment] 2020-04-23 05:57
> Can you please try to remove some of the properties in the <Text> component so we know if one of the is the culprit.

Testing with a completely plain Text component in both source and target still displays the issue

**Comment by guyca** [comment] 2020-04-23 06:00
@bneigher Can you try giving the Text element a high `zIndex` ? Like `zIndex: 99` or something

**Comment by bneigher** [comment] 2020-04-23 06:03
@guyca I have that in my ugly code that was cleaned in formatting my example up top.  No luck

I'm thinking the issue is with the `ImageBackground` component, is that possible?  When moving the text outside of there it works (which makes sense), only breaks on any of the content that is inside the ImageBackground component.  I believe it is at least animating because the nativeID is passed through the props to the underlying Image component inside it, but it is possible that the props live on both the Component (ImageBackground (View), AND it's child (Image))

**Comment by guyca** [comment] 2020-04-23 06:18
> When moving the text outside of there it works 
Having parent-child relationships between shared elements can lead to unexpected results. 

> I believe it is at least animating because the nativeID is passed through the props to the underlying Image component inside it, but it is possible that the props live on both the Component (ImageBackground (View), AND it's child (Image))

That's definitely a possibility. I have no idea how the native layout created by this JSX layout looks like.

**Comment by guyca** [comment] 2020-04-23 06:19
At any case, I'm closing the issue since it seems like it's caused by complex parent-child relationships which we don't plan on supporting in the foreseeable future.

Please refactor your layout so the image and text are siblings, if the issue persists we'll reopen 👍

**Closed by guyca** 2020-04-23 06:19 UTC
Labels: platform: iOS, user: waiting for response

**Comment by bneigher** [comment] 2020-04-23 06:20
Alright, will refactor until she works.  Thanks for the help

**Comment by guyca** [comment] 2020-04-23 06:26
np, would love to see the end result! The animation already looks great 💯 DM us on https://twitter.com/ReactNativeNav 🙏

**Comment by bneigher** [comment] 2020-04-23 06:59
thanks, and thanks for this library. despite some early challenges, this library is arguably one of the most powerful additions to react-native apps and has been a great investment into my product thus far

**Comment by KhimGurung** [comment] 2021-08-11 12:53
When returning back, it has stack navigation's default back animation. that could be the reason. try to make shared element animation like navigating to detail page when going back as well.
