### ISSUE TITLE
Navigation.setRoot crash on iOS with rnn v2.17.0

### ISSUE THREAD

**Issue by Pandan** [wix/react-native-navigation#4961] opened 2019-04-09 12:42 UTC
### Issue Description

I updated RNN from 2.16.0 to 2.17.0 today.
After the update I get an error when calling Navigation.setRoot when starting the app.
I tested reverting to 2.16.0 and then it starts working again. 

```                                              
Navigation.setRoot({
        root: {
          stack: {
            children: [
              {
                component: {
                  name: 'homeScreen',
                },
              },
            ],
          },
        },
 });
```                                      
I get this error in xcode:
```  
Exception '-[RNNRootViewController initWithLayoutInfo:creator:options:defaultOptions:presenter:eventEmitter:]: unrecognized selector sent to instance 0x106546f60' was thrown while invoking setRoot on target RNNBridgeModule with params (
    setRoot3,
        {
        modals =         (
        );
        overlays =         (
        );
        root =         {
            children =             (
                                {
                    children =                     (
                    );
                    data =                     {
                        name = homeScreen;
                        options =                         {
                        };
                    };
                    id = Component2;
                    type = Component;
                }
            );
            data =             {
            };
            id = Stack1;
            type = Stack;
        };
    },
    56,
    57
)
```     
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.59.4
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device, iOS 12.2

**Comment by shuzootani** [comment] 2019-04-09 13:07
same here

### Environment
- React Native Navigation version: 2.17.0
- React Native version: 0.59.2
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Device, iOS iPhoneX 12.1

<img width="338" alt="Screen Shot 2019-04-09 at 22 02 18" src="https://user-images.githubusercontent.com/19385183/55802729-c9396980-5b13-11e9-84c1-9077b65d8fdc.png">

**Comment by aminosman** [comment] 2019-04-14 08:11
Any update on this?

**Comment by guyca** [comment] 2019-04-14 08:13
hey @aminosman, we're out of the office for the next couple of days and will get to this on Wednesday. Sorry for the inconvenience.

**Comment by aminosman** [comment] 2019-04-14 08:16
Thanks @guyca

**Comment by sepiddd** [comment] 2019-04-16 09:51
same here

**Comment by mromarreyes** [comment] 2019-04-16 15:33
Same. I only see this error when i run react-native run-ios. If i run the app from xcode in debug mode I don't see the error and can continue programming as usual. This has been my current workaround until it's fixed.

**Comment by yogevbd** [comment] 2019-04-17 12:14
This issue seems to be related to the build cache itself and not to react-native-navigation.
I managed to reproduce the issue, bootstrapped a new RN project with `RNN@2.16.0` and ran `react-native run-ios`, then upgraded to `RNN@2.17.0` and ran again `react-native run-ios`.

The solution is to remove `ios/build` folder and run `react-native run-ios`.

**Comment by Pandan** [comment] 2019-04-17 12:38
Thanks for looking into this. 
I will give it a try as soon as I have time.

**Comment by aminosman** [comment] 2019-04-17 14:13
I cleared the build cache and am still seeing this issue

**Comment by yogevbd** [comment] 2019-04-17 17:35
Can you try removing  both `ios/DerivedData` and `ios/build`?

**Comment by mromarreyes** [comment] 2019-04-17 17:50
Deleting the `ios/build` folder solved the issue for me. I did not have an `ios/DerivedData` folder. Thanks @yogevbd

**Comment by aminosman** [comment] 2019-04-18 14:02
Ok looks like `DerivedData` was the trick, that got it working for me.

**Comment by yogevbd** [comment] 2019-04-18 14:26
Awesome! closing the issue

**Closed by yogevbd** 2019-04-18 14:26 UTC
Labels: platform: iOS

**Comment by etaytch** [comment] 2019-07-11 15:06
thanks @shuzootani !
