### ISSUE TITLE
when i update bottom tab badge in  ios the app is freez 

### ISSUE THREAD

**Issue by mohamedanwer123** [wix/react-native-navigation#6531] opened 2020-09-02 12:08 UTC
Navigation.mergeOptions("NotificationsStack", {
                bottomTab:{
                badge: this.props.unreadNotificationsCount,
                badgeColor:colors.gold,
                text:allStrings.notifications,
                fontFamily:this.props.isRTL?arabicFont:englishFont
                }
});

RN v 0:63
RNN v 6.8.0

**Comment by jinshin1013** [comment] 2020-09-07 00:07
Hi @mohamedanwer123 I could not reproduce this issue on the Playground app. Would you be able to create a minimal reproduction on Github for us to have a look?

**Comment by jinshin1013** [comment] 2020-09-25 03:03
Closing for now. Feel free to comment back any time :)

**Closed by jinshin1013** 2020-09-25 03:03 UTC
Labels: user: requires reproduction

**Comment by RichardLindhout** [comment] 2020-11-04 12:51
I do have the same problem right now

**Comment by RichardLindhout** [comment] 2020-11-04 12:53
It's because you can't send a number you have to send in a string on iOS!

**Comment by RichardLindhout** [comment] 2020-11-04 12:54
``` 

mergeOptions({
      bottomTab: {
        badge: cartAmount === 0 ? '' : `${cartAmount}`,
      },
    })

```
