### ISSUE TITLE
[ENHANCEMENT] Support custom components for Bottom Tabs

### ISSUE THREAD

**Issue by mrousavy** [wix/react-native-navigation#6522] opened 2020-08-31 11:44 UTC
### Problem

Currently the BottomTabs TabBar can only render Icons and Text (labels) which are rendered using the native TabBar implementations. If I wanted to implement something like this:

<img src="https://user-images.githubusercontent.com/15199031/91716039-26adda80-eb8f-11ea-91a2-bf646e2122b8.png" width="70%">

or this:

<img src="https://user-images.githubusercontent.com/15199031/91716109-46450300-eb8f-11ea-9274-17127ba9aefe.jpg" width="70%">

It would simply not be possible. A very wacky workaround would be to create an overlay the same time the bottom tabs are rendered, which is exactly positioned over the bottom Tabs. This has many issues though:

* Requires a lot of code (especially to manage appearance/disappearance in root replacements, bottomTabs visibility changes, e.g.)
* Doesn't work with Modals (goes above)
* Has issues with transparency (shadows, button pressed animations such as scale, opacity, ..)
* Doesn't work with bottom tabs animations (e.g. visible -> not visible slide animation)

### Solution

A clean solution would be a `component` prop in the bottomTab API.

Example usage:

```ts
bottomTab: {
	component: () => <MyAddButton/>,
},
```
or
```ts
bottomTab: {
	component: {
		name: 'MyAddButton'
	},
},
```

**Comment by danilobuerger** [comment] 2020-09-01 11:55
I wonder if thats compatible with the motto of rnn to use native components for navigation. Maybe it would be better allowing users to override any native rnn components with their own instead of adding solutions that don't exist in the native framework.

**Comment by mrousavy** [comment] 2020-09-01 12:40
@danilobuerger Well the topBar also supports adding custom components via overlays which work pretty well with animations, I'd imagine the bottomTab to support the same. I'm not sure if stuff that overflows causes any issues tho 🤔

**Comment by nenti** [comment] 2020-09-06 21:54
I mean a good start would be to at least implement events for bottomTabShow and bottomTabsHide to enable implementing an overlay yourself. We have the same design challenge and solving it would have been much easier when these events would be available to trigger synchronised appearance and disappearance with bottom tabs of custom overlays.

**Comment by stereodenis** [comment] 2020-10-12 07:26
This is not stale

**Comment by stereodenis** [comment] 2020-12-02 15:00
This is not stale
and we all waiting for this

**Comment by danilobuerger** [comment] 2020-12-02 15:38
@stereodenis instead of waiting you could implement it and submit a PR?

**Comment by stereodenis** [comment] 2021-01-01 19:54
this is not stale

**Comment by chrise86** [comment] 2021-01-18 14:36
Duplicate of https://github.com/wix/react-native-navigation/issues/6384

**Closed** 2021-01-18 18:33 UTC
Labels: type: accepted/discussion

**Comment by cmdominguez** [comment] 2024-06-16 18:23
https://github.com/cmdominguez/react-native-custom-bottom-tabs espero que les sirva
