### ISSUE TITLE
Android: blank space when hide navigation bar 

### ISSUE THREAD

**Issue by DaveLomber** [wix/react-native-navigation#5620] opened 2019-11-01 11:12 UTC
### Issue Description

We have a task to hide/show Android navigation bar

We are using this API to hide it https://github.com/thebylito/react-native-navigation-bar-color#hidenavigationbar-android

So far it looks OK only on a root screen (we have tabs here)
But then, if we push other screen OR show as modal - we see a blank white space on the bottom, which is not filled by UI

<img width="791" alt="RNN-bar-issue" src="https://user-images.githubusercontent.com/39332586/68021103-33c91700-fca9-11e9-99e7-17371bdb5a04.png">

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61.2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): any

**Comment by edferreira** [comment] 2019-11-06 20:00
#5605

**Comment by ItsNoHax** [comment] 2019-11-08 08:41
Going to close this one as it's duplicate of #5605

**Closed by ItsNoHax** 2019-11-08 08:41 UTC

**Comment by DaveLomber** [comment] 2019-11-08 08:45
@ItsNoHax  it's not exactly this one 

That issue is with BottomTab's visibility, but my issue is with navigation bar visibility 

Hide/Show bottom tabs works great in my case, 
what I have is a blank space when hide navigation bar on Android

Please reopen

**Comment by romit07** [comment] 2019-11-17 19:44
I am facing the exact  same issue? Anyone found the solution?

**Comment by vitaliykastsiuk** [comment] 2020-01-10 15:04
@DaveLomber @romit07 did you find any fix for this?

**Comment by DaveLomber** [comment] 2020-01-10 15:28
@vitaliykastsiuk  no I did not..

**Comment by 92sajid110** [comment] 2021-06-02 15:02
any solutions yet...
