### ISSUE TITLE
[v2] BottomTabs disappear on Android after re-opening the app

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#3197] opened 2018-05-11 22:14 UTC
Sometimes the tab from TabNavigator disappears from Android. It usually happens when you close and open the app again.

The area still not clickable, but there's nothing on it. To fix it you need to install it again.

---
### Environment
* React Native Navigation version: 2.0.2275
* React Native version: 0.55.1
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device and Simulator on Debug

**Comment by gabrielvcbessa** [comment] 2018-05-16 17:45
To reproduce it you just need to install an app on an Android Device in Debug mode. Than, close your app and open again, the bottomTabs will disappear. It also happens on the playground app!!

**Comment by guyca** [comment] 2018-05-17 06:33
@gabrielvcbessa How exactly did you reproduce this in the playground app? What do you mean by "close the app"? Do you close it with the back button?

**Comment by gabrielvcbessa** [comment] 2018-05-18 17:25
@guyca You can close it with the back button and/or close it in the multitask manager (the button that isn't home or back). In the gif bellow you can see this bug on playground when I try to switch to the "Tab Based App". 

Luckily I have captured another bug that its happening, sometimes the android app gets stucked on the splash screen indefinitely.

![](https://gfycat.com/EveryThatFinnishspitz)

**Comment by gabrielvcbessa** [comment] 2018-05-25 16:59
@guyca Any updates?

**Comment by gabrielvcbessa** [comment] 2018-06-06 17:37
@guyca This issue seems to be only happening when you close the app using the back button. Do you know something that might be happening? We can help you fixing it. We are using v2.0.2275

**Comment by guyca** [comment] 2018-06-07 14:26
This is not a bug. Back button closes the app, home button minimises it.

**Closed by guyca** 2018-06-07 14:26 UTC
Labels: user: more info needed, v2

**Comment by gabrielvcbessa** [comment] 2018-06-07 14:43
Ok, but closing an app should make the BottomTabs dissapear once you open it again without finishing it on the multitask menu?
