### ISSUE TITLE
Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve project :react-native-navigation

### ISSUE THREAD

**Issue by lisichka999** [wix/react-native-navigation#6279] opened 2020-06-08 15:46 UTC
Getting this error and gradle sync failed
After updating from 4.2 to 6.7
I saw that this issue was already reported twice but the solution was to add 
"RNN.reactNativeVersion", "reactNative60" to missingDependansyStratagy.
But in the migration guide to 5.0.0 need to be remove them.

### Environment
* React Native Navigation version: 6.7.0
* React Native version: 61
* Platform: Android
* Device info : Gradle sync

**Comment by jinshin1013** [comment] 2020-06-09 00:45
@lisichka999 Hi there, adding `missingDependencyStrategy` is not required in the latest version. This is most likely due to some sort of cache/build issue which could be resolved by cleaning the project. 

Closing for now but let me know if the problem still persists and if you could provide a reproduction on Github, that will be even more awesome 🙏

**Closed by jinshin1013** 2020-06-09 00:45 UTC
