### ISSUE TITLE
BottomTabs stretch bug

### ISSUE THREAD

**Issue by Alek997** [wix/react-native-navigation#5870] opened 2020-01-23 12:48 UTC
Hi! I have a problem with bottom tabs stretching too much in portrait orientation.
This only happens on android.
When I go from the main screen from which the bottom tabs are visible to modal, change orientation and then go back to the main screen, bottom tabs are stretched over visible screen width.

Steps to reproduce:

1. From the bottom tab screen go to modal screen
2. Change orientation to landscape
3. Go back to previous bottom tab screen and change the orientation back to portrait

Screenshots of example:
![83375600_178076373295654_3462778766349041664_n (1)](https://user-images.githubusercontent.com/35713221/72986800-4acf5f00-3de9-11ea-96b8-0ca753e3b9f9.jpg)
![80560924_595590787887117_3535635743995068416_n](https://user-images.githubusercontent.com/35713221/72986816-51f66d00-3de9-11ea-9c4b-a1f6731be30b.jpg)
![82787165_194778588375872_8803529981419323392_n](https://user-images.githubusercontent.com/35713221/72986821-5458c700-3de9-11ea-86e9-c0f96419e6ed.jpg)

I am using react native navigation V4.5.3
react-native V0.61.5

**Comment by markorusic** [comment] 2020-01-23 13:16
Same problem here, with both the latest and older versions of rnn on android.

**Comment by suppressf0rce** [comment] 2020-01-23 13:20
Same issue here, can we get this fixed please?

**Comment by ItsNoHax** [comment] 2020-01-24 08:45
Seems like a duplicate of: https://github.com/wix/react-native-navigation/issues/4710

**Comment by Alek997** [comment] 2020-01-24 10:42
@ItsNoHax  Did you find any workaround for this bug?

**Comment by Alek997** [comment] 2020-02-23 12:24
not stale!

**Comment by guyca** [comment] 2020-02-23 13:49
Hey guys, closing this as it's a duplicate. Will get to #4710 asap

**Closed by guyca** 2020-02-23 13:49 UTC
