### ISSUE TITLE
Feature: Custom Push/Pop Animations

### ISSUE THREAD

**Issue by indivisable** [wix/react-native-navigation#419] opened 2016-11-08 22:10 UTC
Could anyone point me in the right direction on implementing a custom animation for push pop?

My goal is to have a nice cross fade animation when scenes are pushed/poped... hopefully this will help resolve the flicker of the screen too. I am not fully fluent in Obj-C but if anyone can point me in right direction I will give it a try using some references online such as:

http://stackoverflow.com/questions/2215672/how-to-change-the-push-and-pop-animations-in-a-navigation-based-app

**Comment by guyca** [comment] 2016-11-09 06:55
@indivisable 
a few animation types are already supported on iOS. Define
`animationType: fade' when you push/pop a screen as shown [here](https://github.com/wix/react-native-navigation/wiki/Top-Level-API#starttabbasedappparams).

That being said, this won't fix the flicker issue. The cause is that each native screen has a default white color and that native screen is visible before the react screen is. On Android we solved this by displaying the native screen only when the RN screen has rendered. I think that's we're going to stick with this approach and implement it in iOS as well.

At any case, This is something that we should get to pretty soon. I think a few developers mentioned temporary workarounds to this issue in another issue, can't seem to find it right now.

**Comment by indivisable** [comment] 2016-11-09 20:05
@guyca This animation does not effect Push/Pop method:

`this.props.navigator.push(); or this.props.navigator.pop();`

I do not believe these methods have a animationType unlike the showModal method.

**Comment by guyca** [comment] 2016-11-09 20:08
@indivisable gotcha 👍

**Comment by Crash--** [comment] 2016-11-14 17:43
+1 to have animationType on push / pop.

**Comment by grundmanise** [comment] 2017-03-09 10:25
@guyca it would be **very** cool to have an option to pass a pop/push transition types:

```
CATransition* transition = [CATransition animation];
transition.duration = 0.5;
transition.timingFunction = [CAMediaTimingFunction functionWithName:kCAMediaTimingFunctionEaseInEaseOut];
transition.type = kCATransitionFade; //kCATransitionMoveIn; //, kCATransitionPush, kCATransitionReveal, kCATransitionFade
//transition.subtype = kCATransitionFromTop; //kCATransitionFromLeft, kCATransitionFromRight, kCATransitionFromTop, kCATransitionFromBottom
[self.navigationController.view.layer addAnimation:transition forKey:nil];
[[self navigationController] popViewControllerAnimated:NO];
```

Just imagine the possibility to have tranitions [like this](https://www.w3schools.com/jquerymobile/tryit.asp?filename=tryjqmob_trans_slide) and **[this](https://youtu.be/B9sH_VxPPo4?t=31m43s)**. Of course, we should also not forget about Android... because of that we should(?) implement only transitions that are available on both iOS and Android first and later any custom one. But anyway having transitions like `from left to right` and `from right to left` would be super cool.

**Comment by grundmanise** [comment] 2017-03-09 10:26
2nd option. Maybe to make some kind of a tutorial on 'How to create a custom push/pop` transition?

**Comment by denizs** [comment] 2017-04-28 09:16
I'd also be pretty interested in a solution which enables fully customizable scene transitions, especially @grundmanise's second example (an expanding button).
Or is there already some solution

**Comment by troianoandres** [comment] 2017-05-15 01:16
+1 to have animationType on push / pop. This would be really nice.

**Comment by linnett** [comment] 2017-05-31 16:48
+1 to animationType on push and pop 👍

**Comment by rpmonteiro** [comment] 2018-04-04 15:17
👍

**Comment by bigxigua** [comment] 2018-05-21 03:11
+1

**Comment by guyca** [comment] 2018-05-21 07:56
Hey guys
Custom animations for modals (show dismiss), push, pop and startApp are implemented in v2
Example usage can be found in the [playground app](https://github.com/wix/react-native-navigation/blob/v2/playground/src/app.js#L27)

**Closed by guyca** 2018-05-21 07:56 UTC

**Comment by tastyqbit** [comment] 2018-12-24 03:39
In case someone finds this useful, been looking a long time to implement a sharedElement customTransition in Navigation.pop so here it is. It works :) 

```javascript
  pop() {
    Navigation.pop(this.props.componentId, {
      customTransition: {
        animations: [
          { type: 'sharedElement', fromId: 'artworkImage', toId: this.props.selectedArtwork.id, startDelay: 0.0, springVelocity: 0.2, duration: 0.8 }
        ],
        duration: 0.8
      }
    })
  }
```

**Comment by sebringj** [comment] 2019-02-10 16:27
I do appreciate you making this...
BUT
The support for animations seems to be lacking.
```
  static options(passProps) {
    return {
      animations: {
        push: {
          content: {
            x: {
              from: -1000, to: 0, duration: 300
            },
            y: {
              from: 0, to: 0, duration: 300
            }
          }
        },
        pop: {
          content: {
            x: {
              from: 0, to: -1000, duration: 300
            },
            y: {
              from: 0, to: 0, duration: 300
            }
          }
        }
      }
    }
  }
```
This does not work nor does the undocumented _ prefix approach work. This is a great library in terms of app memory performance but needs some loving care for the overrides. I might help just been busy.
