### ISSUE TITLE
Some problems on Android.

### ISSUE THREAD

**Issue by jaggerwang** [wix/react-native-navigation#543] opened 2016-12-07 12:37 UTC
### Issue Description

It works great on iOS, but there are some problems on Android. Source code of the project is here, https://github.com/jaggerwang/zqc-app-demo.

#### First
1. title of nav bar is not in center, seems right on Android. But it is not consistent with iOS, and most apps of Android.
1. status bar is not light, already set statusBarTextColorScheme style to 'light'.
1. color of tab bar label and icon is not right, both normal and selected. As suggested by @guyca , using appStyle works on Android. But why not using another prop for Android?
1. iOS only! The color of selected icon is not changed to the value specified by tabBarSelectedButtonColor. The icon image is generated by FontAwesome.getImageSource.

<img src="https://cloud.githubusercontent.com/assets/1255011/20967319/ce7af882-bcb9-11e6-84d3-330f25b76fab.png" width="240">
<img src="https://cloud.githubusercontent.com/assets/1255011/20967322/d7a99e9a-bcb9-11e6-9651-8d62c59bc7fd.png" width="240">

#### Second
1. when pushed a screen, the screen is not inheriting the navigator style of previous. As @guyca said, Android not supporting this way, so behavior on iOS may be changed to consist with Android.

<img src="https://cloud.githubusercontent.com/assets/1255011/20967429/69d6db66-bcba-11e6-8c16-dd8529825448.png" width="240">
<img src="https://cloud.githubusercontent.com/assets/1255011/20967437/6ea1c3f4-bcba-11e6-84c1-c25aef3ee3bc.png" width="240">

#### Third
1. left button's text is not showing, it is not a cross. As @guyca told, Android only support 4 limited buttons on left.

<img src="https://cloud.githubusercontent.com/assets/1255011/20967505/c8dfaed0-bcba-11e6-9f7d-2a5b06156bbb.png" width="240">
<img src="https://cloud.githubusercontent.com/assets/1255011/20967507/cc772dfc-bcba-11e6-86ed-e7d05b064685.png" width="240">

### Environment
* React Native Navigation version: 2.0 newest
* React Native version: 0.38.1
* Platform(s) (iOS, Android, or both?): Android, iOS is right
* Device info (Simulator/Device? OS version? Debug/Release?): Android on device, iOS on Simulator

**Comment by guyca** [comment] 2016-12-07 13:00
Hey @jaggerwang Thanks for the detailed post.

1. Android Toolbar title is aligned left (start)
2. Try setting bottomTabs colors in `AppStyle`:

```js
Navigation.startTabBasedApp({
  tabs: createTabs(),
  appStyle: {
    tabBarBackgroundColor: '#0f2362',
    tabBarButtonColor: '#ffffff',
    tabBarSelectedButtonColor: '#63d7cc'
  }
});
```
3. Android screen don't inherit styles by design. I think this behavior will change on iOS.  
4. Left button on Android has only icon and it's limited to only 4 types of icons: Menu, cancel, approve and back. I'm pretty sure this is mentioned in the docs

**Comment by jaggerwang** [comment] 2016-12-08 02:42
Thanks to @guyca , I fixed most of the problems. But there still has a few.

1. On Android, status bar is not light, already set statusBarTextColorScheme style to 'light'.
1. On iOS, the color of selected icon is not changed to the value specified by tabBarSelectedButtonColor. The icon image is generated by FontAwesome.getImageSource.

**Comment by guyca** [comment] 2016-12-08 07:16
Regarding `tabBarSelectedButtonColor`. The BottomTabs style api is in a bit of a limbo state right now. iOS still uses the [old way of styling tabs](https://github.com/wix/react-native-navigation/wiki/Styling-the-tab-bar). The styling api is still not final, some things like `tabStyle` will likely get removed and some style properties will get renamed etc.

Seems like `statusBarTextColorScheme` is an iOS only property. I think you can use [StatusBar](https://facebook.github.io/react-native/docs/statusbar.html) as a workaround. We will add proper StatusBar styling support on Android in one of the next versions

**Comment by guyca** [comment] 2016-12-09 12:44
@jaggerwang I'm closing the issue. Please reopen if you have any more questions 👍

**Closed** 2016-12-09 12:43 UTC

**Comment by mansarip** [comment] 2017-06-27 21:33
@guyca Is there any workaround to get dark text in Android using "statusBarTextColorScheme"? 

Already set "statusBarTextColorScheme" to "dark", but still the color of the text is light. Here's my style preferences :

`navigatorStyle : {
	navBarHidden : true,
	statusBarColor : '#fff',
	statusBarTextColorScheme : 'dark'
}`
