### ISSUE TITLE
A problem occurred configuring project ':react-native-navigation'.

### ISSUE THREAD

**Issue by mohamadrezach** [wix/react-native-navigation#7469] opened 2022-02-24 11:57 UTC
## 🐛 Bug Report

I Installed react native navigation V7.25.4, now when I sync project in android studio I have an error:
```
A problem occurred configuring project ':react-native-navigation'.
> It is too late to set sourceCompatibility
  It has already been read to configure this project.
  Consider either moving this call to be during evaluation,
  or using the variant API.
```
```

Cannot resolve symbol 'json'
Cannot resolve symbol 'JsonSlurper'
```

**Comment by danilobuerger** [comment] 2022-02-28 19:14
Duplicate of #7463

**Closed by danilobuerger** 2022-02-28 19:14 UTC
Labels: needs triage, triage: bug
