### ISSUE TITLE
Android app gets stuck on splash screen when permissions for the app are changed

### ISSUE THREAD

**Issue by varungupta85** [wix/react-native-navigation#3064] opened 2018-04-17 10:04 UTC
### Issue Description

Please see the attached GIF which shows the unexpected behaviour. My app requires contacts permission from the user. Whenever I disable the contacts permission for the app from the phone settings and go back to the app, the app get stuck. If you look at the GIF, you will observe that when I start the app again after disabling contacts permission, splash activity is shown and when it finishes, a new splash activity is shown. I am not sure why is a new splash activity started which I think is causing the problem. If I put the app in background and then start it again, the app gets unstuck.

I haven't overridden `clearHostOnActivityDestroy` because it creates some other issues in my app.

![splashactivitystucknew](https://user-images.githubusercontent.com/7475133/38863458-5110f356-4255-11e8-8e42-fab96753fa89.gif)

### Steps to Reproduce / Code Snippets / Screenshots

1. Request contacts permission in the app and allow it
2. Go to phone settings and disable contacts permission
3. Go back to the app and observe that the app gets stuck on the splash screen

---
### Environment
* React Native Navigation version: 1.1.409
* React Native version: 0.52.4
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by guyca** [comment] 2018-04-23 06:36
Hey @varungupta85 I'm not able to reproduce this issue in the Wix app when returning false from `clearHostOnActivityDestroy`.
As this is also not reproducing in v2 (we have e2e for this exact scenario), I'm opting to close the issue.
You should not clear host when activity is destroyed, I don't know what other issues your facing when not clearing host but perhaps this is a good time to address them as host isn't cleared in v2 as well.

**Closed by guyca** 2018-04-23 06:36 UTC

**Comment by trieulh-ict** [comment] 2018-06-20 06:30
I also got this problem when turning off camera permission, then come back to the app. This issue only happens when users turn off any permissions, it runs smoothly when they turn on.

**Comment by HeWhoRemains88** [comment] 2024-09-30 18:47
> I also got this problem when turning off camera permission, then come back to the app. This issue only happens when users turn off any permissions, it runs smoothly when they turn on.

Hi @trieulh-ict did you ever find a solution to this problem?  I'm seeing the same thing as of late.
