### ISSUE TITLE
[v6] [iOS] registerBottomTabSelectedListener returns (0, 0) indexes

### ISSUE THREAD

**Issue by ddcrobert** [wix/react-native-navigation#6254] opened 2020-05-28 18:06 UTC
### Issue Description

The registerBottomTabSelectedListener is not returning the correct indexes. Both selectedTabIndex and unselectedTabIndex are 0 on iOS. On the other hand, it's working perfectly on Android.

bottomsTabs are set up using Navigation.setRoot(...).

I assume my implementation is stable : the tabs are there since v2, the listener since v2 or v3.

### Steps to Reproduce / Code Snippets / Screenshots

```js

const bottomTabEventListener = Navigation.events().registerBottomTabSelectedListener(({ selectedTabIndex, unselectedTabIndex }) => {
  console.log("registerBottomTabSelectedListener:");
  console.log(selectedTabIndex);
  console.log(unselectedTabIndex);
}); 
/*
registerBottomTabSelectedListener:
0
0
*/

```

Tap from any tab to any tab, it will always be selectedTabIndex = 0, unselectedTabIndex = 0.

---
### Environment
* React Native Navigation version: 6.7.1
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Device (13.5), Simulator (13.5), Debug

**Comment by mlangebeeke** [comment] 2020-06-01 19:41
Had the same issue, then rolled back to version 6.3.0 and it's working again.. no more 0,0

**Comment by jinshin1013** [comment] 2020-06-01 22:28
@yogevbd I can reproduce this in the latest Playground app. 

It seems like `tabBarController.selectedIndex` always returns 0 causing `_currentTabIndex` to never change either.

```objective-c
// RNNBottomTabsController.m
- (void)tabBarController:(UITabBarController *)tabBarController didSelectViewController:(UIViewController *)viewController {
  [self.eventEmitter sendBottomTabSelected:@(tabBarController.selectedIndex) unselected:@(_currentTabIndex)];
  _currentTabIndex = tabBarController.selectedIndex;
}
```

**Comment by mlangebeeke** [comment] 2020-06-02 06:50
Don't know if it's related, but I have the same issue that componentDidAppear() doesn't get called, also only on iOS. It does work when debugger attached, so might have to do with the JS engine that is used on iOS?
(on v6.5, and also after downgrading to v6.3)

**Comment by damii** [comment] 2020-06-11 08:26
I had same issue with React Native Navigation version: 6.7.2

it will always be selectedTabIndex = 0, unselectedTabIndex = 0.

**Comment by alex-phillips** [comment] 2020-06-11 15:40
Same issue. This is a breaking change as far as our app goes. Is there a possible ETA on a fix?

**Comment by micheleb** [comment] 2020-06-11 16:36
Same here. To fix it, I changed `RNNBottomTabsController.shouldSelectViewController()` so that it looks like this:

```obj-c
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController
{
    NSUInteger _index = [tabBarController.viewControllers indexOfObject:viewController];
    // add the following line
    tabBarController.selectedIndex = _index;
    [self.eventEmitter sendBottomTabPressed:@(_index)];
    
    if([[viewController resolveOptions].bottomTab.selectTabOnPress getWithDefaultValue:YES]){
        return YES;
    }

    return NO;
}
```

I tracked this back to this pull request: https://github.com/wix/react-native-navigation/pull/6230

**Comment by bneigher** [comment] 2020-06-15 22:10
This has broken for me updating from 6.4 to 6.7

**Comment by ItsNoHax** [comment] 2020-06-16 09:45
Hi all, we are aware that this is currently broken and it will be dealt with in the next release!

**Comment by ItsNoHax** [comment] 2020-06-16 11:05
@bneigher , @micheleb , @alex-phillips , @damii could you guys check if this is fixed in 6.7.4?

**Comment by bneigher** [comment] 2020-06-16 21:29
@ItsNoHax yes this version seems to have fixed the issue.  Thanks for hopping on it!

**Closed** 2020-06-17 03:51 UTC
Labels: platform: iOS, type: accepted/bug, 📌 pinned

**Comment by peterh32** [comment] 2020-06-17 19:47
It seems to me that `selectedTabIndex` is correct but that `unselectedTabIndex` is just being set equal to `selectedTabIndex`
