### ISSUE TITLE
[V2] Cannot use react-native-auth0, RNN is intercepting callbacks

### ISSUE THREAD

**Issue by reinvanimschoot** [wix/react-native-navigation#3716] opened 2018-08-08 15:00 UTC
On Android, when using the Auth0 library, all callbacks used when authenticating via WebAuth are intercepted by React-Native-Navigation and are never passed to Auth0. 

I guess this is a bit the same as the problems that used to arise when using Facebook Login from the FBSDK.

Is there anything I can add in MainActivity that would allow Auth0 to receive the callbacks?

The Auth0 react-native-docs can be found here: https://github.com/auth0/react-native-auth0

**Comment by lean** [comment] 2018-08-08 15:19
Same issue here. The error response:  `error_description: 'User cancelled the Auth`

**Comment by reinvanimschoot** [comment] 2018-08-20 07:13
Is there any workaround to this? Or any idea of whether or not this will work eventually?

**Comment by nenti** [comment] 2018-09-12 12:47
Did anyone find a solution to assist handling this issue?

**Comment by nenti** [comment] 2018-09-13 07:58
I got it to work on both iOS and Android in the latest version RNN@^2.0.2518 @reinvanimschoot please check if upgrading works for you and close if confirmed.

**Comment by kevinranks** [comment] 2018-09-18 13:20
@nenti Currently not working on RNN 2.0.2538 & RNAuth0 1.3.0 ... anyone know how to fix this?

**Comment by nenti** [comment] 2018-09-18 13:45
Make sure you have launchMode set to single task.
```
        <activity
            android:name=".MainActivity"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data
                        android:host="XXX.XX.auth0.com"
                        android:pathPrefix="/android/${applicationId}/callback"
                        android:scheme="${applicationId}" />
            </intent-filter>
        </activity>
```

**Comment by kevinranks** [comment] 2018-09-18 14:01
@nenti  Can confirm, working now. Mistakenly had `android:launchMode="singleTask"` under `<application>` and not `<activity>. My mistake, thanks!

**Comment by guyca** [comment] 2018-09-18 16:11
Closing as this seems to be resolved. Thanks a lot @nenti and @kevinranks for confirming.

**Closed by guyca** 2018-09-18 16:11 UTC
Labels: platform: Android, v2
