### ISSUE TITLE
immediately fails on 'npm install'

### ISSUE THREAD

**Issue by hqtsky** [wix/react-native-navigation#5401] opened 2019-08-21 17:36 UTC
### Issue Description
Followed instructions from this doc: https://wix.github.io/react-native-navigation/#/docs/showcases

npm command fails with the following output:
```

galaga:react-native-navigation hqtsky$ npm install

> dtrace-provider@0.8.8 install /Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

  ACTION binding_gyp_ndtp_target_build_ndtp .
/bin/sh: Recent: command not found
  TOUCH Release/obj.target/ndtp.stamp

> detox@12.11.3 postinstall /Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox
> node scripts/postinstall.js

+ xcodebuild -version
+++ dirname '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/scripts/build_framework.ios.sh'
++ dirname '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/scripts'
+ detoxRootPath='/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox'
++ node -p 'require('\''/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/package.json'\'').version'
+ detoxVersion=12.11.3
++ echo 12.11.3
++ xcodebuild -version
++ shasum
++ awk '{print $1}'
+ sha1=9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da
+ detoxFrameworkDirPath=/Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da
+ detoxFrameworkPath=/Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da/Detox.framework
+ main
+ '[' -d /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da ']'
+ '[' '!' -d /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da/Detox.framework ']'
+ echo '/Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da and trying to rebuild.'
/Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da was found, but could not find Detox.framework inside it. This means that the Detox framework build process was interrupted.
         deleting /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da and trying to rebuild.
+ rm -rf /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da
+ prepareAndBuildFramework
+ '[' -d '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios' ']'
+ detoxSourcePath='/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ extractSources '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ detoxSourcePath='/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ echo 'Extracting Detox sources...'
Extracting Detox sources...
+ mkdir -p '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ tar -xjf '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/Detox-ios-src.tbz' -C '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ buildFramework '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ detoxSourcePath='/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src'
+ echo 'Building Detox.framework from /Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src...'
Building Detox.framework from /Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src...
+ mkdir -p /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da
+ '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/scripts/build_universal_framework.sh' '/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/ios_src/Detox.xcodeproj' /Users/hqtsky/Library/Detox/ios/9b6034ad29b8c8eb063a9dbfeac9c0fab80de1da
child_process.js:650
    throw err;
    ^

Error: Command failed: /Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/scripts/build_framework.ios.sh
    at checkExecSyncError (child_process.js:629:11)
    at Object.execFileSync (child_process.js:647:13)
    at Object.<anonymous> (/Users/hqtsky/prj/0 Recent Workspaces/prj-narrate/src-sandbox/reactnative/wix-nav/react-native-navigation/node_modules/detox/scripts/postinstall.js:2:27)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
npm WARN react-native-text-size@2.1.1 requires a peer of react-native@>=0.52.0 <0.57.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! detox@12.11.3 postinstall: `node scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the detox@12.11.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hqtsky/.npm/_logs/2019-08-21T17_27_38_019Z-debug.log
galaga:react-native-navigation hqtsky$ npm --version
6.10.3


```

### Steps to Reproduce / Code Snippets / Screenshots
1) Clone this repo: git clone https://github.com/wix/react-native-navigation
2) cd react-native-navigation
3) npm install  //boom fail

---
### Environment
* React Native Navigation version: 
* React Native version: 0.6.x 
* Platform(s) (iOS, Android, or both?): neither failed on npm install
* Device info (Simulator/Device? OS version? Debug/Release?): didn't get that far. I'm on a mac

**Comment by ItsNoHax** [comment] 2019-08-25 12:02
Closing issue as I can't reproduce. Most likely related to your specific node/npm version.

**Closed by ItsNoHax** 2019-08-25 12:02 UTC
