### ISSUE TITLE
[V2] How to set root component for multiple screens (like Provider for Context or Redux)

### ISSUE THREAD

**Issue by pie6k** [wix/react-native-navigation#3549] opened 2018-07-13 11:37 UTC
I need all screens to be wrapped inside the same instance of Provider component. 

In version 1 of react-native-navigation there was 3rd parameter of `registerComponent` that was allowing that.

Is it possible in v2?

Example:

In case like this:
https://reactjs.org/docs/context.html#updating-context-from-a-nested-component

Context value is based on root component state. This requires, however, to have only single instance of this root component. When I'm registering component inside `react-native-navigation` I need to pass this root component everytime (so it's not the same instance), so it have different internal state, so it's not possible to sync context between multiple screens.

---
### Environment
* React Native Navigation version: 2.0.2410
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by abdullah-sr** [comment] 2018-07-13 19:55
You probably want to take a look at this thread https://github.com/wix/react-native-navigation/issues/3549

Here's my solution. i created a helper function:
 ```
import React from 'react';
import { Provider } from 'react-redux';

const wrapWithProvider = component, store) => (
    () => React.createElement(
        Provider,
        { store },
        React.createElement(component, null)
    )
);
```
and then when you register your component 
```
Navigation.registerComponent('HOME', () => wrapWithProvider(Home, store));
```

**Comment by MaxInMoon** [comment] 2018-07-22 09:58
@abdullah-sr app crashes at first link with your method. Are you sure of it?

**Comment by sturmenta** [comment] 2018-07-24 21:11
I solved it in this way:
```javascript
const wrapWithToastProvider = Comp => props => (
	<ToastProvider>
		<Comp {...props} />
	</ToastProvider>
);

Navigation.registerComponent('myschool.login', () => wrapWithToastProvider(Login), store, ReduxProvider);
```

**Comment by abdullah-sr** [comment] 2018-08-09 15:35
@pie6k @MaxInMoon Redux support was introduced with this PR https://github.com/wix/react-native-navigation/pull/3675
Now, you can use `registerComponentWithRedux` just as you would with v1.
This issue can probably be closed closed now.

**Comment by LordParsley** [comment] 2018-09-28 12:50
@brunolemos 's suggestion would be really handy for things like the `native-base` `StyleProvider`: https://docs.nativebase.io/Customize.html#theaming-nb-headref

I would normally wrap the whole app:

```
<StyleProvider style={getTheme(variables)}>
	<Provider store={store}>
		{app}
	</Provider>
</StyleProvider>
```

And @sturmenta 's workaround is good but masks any `static options()` in the component which I find handy for setting the `topBar` on a screen-by-screen basis.

**Comment by adrianolsk** [comment] 2018-10-03 02:03
Like @LordParsley said, when using native base we want to set the theme for the whole app, isn't bad doing it for every component?

**Comment by SMJ93** [comment] 2018-10-06 20:14
Has anybody found a solution to this? 

This[ singleton solution on StackOverflow](https://stackoverflow.com/questions/51896173/react-native-navigation-context-api) is the closest thing I could find, but feels very hacky.

Feels like a major flaw in `react-native-navigation v2` if we can't use the context api as intended 😞

**Comment by guyca** [comment] 2018-12-16 08:56
Hey guys, we've improved supports for this use case. When registering components you can wrap them with providers, additionally you'll need to pass a third argument which is a generator function which returns the actual component.

### Context API
```jsx
Navigation.registerComponent('navigation.playground.ContextScreen', () => (props) => (
  <TitleContext.Provider value={'Title from Provider'}>
    <ContextScreen {...props} />
  </TitleContext.Provider>
), () => ContextScreen);
```

### Redux
```jsx
Navigation.registerComponent('navigation.playground.ReduxScreen', () => (props) => (
  <Provider store={reduxStore}>
    <ReduxScreen {...props} />
  </Provider>
), () => ReduxScreen);
```

With this change, `Navigation.registerComponentWithRedux` is now deprecated and will be removed in the future.
I'm closing the issue but suggestions for improvements and feedback are more then welcome.

**Closed by guyca** 2018-12-16 08:56 UTC
Labels: type: accepted/enhancement, 📌 pinned

**Comment by capozzid** [comment] 2019-03-20 16:45
@guyca thanks for the tip but I still have the same problem of two instances using `Navigation.registerComponent('navigation.playground.ContextScreen', () => (props) => (
  <TitleContext.Provider value={'Title from Provider'}>
    <ContextScreen {...props} />
  </TitleContext.Provider>
), () => ContextScreen);` the way you provided it with two different screen.

**Comment by boiy** [comment] 2019-03-24 04:59
I know this has been closed, but i think you guys should be more elaborate on this... currently learning about this and i found out that `Navigation.registerComponentWithRedux` is still working, how exactly am i supposed to apply whats below to multiscreens... what components will be in <ReduxScreen /> and ReduxScreen, for someone new to react native, i will ask please you should break it down so we get it once... Thank you..
```
Navigation.registerComponent('navigation.playground.ReduxScreen', () => (props) => (
  <Provider store={reduxStore}>
    <ReduxScreen {...props} />
  </Provider>
), () => ReduxScreen);
```

**Comment by bogdan-marian** [comment] 2019-04-28 15:48
@boiy You definitely summarized in one phrase all my frustrations. I'm just learning react and I try for about 2 days now to create a new application where I connect redux and AsyncStorage to my simple app that has a buttonTab navigator and allso I plan to navigate directly between different screens. I guess my simple app is not simple. Can someone point me to a complete up to date example?

**Comment by meinto** [comment] 2019-05-27 22:12
Switching from context api to [mobx](https://github.com/mobxjs/mobx) solves all my problems. To register my components and inject the mobx stores i wrote a little helper:

```js
const registerComponentWithStores = (componentID: string, Component: any) => {
  Navigation.registerComponent(componentID, () => (props: Object) => (
    <Component
      { ...props }
      mobxStore1={mobxStore1}
      mobxStore2={mobxStore2}
    />
  ), () => Component)
}
```

The stores are now available in the props of the registered component: `props.mobxStore1`, `props.mobxStore2`. All changes i perform via actions to mutate values in the stores are automatically observed by all other registered screens.

**Comment by bang88** [comment] 2019-07-04 07:25
Still don't know how to setup a `mobx` provider and other provider together (eg. `Intl Provider.` ThemeProvider)

How to register a root component with these providers and avoid register them individual.

**Comment by pie6k** [comment] 2019-11-04 11:41
@guyca I'm not sure if I misunderstood something, but as far as I can see in your code, still - every registered component will have different provider **'instance'.**

Let's say we have context with some random number.

```ts
// each screen will have different 'random' values. I'd like all of them to be wrapped inside the same instance of the provider with the same value across all screens.
Navigation.registerComponent('navigation.playground.ContextScreen', () => (props) => (
  <RandomContext.Provider value={Math.random()}>
    <ContextScreen {...props} />
  </RandomContext.Provider>
), () => ContextScreen);
```

There are of course ways to synchronize those context values, but the ultimate goal is to have everything wrapped inside the same root providers. And this seems to still be unresolvable as far as I know

**Comment by pie6k** [comment] 2019-11-16 13:17
I've investigated it a bit more, and it's not possible, as far as I've tried to create a single provider for every screen, which is quite an issue for me.

Imagine a simple case like this:

```
export function Provider({children}) {
  // let's say we have provider that counts how many times app went to background
  const [timesAppWentToBackground, setTimesAppWentToBackground] = useState(0);

  // every time it happens, we modify inner state of provider
  useAppGoesToBackground(() => {
    setTimesAppWentToBackground(count => count + 1);
  });

  // in real life, we'd create some context for it etc.
  return <>{children}</>
}
```

It works well if we have only one screen. However, for every new screen, the brand new provider is created with a fresh state of `0` in this case.

This is the simple case and I could keep such count somewhere to be reused later like

```tsx
let cachedCount = 0;

export function Provider({children}) {
  // let's say we have provider that counts how many times app went to background
  const [timesAppWentToBackground, setTimesAppWentToBackground] = useState(cachedCount);

  useEffect(() => {
    cachedCount = timesAppWentToBackground 
  }, [timesAppWentToBackground]);
  
  // every time it happens, we modify inner state of provider
  useAppGoesToBackground(() => {
    setTimesAppWentToBackground(count => count + 1);
  });

  // in real life, we'd create some context for it etc.
  return <>{children}</>
}
```

And this would work. Every new screen would get an 'actual' count. However, in many cases, it's not possible to pass a 'previous state' in such a simple way, especially if it includes some callbacks, etc.

Also, in some cases, the provider is executing some network fetching, etc. In such a case, every screen cause another request, even tho it's not needed.

I consider it serious limitation of react-native navigation.

**Comment by yemi** [comment] 2019-12-02 17:58
@pie6k did you find any solution to this? I found that using redux works in that it keeps the state consistent across each and every screen, however, my plan was not to use redux, but if i have to, i might use it with easy peasy for example

**Comment by pie6k** [comment] 2019-12-03 00:30
@yemi I didn't find any solution for this.

Redux is specific as even if you have multiple providers, you still have a single store, so providers are in sync.

**Comment by RichardLindhout** [comment] 2021-05-05 21:44
I use the following now: 
```
import * as React from 'react';

let subscribed = false;
export default function OnlyRenderOnce({ children }: { children: any }) {
  const [loadChildren, setLoadChildren] = React.useState<boolean>(false);
  React.useEffect(() => {
    if (!subscribed) {
      subscribed = true;
      setLoadChildren(true);
      return () => {
        subscribed = false;
      };
    }
  }, []);
  return loadChildren ? children : null;
}

```

E.g
```tsx

Navigation.registerComponent('navigation.playground.ContextScreen', () => (props) => (
  <RandomContext.Provider value={Math.random()}>
    <ContextScreen {...props} />
      <OnlyRenderOnce>
           <Subscriber />
     </OnlyRenderOnce>
  </RandomContext.Provider>
), () => ContextScreen);
```

**Comment by xgenem** [comment] 2022-01-28 04:04
I wonder what happened to this issue? I personally like this project but without that support makes it difficult to use.

**Comment by xgenem** [comment] 2022-01-28 04:08
So you have to do it on every single component https://wix.github.io/react-native-navigation/api/component/

**Comment by RamanDEEP225** [comment] 2023-04-28 05:40
@xgenem, have you made the above changes for every single component?
    Navigation.registerComponent(Constants.Screens.INITIAL_PAGE, () => (props) => (<Provider store={Store}/>), () => InitialScreen);

**Comment by xgenem** [comment] 2023-04-28 11:43
> @xgenem, have you made the above changes for every single component? Navigation.registerComponent(Constants.Screens.INITIAL_PAGE, () => (props) => (), () => InitialScreen);

Yes. In my case I am using NativeBase so...

I created my own wrapper
```js
// filename wrapper.tsx
// Modify this to wrap component with other providers
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const wrap = (Component: ComponentType<any>) => (props: any) =>
  (
    <GestureHandlerRootView style={{flex: 1}}>
      <NativeBaseProvider theme={theme}>
        <Component {...props} />
      </NativeBaseProvider>
    </GestureHandlerRootView>
  )
```

Also another helper function
```js
// filename register-scren.tsx
import {ComponentType} from 'react'
import {Navigation} from 'react-native-navigation'
import {wrap} from './wrapper'

// Custom register component
export const register = (
  screenName: string | number,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Component: ComponentType<any>,
  wrapped = true // Set to false in-case there's a need to
) =>
  Navigation.registerComponent(
    screenName,
    wrapped ? () => wrap(Component) : () => Component,
    wrapped ? () => Component : undefined
  )
```

and use it like
```js
import register from './register-screens'

function registerScreens() {
  register(Screens.Splash, Splash)
}
```
