### ISSUE TITLE
Bottom tabs are broken!

### ISSUE THREAD

**Issue by JohnnyDevX** [wix/react-native-navigation#4726] opened 2019-02-13 02:51 UTC
Side navigation worked fine but when we add bottomTabs, the app crashes very very early on startup.
This is new issue that I'm experiencing with RN 0.58 but people are having problems with it also on 57.8

**Comment by kyle-ssg** [comment] 2019-02-13 11:52
@JohnnyDevX Is this by any chance on Android, if so are you setting an icon for the tabs?

**Comment by kyle-ssg** [comment] 2019-02-13 15:17
Duplicate of https://github.com/wix/react-native-navigation/issues/4724

**Closed** 2019-02-13 17:24 UTC
