### ISSUE TITLE
Sidemenu keeps openning on android

### ISSUE THREAD

**Issue by suupham2506** [wix/react-native-navigation#4661] opened 2019-01-30 10:30 UTC
### Issue Description

I pressed on OPEN SIDEMENU button, then I closed it. I switch to tab Flatlist, when I switch back to SideMenu tab, the sidemenu kept openning.

This is playground example project.

![screenshot_1548844077](https://user-images.githubusercontent.com/28852565/51975290-63e25000-24b4-11e9-9a24-84077a7f864f.png)

### Steps to Reproduce / Code Snippets / Screenshots
![screenshot_1548843852](https://user-images.githubusercontent.com/28852565/51975260-55943400-24b4-11e9-921a-71203b27a8df.png)

---
### Environment
* React Native Navigation version: FILL THIS OUT
* React Native version: FILL THIS OUT
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by retyui** [comment] 2019-03-01 20:11
Up

**Comment by guyca** [comment] 2019-04-01 09:28
@retyui Is this issue still reproducing for you? I think it's fixed by https://github.com/wix/react-native-navigation/commit/43f05ee01574c18d216acfb510be4b5e38165e4d

**Comment by retyui** [comment] 2019-04-01 09:46
@guyca 
I could not reproduce the problems, RN 2.16

**Closed** 2019-04-01 11:52 UTC
