### ISSUE TITLE
testID not being applied correctly

### ISSUE THREAD

**Issue by calumgould** [wix/react-native-navigation#6731] opened 2020-11-02 09:57 UTC
Quoting my previous follow up here, as the ticket was closed. This still remains an issue for me.

Hi @mateioprea, I appreciate you taking the time to look into this further. I have upgraded to 7.2.0 and booted up the Appium inspector to get a better look at what is going on.

I've now identified a consistent behaviour for how testIDs are being assigned to the back button. The testID passed to `setDefaultOptions` above has no effect, and the testID that is being read by Appium can be one of two things:

### Outcome 1:
- TestID is whatever the name of the title prop is from the screen that it would navigate *back* to, e.g.

Options passed to previous screen with topBar title 'Wallet':

```js
{
      topBar: {
        title: {
          text: 'Wallet'
        },
        visible: false,
        height:  0
      },

      bottomTab: {
        text:              'WALLET',
        icon:              require('../../../assets/images/walletsUnactive.png'),
        selectedIcon:      require('../../../assets/images/wallets.png'),
        selectedIconColor: (Platform.OS === 'android') ? Colors.accent : undefined,
        testID:            'navigation-wallet'
      }
}
```

Now pressing on an item in this screen, brings up the backButton in the next component. This is what the Appium inspector shows for this: (notice the correct assignment of the bottom navigation)

<img width="1131" alt="Screenshot 2020-10-27 at 10 33 35" src="https://user-images.githubusercontent.com/56885619/97291393-c317f480-1841-11eb-9f99-32df4d8f95fe.png">

### Outcome 2:
- TestID is set to default value of 'Back' when no title prop was provided in the previous screen. e.g.

Options passed to previous screen without a title prop:

```js
{
      topBar: {
        visible: false,
        noBorder:  true,
        elevation: 0
      },

      bottomTab: {
        text:              'SETTINGS',
        icon:              require('../../../assets/images/settingsUnactive.png'),
        selectedIcon:      require('../../../assets/images/settings.png'),
        selectedIconColor: (Platform.OS === 'android') ? Colors.accent : undefined,
        testID:            'navigation-settings'
      }
}
```

Following the same steps as above, the Appium inspector now shows:

<img width="1130" alt="Screenshot 2020-10-27 at 10 50 45" src="https://user-images.githubusercontent.com/56885619/97291846-59e4b100-1842-11eb-9e27-a597c2c26f82.png">

As you can see here, the testID provided to backButton isn't being applied at any stage, even passing a testID directly to backButton options in the component has no effect.

The testIDs for the bottom nav are applied correctly and recognised by the inspector.

Running the previous test, replacing the id selector with whatever testID was automatically assigned results in passing tests:

```js
  it('should be able to navigate back', async () => {
    const back = await $('~Wallet')
    await back.waitForDisplayed({ timeout: 5000 })
    await back.click()
    const screen = await $('wallet-screen')
    const visible = await screen.waitForDisplayed({ timeout: 5000 })
    expect(visible).toEqual(true)
  })
```

However, this obviously isn't an ideal solution and one would expect the testID to be consistent across all screens.

_Originally posted by @calumgould in https://github.com/wix/react-native-navigation/issues/6669#issuecomment-717162871_

**Comment by danilobuerger** [comment] 2020-11-02 16:48
Duplicate of #6669

**Closed by danilobuerger** 2020-11-02 16:48 UTC
