### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by a289459798** [wix/react-native-navigation#1406] opened 2017-06-23 06:19 UTC
### Issue Description

Open the app sometimes white screen

---
### Environment
* React Native Navigation version: 1.1.112
* React Native version: 0.43
* Platform(s) (iOS, Android, or both?): IOS

**Comment by Zcgong** [comment] 2017-07-11 03:55
I have the same problem, when I commented out  RCCTabBarController.m line 26 -> 28, solved this.
```
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController {
  id queue = [[RCCManager sharedInstance].getBridge uiManager].methodQueue;
//  dispatch_async(queue, ^{
//    [[[RCCManager sharedInstance].getBridge uiManager] configureNextLayoutAnimation:nil withCallback:^(NSArray* arr){} errorCallback:^(NSArray* arr){}];
//  });
  
  if (tabBarController.selectedIndex != [tabBarController.viewControllers indexOfObject:viewController]) {
    NSDictionary *body = @{
                           @"selectedTabIndex": @([tabBarController.viewControllers indexOfObject:viewController]),
                           @"unselectedTabIndex": @(tabBarController.selectedIndex)
                           };
    [RCCTabBarController sendScreenTabChangedEvent:viewController body:body];
    
    [[[RCCManager sharedInstance] getBridge].eventDispatcher sendAppEventWithName:@"bottomTabSelected" body:body];
  } else {
    [RCCTabBarController sendScreenTabPressedEvent:viewController body:nil];
  }
  
  
  
  return YES;
}
```

**Comment by a289459798** [comment] 2017-07-11 03:58
@Zcgong  thanks

**Comment by a289459798** [comment] 2017-07-11 04:00
but i don't use tabbar.

`Navigation.startSingleScreenApp`

**Comment by a289459798** [comment] 2017-07-17 07:35
@guyca

**Comment by guyca** [comment] 2017-07-17 07:47
Usually this happens when there's an exception in JS before `startSingleScreenApp` was called.
Since there's not much I can do the resolve this, I'm closing the issue. Will reopen if you upload an example project where this issue reproduces.

**Closed by guyca** 2017-07-17 07:47 UTC

**Comment by a289459798** [comment] 2017-07-21 06:22
// index.ios.js

`import Root from './Pages/Root';`

// Root.js

`
import React, {Component} from 'react';
import {
    View,
    Platform
} from 'react-native';

import {createStore, applyMiddleware, combineReducers} from "redux";
import {Provider} from "react-redux";
import thunk from "redux-thunk";
import * as reducers from "./redux/Reducer";

import {registerScreens} from './Router';
import {Navigation} from 'react-native-navigation';
import {navStyle} from './Views/config';

const createStoreWithMiddleware = applyMiddleware(thunk)(createStore);
const reducer = combineReducers(reducers);
const store = createStoreWithMiddleware(reducer);

registerScreens(store, Provider);

Navigation.startSingleScreenApp({
    screen: {
        screen: 'app',
        title: '爱宠采购',
        navigatorStyle: {
            ...navStyle
        }
    },
    drawer: {
        left: {
            screen: 'left'
        },
        disableOpenGesture: true
    },
    passProps: {},
    animationType: 'none'
});
`

White screen is not necessarily present, usually in the application to the background, from time to time to re-open may occur, kill the process to normal

**Comment by masterpetit** [comment] 2017-07-24 09:43
Related to: https://github.com/wix/react-native-navigation/issues/1047 ?

**Comment by a289459798** [comment] 2017-07-25 02:20
@masterpetit  same issue?

**Comment by ofirdagan** [comment] 2018-01-18 09:13
The same happened for me. The problem was an error was thrown inside the `Navigation.startTabBasedApp` or `Navigation.startSingleScrrenApp` and it was swollen so I didn't know it ever happened. 
I fixed it in this PR:

https://github.com/wix/react-native-navigation/pull/2556

**Comment by narek11** [comment] 2018-03-18 09:01
fresh react native project + install of this module  = white screen

**Comment by ofirdagan** [comment] 2018-03-21 10:26
@narek11 - did u check the console.log?
if u don't see anything I would continue with searching where the exception occur by adding break points in your code and see where it stops.

**Comment by narek11** [comment] 2018-03-21 13:02
@ofirdagan cant enter dev menu too... so cant enable it to view

**Comment by ofirdagan** [comment] 2018-03-21 15:24
@narek11 - I would check the xcode / android studio logs

**Comment by ppozniak** [comment] 2018-04-06 08:36
Maybe this will help someone: try to delete app's cache/data if on Android.
