### ISSUE TITLE
[V7] White flash between iOS Launch Screen and RN screen

### ISSUE THREAD

**Issue by alpha0010** [wix/react-native-navigation#6534] opened 2020-09-04 14:04 UTC
### Issue Description

There is a white flash between iOS Launch Screen and the first loaded javascript screen.  Same issue as #5432.

### Steps to Reproduce / Code Snippets / Screenshots

Using `waitForRender` does not seem to help.
```js
Navigation.setDefaultOptions({
  animations: {
    setRoot: {
      waitForRender: true,
    },
  },
});
```

---
### Environment
* React Native Navigation version: 7.0.0-alpha.1
* React Native version: 0.63.2
* Platform(s) (iOS, Android, or both?): iOS (Android works fine event *without* `waitForRender`)
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone 11 (13.7) simulator, debug

**Comment by mrousavy** [comment] 2020-09-05 09:34
Experiencing the same issue. I think the `animations: { setRoot }` property doesn't change anything...

**Comment by danilobuerger** [comment] 2020-09-11 08:38
Could you please try with the v7 release version? There was a change on reusing the `UIWindow` if already created. This could potentially have an impact here.

**Comment by alpha0010** [comment] 2020-09-11 12:54
Updated; the white flash still exists for me.

**Comment by alpha0010** [comment] 2020-09-30 15:13
Any updates?  Do you require more information?

**Comment by guyca** [comment] 2020-09-30 16:58
Hey @alpha0010, this will be really had to debug without a reproduction. Could you please fork the repo and reproduce in the playground app?

**Comment by alpha0010** [comment] 2020-09-30 21:34
Here is a reproduction: https://github.com/alpha0010/react-native-navigation/tree/issue-6534

**Comment by guyca** [comment] 2020-10-01 07:14
@alpha0010 What color is your splash screen and what's the background color of the first visible screen in your root?

**Comment by alpha0010** [comment] 2020-10-01 12:53
In my actual app, I use `#002350` for the splash screen, background color:
```ts
HomeScreen.options = function (passProps: Props): Options {
  return {
    layout: {
      backgroundColor: '#002350',
    },
    sideMenu: {left: {enabled: false}, right: {enabled: false}},
    // ...
```
and initial view:
```tsx
<View style={{ backgroundColor: '#002350', height: '100%', width: '100%' }} />
```
(For the reproduction, I used `#96010F`.)

**Comment by guyca** [comment] 2020-10-18 14:28
@alpha0010 ,the reproduction you submitted doesn't contain `waitForRender: true`. Adding waitForRender to the setRoot animation works as expected.

```js
Navigation.setDefaultOptions({
    animations: {
      setRoot: {
        waitForRender: true
      }
    }
});
```

I'm keeping the issue open for now as I'm waiting for your response.

**Comment by alpha0010** [comment] 2020-10-19 17:05
Did I apply this as intended?
```diff
diff --git a/playground/src/commons/Options.ts b/playground/src/commons/Options.ts
index 3c1c5e5bf..6a8c47f36 100644
--- a/playground/src/commons/Options.ts
+++ b/playground/src/commons/Options.ts
@@ -27,6 +27,9 @@ const setDefaultOptions = () =>
     },
     animations: {
       ...(useSlideAnimation ? slideAnimations : useCustomAnimations ? customAnimations : {}),
+      setRoot: {
+        waitForRender: true,
+      },
     },
     modalPresentationStyle: OptionsModalPresentationStyle.fullScreen,
   });
```

![Screen-Recording-2020-10-19-at-1](https://user-images.githubusercontent.com/4990928/96488232-a6f5d100-120b-11eb-96ef-9fb5448c4615.gif)

**Comment by danilobuerger** [comment] 2020-10-19 17:07
@alpha0010 yes, thats correct. As far as I can tell from your gif there is no white flash across the **whole** screen but just in the content area, correct?

**Comment by mrousavy** [comment] 2020-10-19 17:08
it would be great to have a slowed down version of that, e.g.: by recording it with your phone camera in slow-mo mode.. 🤔

**Comment by alpha0010** [comment] 2020-10-19 17:12
Pulled it into GIMP, frame 43:

![frame-43](https://user-images.githubusercontent.com/4990928/96488947-c17c7a00-120c-11eb-8d87-b4a9ccf88b69.png)

**Comment by danilobuerger** [comment] 2020-10-19 17:19
Interesting, I can reproduce this in the playground too. Just the inner area flashes in that light grey color.

**Comment by danilobuerger** [comment] 2020-10-19 17:25
It seems the grey flash occurs under these conditions:

| setRoot.waitForRender | = true | = false |
| --- | --- | --- |
| bottomTabs | grey flash | grey flash |
| only stack | **no flash** | grey flash

**Comment by alpha0010** [comment] 2020-10-19 17:32
If it helps, the `setRoot()` used in our app is:
```ts
  Promise.all(promises).then((promiseResults) => {
    Navigation.setRoot({
      root: {
        sideMenu: {
          center: {
            stack: {
              children: [
                {
                  component: {
                    name: 'screens.Home',
                    passProps: {isStartUp: true},
                  },
                },
              ],
            },
          },
          right: {
            component: {
              id: 'SideMenu',
              name: 'menu.SideMenu',
              passProps: {
                lectionaryAvailable: promiseResults[0],
              },
            },
          },
        },
      },
    });
  });
```

**Comment by danilobuerger** [comment] 2020-10-19 19:00
@alpha0010 Could you please try and patch rnn with the PR at #6689 and see if that fixes your issue?

**Comment by alpha0010** [comment] 2020-10-19 19:39
It fixes it in the playground app, but not our app.  Perhaps related; we do not use bottom tabs?  Just a stack and a sidemenu?

**Comment by danilobuerger** [comment] 2020-10-19 19:40
Ah ok, if you are experiencing it with a sidemenu, this is a duplicate of #6000. So I am closing this to just keep one issue open.

**Closed by danilobuerger** 2020-10-19 19:40 UTC
Labels: platform: iOS, type: accepted/bug, user: reproduction provided

**Comment by danilobuerger** [comment] 2020-10-21 18:36
Should be fixed in 7.2.0

**Comment by marcshilling** [comment] 2020-11-25 17:20
This is still happening for me on 7.4.0 :(

**Comment by marcshilling** [comment] 2020-11-28 06:22
Seems related to #6092 and react-native-safe-area-context. If I remove the `<SafeAreaProvider>` around my Login component, no white flash.

CC @danilobuerger

**Comment by guyca** [comment] 2020-11-29 11:02
@marcshilling Can you please fork the library and reproduce the issue in the Playground app? It will help us understand if there's something wrong on your end or if there's still something that needs fixing.

**Comment by marcshilling** [comment] 2020-12-01 03:46
I think it can be chalked up to a limitation with `react-native-safe-area-context`, not an issue with this library. I got rid of the issue by just not using that context provider and just using `<SafeAreaView>` from React Native.

**Comment by mrousavy** [comment] 2020-12-01 08:08
@marcshilling The Safe Area should just manage insets (padding), and I don't believe it has so large padding that the view is actually 0 in size at first render. If anything weird comes up again please report back

**Comment by marcshilling** [comment] 2020-12-01 13:53
@mrousavy I can definitely reproduce it in the playground repo if you are curious

**Comment by izakfilmalter** [comment] 2021-03-20 12:39
I did the following with patch-package within `SafeAreaContext.tsx` in `react-native-safe-area-context`:

```jsx
  return (
    <NativeSafeAreaProvider
      style={[styles.fill, style]}
      onInsetsChange={onInsetsChange}
    >
      {insets != null ? (
        <SafeAreaFrameContext.Provider value={frame}>
          <SafeAreaInsetsContext.Provider value={insets}>
            {children}
          </SafeAreaInsetsContext.Provider>
        </SafeAreaFrameContext.Provider>
      ) : children}
    </NativeSafeAreaProvider>
  );
```

The problem was `insets != null ? () : null` which causes the flash.

**Comment by Garamani** [comment] 2021-04-29 04:52
For me (using react-native-navigation and redux persist) the only working solution is:

```
setTimeout(() => {
    SplashScreen.hide();
    registerScreens(Provider, store);
    Navigation.events().registerAppLaunchedListener(() => {
      persistStore(store, null, () => {
        Navigation.setRoot({
          root: {
            component: {
              name: 'app.SetRootScreens',
              options: {
                topBar: {
                  visible: false,
                },
                layout: {
                  componentBackgrosundColor: 'transparent',
                },
              },
            },
          },
        });
      });
    });
  }, 1000);
```

**Comment by Garamani** [comment] 2021-04-29 05:20
The above solution was not consistent. Randomly, I was still seeing a white flash. by adding the following lines (recommended earlier in comments):
```
Navigation.setDefaultOptions({
  animations: {
    setRoot: {
      waitForRender: true
    }
  }
});
```
 I don't see any white flash:

```
setTimeout(() => {
    SplashScreen.hide();
    registerScreens(Provider, store);
    Navigation.events().registerAppLaunchedListener(() => {
      persistStore(store, null, () => {
        Navigation.setDefaultOptions({
          animations: {
            setRoot: {
              waitForRender: true
            }
          }
        });
        Navigation.setRoot({
          root: {
            component: {
              name: 'app.SetRootScreens',
              options: {
                topBar: {
                  visible: false,
                },
                layout: {
                  componentBackgrosundColor: 'transparent',
                },
              },
            },
          },
        });
      });
    });
  }, 300);
```

**Comment by AlphaJuliettOmega** [comment] 2021-06-23 13:13
> It seems the grey flash occurs under these conditions:
> 
> setRoot.waitForRender	= true	= false
> bottomTabs	 grey flash	grey flash
> only stack	**no flash**	grey flash

Ah, I disabled my bottomTabs to implement custom bottomtabs now there is a white screen flash between Pin and Home screens.

I do use Animation.waitForRender option as well as setting the componentBackgroundColor in the Stack definitions

**Comment by ermakov95** [comment] 2024-06-13 19:11
How I reduced the flash:
1. The splash screen must coincide with the first screen so that the transition between them is imperceptible.
2. Set the following default animations for the setRoot:
`setRoot: {
      waitForRender: true,
      alpha: {
        duration: OS_IS_ANDROID ? 0 : 1500,
      },
    }`
(1500 is the approximate duration, you can choose it for yourself)
3. Find the file "node_modules/react-native-navigation/lib/ios/RNNSetRootAnimator.m" and write in options (UIViewAnimationOptionTransitionCrossDissolve | UIViewAnimationOptionCurveEaseIn)
<img width="795" alt="image" src="https://github.com/wix/react-native-navigation/assets/89069249/30461fa3-e8db-483e-8e82-ad11425a43df">
"UIViewAnimationOptionCurveEaseIn" will make the splash screen exit slower at the beginning of the animation.
