### ISSUE TITLE
ComponentDidAppear and ComponentDidDisappear is not called when open another native Android activity

### ISSUE THREAD

**Issue by lethienhung** [wix/react-native-navigation#7158] opened 2021-06-17 14:35 UTC
## 🐛 Bug Report

I'm working on a hybrid app and facing an issue of component's lifecycle in Android. For example, I have 2 screens, the first one is React Native screen using react native navigation component, the second one is another activity from android native. How can I trigger component did disappear when I open new activity and trigger component did appear when I pop back the native android activity?

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes. I've read the "Contributing Guidelines"

## To Reproduce

1. I have an existing native android app. Then I every time I want to navigate to a React Native Screen, I start an activity then override the onCreate function as below: 
```js
super.onCreate(savedInstanceState)
reactRootView = ReactRootView(this)
val bundle = intent.extras
reactInstanceManager?.currentReactContext?.let { it ->
    val map: WritableMap = Arguments.fromBundle(bundle)
    it
        .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
        .emit("androidNavigate", map)
}
```
    
2. On React Native side, I handle the "androidNavigate" event by `NativeEventEmitter addListener`: 

```js
this.eventListener = eventEmitter.addListener(
    'androidNavigate',
    (event) => {
        Navigation.setRoot({
            root: {
                stack: {
                    children: [
                        {
                            component: {
                                 name: event.screen,
                                 passProps: event.passProps,
                             },
                        },
                    ],
                },
            },
        });
    },
)
```

3. After display the React Native screen as I expected, I want to navigate to another native screen by starting a new Android activity via another native module.

```java
var intent = Intent()
intent.setClass(context, AnotherActivity::class.java)
intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK
context.startActivity(intent)
```

## Expected behavior

I expected the componentDidDisappear will trigger when I start another Android activity. Then after that, when I finish that activity, the componentDidAppear will be called on React Native side.

## Actual Behavior
The componentDidAppear and componentDidDisAppear are not triggering on React Native side

## Your Environment

- React Native Navigation version: 7.16.0
- React Native version: 0.63.3
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5 Emulator, Samsung A71, ...

**Comment by guyca** [comment] 2021-06-17 21:59
@lethienhung This is a very interesting use case. Before we look into it, can you please create a minimal reproducible example in the playground app? Thanks!

**Comment by lethienhung** [comment] 2021-06-27 12:03
Hi @guyca @swabbass I've created a minimal reproducible example here.
https://github.com/lethienhung/RNNIssuse

**Comment by swabbass** [comment] 2021-06-30 02:53
Hey @lethienhung, I cloned your project ad ran it, what I found was that the events are sent accordingly, am I missing something?

see:

https://user-images.githubusercontent.com/7227793/123894768-6a1bd580-d967-11eb-8427-5f1a5a69e70f.mov

**Comment by lethienhung** [comment] 2021-07-01 04:11
Hey @swabbass! 
Can u try it on the Nexus 5 Emulator.


https://user-images.githubusercontent.com/9305217/124063392-f3610400-da5c-11eb-9ceb-579b7ef9d307.mov

**Comment by swabbass** [comment] 2021-07-01 08:52
> Hey @swabbass!
> Can u try it on the Nexus 5 Emulator. I used Nexus 5X Emulator API 28
> 
>  Screen.Recording.2021-07-01.at.11.08.03.mov

I'll try that, it might be related to API 28? I will try a couple of configurations, but it seems that emulator configuration is not related, since the lifecycle callbacks are being called at the Application level, opening/closing activities.
what I'm trying to do is, eliminating the hardware configuration, I tried with my pixel 4, android 12, and got the same stuff, so I'll keep eliminating environmental stuff.

**Comment by swabbass** [comment] 2021-07-05 10:06
My explaination to this issue:
- Components will have `DidDisappear` sent once they are destroyed.
- Also, `ViewTreeObserver.onGlobalLayout`, will determine what events to call, once the layout changes.
- As a result, if a component didn't get destroyed then `DidAppear` will not be sent.
- Moreover, `onGlobalLayout` won't be triggered when the activity gets `Paused (Call/move toBG) / stopped (Open new activity)` .
- See docs, <img width="900" alt="Screen Shot 2021-07-05 at 10 55 33" src="https://user-images.githubusercontent.com/7227793/124437227-895b9e00-dd7f-11eb-9fa5-333861070141.png">

We can understand that a Component won't send events since the layout tree didn't change and the activity did not get destroyed:
- Components are destroyed once they are removed from their parent, or activity got destroyed.
- On all APIs, the activity won't get destroyed when opening a new activity or move to BG, hence, the activity lifecycle doesn't trigger `onDestroy`, "always", in order to send such events.
- My screenshot above included the `Don't keep activities` option enabled, which always destroys the activity.

I checked on most recent android APIs, and the app won't emit those events when app moves to BG or open new activity.

I think in order to be aligned with ios we need to have `ViewTreeObserver.OnWindowAttachListener` integrated, or just destroy views on stop, hence, move `onDestroy` logic, to `onStop`.
<img width="871" alt="Screen Shot 2021-07-05 at 12 37 45" src="https://user-images.githubusercontent.com/7227793/124452735-53261a80-dd8f-11eb-9e07-01ed382bc9d9.png">

@guyca @yogevbd wdyt?

**Comment by AlphaJuliettOmega** [comment] 2021-07-06 08:09
> I'll try that, it might be related to API 28? I will try a couple of configurations, but it seems that emulator configuration is not related, since the lifecycle callbacks are being called at the Application level, opening/closing activities.

Hmm with API 24 / Android 7 there seems to be a much bigger delay for didAppear events / sometimes they don't fire causing quite a mess.
Will bring more information as I acquire it but I doubt I'll investigate this really sooon.

**Comment by swabbass** [comment] 2021-07-06 09:06
> > I'll try that, it might be related to API 28? I will try a couple of configurations, but it seems that emulator configuration is not related, since the lifecycle callbacks are being called at the Application level, opening/closing activities.
> 
> Hmm with API 24 / Android 7 there seems to be a much bigger delay for didAppear events / sometimes they don't fire causing quite a mess.
> Will bring more information as I acquire it but I doubt I'll investigate this really sooon.

This issue here is not related to API or configuration, [comment](https://github.com/wix/react-native-navigation/issues/7158#issuecomment-873985190).

If you are facing other issues, please feel free to create one and reproducible code and we will investigate it.

**Closed** 2021-07-07 11:25 UTC
Labels: platform: Android, user: requires reproduction
