### ISSUE TITLE
V3 NavBar not updated

### ISSUE THREAD

**Issue by NISUSIN** [wix/react-native-navigation#5587] opened 2019-10-16 00:15 UTC
### Issue Description

Navbar is not updated when we pop too fast, on android with the hardware button. Can be reproduce on simulator with timeout

### Steps to Reproduce / Code Snippets / Screenshots
Use my repo: https://github.com/NISUSIN/navbarbug

Just push a screen and pop immediatly with back button android, navbar is not updated.

---
### Environment
* React Native Navigation version: 3.2.0
* React Native version: 0.61
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Both

**Comment by NISUSIN** [comment] 2019-10-16 09:37
topBar not updated and event componentDidAppear not fired too, maybe a way where to search.

**Comment by alpamys-qanybet** [comment] 2019-10-18 13:38
hey guys,  any update on this?,  my boss will kill me if I show him this bug on application.

**Comment by NISUSIN** [comment] 2019-10-18 16:51
Same effect with open drawer, close drawer and change tabs instant, didAppear event not fired on new screen.

**Comment by alpamys-qanybet** [comment] 2019-10-18 21:59
V1 was great, V2and3 are some kind of mess with JS.

**Comment by NISUSIN** [comment] 2019-10-19 10:09
@alpamys-qanybet  For topBar update, you can use this workaround.

When you push the screen, pass component id, and on your new screen when you unmount it, update the excomponent.

Exemple:

		Navigation.push(this.props.componentId, {
		  component: {
		    name: 'Collection',
		    passProps: {
		    	exCompo:  this.props.componentId,
		    },
            }

And in screen Collection, make this:

	componentWillUnmount(){
		if(this.props.exCompo == "Profil"){
                  Navigation.mergeOptions(this.props.exCompo, {	
                           //Make your stuff			
                 });
            }

                  //Or make function like this UpdaterClass.update(this.props.exCompo)
                 //And in your UpdaterClass, you make your mergeOption
    }

It will work, and for drawer bug, if you use bottomTabs, you can use :
```

//Same effect than DidAppear on bottom Screen
          Navigation.events().registerBottomTabSelectedListener(({ selectedTabIndex,  unselectedTabIndex }) => {
         if(selectedTabIndex == 2){
	        }
	      });
```

**Comment by ItsNoHax** [comment] 2019-11-08 08:43
Going to close this as it's a duplicate of: #4405

**Closed by ItsNoHax** 2019-11-08 08:43 UTC
