### ISSUE TITLE
[v2] Can't start application.

### ISSUE THREAD

**Issue by amin3mej** [wix/react-native-navigation#4382] opened 2018-12-03 04:16 UTC
### Issue Description
I work on my application last night and everything worked successfully. Now I want to continue my developing and see that I can't start my application because I get this error.

```Error: Missing component data.name
Error: Missing component data.name
    at LayoutTreeCrawler._assertComponentDataName (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:88213:17)
    at LayoutTreeCrawler._handleComponent (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:88181:14)
    at LayoutTreeCrawler.crawl (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:88166:16)
    at arrayEach (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:80853:13)
    at Function.forEach (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:85274:16)
    at LayoutTreeCrawler.crawl (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:88171:11)
    at Commands.setRoot (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:87719:32)
    at Navigation.setRoot (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:80084:30)
    at _callee$ (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:100444:49)
    at tryCatch (blob:file:///1957ca21-c2ec-4a07-bb05-872403708419:28062:19)
```
### Steps to Reproduce / Code Snippets / Screenshots
I don't know how to Reproduce.

### Environment
* React Native Navigation version: 2.1.3
* React Native version: 0.56.1
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X simulator, version 12.1, Debug

**Comment by amin3mej** [comment] 2018-12-03 04:42
I realize that when I import baseUrl from my config file that error happens.
Config.js
```import { INTRO_MAIN, HOME_MAIN } from './screens/Registers';

const defaultAuthenticatedScreen = HOME_MAIN;
const defaultGuestScreen = INTRO_MAIN;
const baseUrl = 'http://domain.com';

export { defaultAuthenticatedScreen, defaultGuestScreen, baseUrl };
```

**Comment by ItsNoHax** [comment] 2018-12-03 13:17
Sorry but this issue is not clear enough, does not have reproducible steps or sample code. Going to close this.

**Closed by ItsNoHax** 2018-12-03 13:17 UTC

**Comment by kkulikowski** [comment] 2019-01-01 22:31
if anyone have the same issue - i found solution.. i did the same mistake.
when creating navigation i did something like this:
`children: [{
        component: {
          name: '',
          passProps: {
            text: 'stack with one child'
          }
        }
      }],` it was not working, the same issue like above. It happened because property name inside component was empty. after changing to
`children: [{
        component: {
          name: 'my.component.name',
          passProps: {
            text: 'stack with one child'
          }
        }
      }],` it was all good again.
