### ISSUE TITLE
IOS - Back Button Not Hiding

### ISSUE THREAD

**Issue by keremcubuk** [wix/react-native-navigation#6338] opened 2020-06-26 10:12 UTC
### Issue Description

When I try to hide back button with the **mergeOptions**, back button is not hiding only **IOS**.

### Steps to Reproduce / Code Snippets / Screenshots

```js                                       
 Navigation.mergeOptions(this.props.componentId, {
       topBar: {
            leftButtons: [],
            backButton: { visible: false }
       },
 });
```

I have tried backButton and leftButtons for hiding but only Android works. I also tried a workaround which is opened for V2. 
[Click to see](https://github.com/wix/react-native-navigation/issues/4384)

This solution works but I have a lot of screens, so that I have to pass this usage to every screen.

```js
 Navigation.mergeOptions(this.props.componentId, {
       topBar: {
            leftButtons: Platform.OS === 'android' ? [] : [{ id: 'hideBack', text: '' }],
       },
 });
```

---
### Environment
* React Native Navigation version: **6.8.0**
* React Native version: **0.62.2**
* Platform(s) (iOS, Android, or both?): **iOS**
* Device info (Simulator/Device? OS version? Debug/Release?): 
   - **Simulator&Device**
   - **iOS 11,12,13**
   - **Debug&Release**

**Comment by jinshin1013** [comment] 2020-06-29 05:52
Hi @keremcubuk, I couldn't reproduce this problem in the latest Playground app. Could you try running the Playground app and add the following in `PushedScreen.js` file for me?

```ts
<Button label='Hide back button' onPress={() => {
  Navigation.mergeOptions(this.props.componentId, {
    topBar: {
      backButton: { visible: false }
    }
  })
}} />
<Button label='Show back button'  onPress={() => {
  Navigation.mergeOptions(this.props.componentId, {
    topBar: {
      backButton: { visible: true }
    }
  })
}} />
```

---

The following is a clip to demonstrate I was able to toggle the visibility of the back button using your example on `iOS 13.5`.

![backbutton](https://user-images.githubusercontent.com/17612922/85977700-6be34e00-ba20-11ea-8d27-2848f36a99a8.gif)

**Comment by keremcubuk** [comment] 2020-06-29 13:43
Hello @jinshin1013,

I'm using dynamic updated views so that, I have to use mergeOptions. In playground, examples are simple for my problem. This is a little example of my code block.

```js
class MyExample extends React.Component {
  static options(passProps) {
    return {
      topBar: {
        title: { text: 'Start Screen' },
        leftButtons: [
          {
            id: 'myCustomBack',
            icon: myImages.back,
          },
        ],
      },
    };
  }

  onLoad(content) {
    const viewName = content.viewname;
    if (viewName === 'start') {
      Navigation.mergeOptions(this.props.componentId, {
        topBar: { title: { text: 'Start Screen' } },
      });
    } else if (viewName === 'status') {
      Navigation.mergeOptions(this.props.componentId, {
        topBar: {
          title: { text: 'Final Screen' },
          leftButtons: [],
          backButton: { visible: false },
        },
      });
    }
  }

  render() {
    return (
      <MyDynamicView
        componentId={this.props.componentId}
        navigator={this.props.navigator}
        onLoad={content => this.onLoad(content)}
      />
    );
  }
}
```

When I came to status screen.  Navigation.mergeOptions triggers, title updates. But only back button or leftButtons not hiding.
**In this case Android works well, but iOS not works.**

Any suggestion?

**Comment by jinshin1013** [comment] 2020-07-01 01:04
Hi @keremcubuk, thanks for the clarification. I am still unable to reproduce this problem. Please see the code/clip below:

```tsx
static options() {
  return {
    topBar: {
      title: {
        text: 'Pushed Screen',
      },
      leftButtons: [
        {
          id: 'LEFT_BUTTON',
          icon: require('../../img/navicon_add.png'),
        },
      ],
    },
  };

hideLeftButton = () => {
  return Navigation.mergeOptions(this.props.componentId, {
    topBar: {
      backButton: {
        visible: false,
      },
      leftButtons: [],
    },
})
}
```

![backbutton](https://user-images.githubusercontent.com/17612922/86191353-29d61b80-bb8a-11ea-938c-29e6065cfcfd.gif)

It'd be very helpful if you could provide a minimal reproduction on Github for me to have a look.

**Comment by keremcubuk** [comment] 2020-07-03 18:50
Hello again @jinshin1013, I am sorry about the share my code blocks. I couldn't share open source demo for reproduction. If I am find the another way for reproduce issue, I will give you more information.

**Comment by jinshin1013** [comment] 2020-07-04 01:51
Thank you @keremcubuk, will close the issue for now.

**Closed by jinshin1013** 2020-07-04 01:51 UTC
Labels: user: requires reproduction
