### ISSUE TITLE
Nav Bar Button Font Size Reverts On Press

### ISSUE THREAD

**Issue by kjbappsllc** [wix/react-native-navigation#2353] opened 2017-12-15 07:15 UTC
When I set the font size on a text only nav bar button, the font size would revert back to the default when I click on it.

Here is the code that I am using to set the button:

`this.props.navigator.setButtons({
      rightButtons: [
        {
          title: 'NEXT',
          buttonColor: 'white',
          buttonFontSize: 12
        }
      ]
    });`

---
### Environment
* React Native Navigation version: "^1.3.4"
* React Native version: "0.50.1"
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): IPhone 6 Simulator

**Comment by guyca** [comment] 2017-12-15 09:46
I've noticed this bug yesterday. Apparently, when setting the color and font in AppStyle and not in the button declaration the button looks as expected.

**Comment by luco** [comment] 2017-12-25 06:16
Duplicate of #2087?

**Comment by yogevbd** [comment] 2017-12-27 12:54
Fixes https://github.com/wix/react-native-navigation/commit/989fb6ad184989d19870e21aab089dc65e62dcac

**Comment by luco** [comment] 2017-12-30 03:26
@yogevbd Doesn't accept custom font anymore.

**Closed** 2018-01-01 14:09 UTC
Labels: Bug - iOS
