### ISSUE TITLE
[V2] [Android] 【critical】mergeOptions apply all the options of screen

### ISSUE THREAD

**Issue by sapjax** [wix/react-native-navigation#3393] opened 2018-06-20 09:03 UTC
### Issue Description

I `setRoot` with `bottomTabs` which contain 4 children

```javascript
const bottomTabs = {
      children: [
        {
          stack: {
            children: [
              {
                component: {
                  name: `${PACKAGE_NAME}.Assets`,
                },
              },
            ],
            options: {
              bottomTab: {
                testID: 'TabAssets',
                title: t('wallet'),
                icon: icon.tabAssetThin,
              },
            },
          },
        },
        {
          stack: {
            children: [{
              component: {
                name: `${PACKAGE_NAME}.Market`,
              },
            }],
            options: {
              bottomTab: {
                testID: 'TabMarket',
                title: t('market'),
                icon: icon.tabMarket,
              },
            },
          },
        },
        {
          stack: {
            children: [{
              component: {
                name: `${PACKAGE_NAME}.Discovery`,
              },
            }],
            options: {
              bottomTab: {
                testID: 'TabBrowser',
                title: t('browse'),
                icon: icon.tabDiscover,
              },
            },
          },
        },
        {
          stack: {
            children: [{
              component: {
                name: `${PACKAGE_NAME}.Profile`,
              },
            }],
            options: {
              bottomTab: {
                testID: 'TabProfile',
                title: t('profile'),
                icon: icon.tabMe,
              },
            },
          },
        },
      ],
      options: {
        bottomTabs: {
          visible: true,
          animate: false, 
          translucent: false,
          disableIconTint: true, // set true if you want to disable the icon tinting
          disableSelectedIconTint: true,
          backgroundColor: color.t10,
          tabColor: color.t4,
          selectedTabColor: color.main,
          fontFamily: 'Helvetica',
          fontSize: 10,
          titleDisplayMode: 'alwaysShow',
        },
      },
    }
```

in `defaultOptions` I set `statusBar` style as `dark`:

```javascript
  statusBar: {
    visible: true,
    style: 'dark',
    backgroundColor: color.t10,
  },
```

and in the latest child screen of bottomTabs **Profile**,  I set `statusBar` style as `light`:

```javascript
 statusBar: {
        style: 'light',
        backgroundColor: color.t1,
      },
```

When app started, It renders the first tab screen,  but with the `statusBar` style configured in **Profile** screen.

---
### Environment
* React Native Navigation version: 2.0.2361
* React Native version: 0.51
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device, Debug & Release

**Comment by sapjax** [comment] 2018-06-20 10:12
I found this issue is caused by `mergeOptions` in component `construct` function (even though the merged options has no `statusBar` setting ).
after I remove `mergeOptions` from `construct` function, seems it works now.

**Comment by sapjax** [comment] 2018-06-20 15:04
I found the problem is caused by the code below:
```
navigator.mergeOptions(this.props.componentId, {
      bottomTab: {
        badge: n ? String(n) : null,
      },
    })
```

This code is run in the fourth tab screen after the first screen has appeared.
And it set the badge correctly，  but it causes the `statusBar` style as the fourth tab screen.
Notice, I didn't switch to the fourth screen, just run `mergeOptions` with `badge`  in the screen component, 
the **all** `options` of the fourth tab screen will be applied ‼️

I notice that many other bugs caused by `mergeOptions` on Android.

**Comment by sapjax** [comment] 2018-07-11 10:35
@guyca

**Comment by numen31337** [comment] 2018-08-07 09:47
Have the same issue when updating the `top bar` for the `root screen` of the `stack` (which is not currently presented). After the update, the updated `top bar` is presented on the currently presented screen. The issue is only on Android, everything is good on the iOS side.

**Comment by sapjax** [comment] 2018-08-07 10:15
@yogevbd

**Comment by DavitVosk** [comment] 2019-09-16 08:22
Some strange problem happens on my Android as well with mergeOptions. When I try to change my  bottom tab badges from some number to another one it works, but when I try to change the badge number to null (namely hide the badge on tab) - it does not work:

`navigator.mergeOptions(this.props.componentId, {
      bottomTab: {
        badge: n === 0 ? String(n) : null,
      },
    })`.

How I can such kind of problem?

**Comment by DavitVosk** [comment] 2019-09-16 08:55
Ok, I found the fix. We need to pass an empty string instead of `null` to clear badge

**Comment by guyca** [comment] 2020-02-03 05:11
This issue has already been fixed, closing.

**Closed by guyca** 2020-02-03 05:11 UTC
Labels: platform: Android, v2, 📌 pinned
