### ISSUE TITLE
Declarative API

### ISSUE THREAD

**Issue by brunolemos** [wix/react-native-navigation#513] opened 2016-11-29 22:36 UTC
Is it to possible now to start moving to a more declarative API?

- Having to call functions like `startTabBasedApp` are against the React way of doing things
- It makes it harder to have control over the app, like customizing the tabbar on runtime #466
- Having to change so many native files (AppDelegate, MainApplication, MainActivity, ...) makes it impossible to use the `react-native upgrade` command, because it would overwrite almost everything

**Comment by DanielZlotin** [comment] 2016-12-04 15:33
Thanks for the suggestions, you actually made 3-4 different and not necessarily related points.
1. Declarative API:
As discussed in #414 this project allows you to create and control skeletal navigational components in iOS and Android, in a semi-opinionated way, which are in turn imperative by design. Adding declarative functionality - parsing some DSL or even JSX, aggregating commands, and managing the deltas - while maybe desired, will only slow our (already too slow) progress and interfere with the emerging design of this project - which is still in early development and experimental. This can and *will* be achieved in the future, by us or the community, by wrapping react-native-navigation with something that does just that.

2. Dynamic styling for BottomTabs and other "declare once" components:
This is a feature we thought about, and will likely implement in the future. It has little to do with declarative API, and it's just a feature of being more flexible. Declarative or not, you are welcome to open a feature request with this and we will try to assign it to a future milestone.

3. `react-native upgrade`: we don't use this command ourselves for a simple reason - we like full control, especially when touching core stuff like `AppDelegate.m`. The changes required from you for this project to work are minimal but important - and a little different thant what is required by RN. The reason is simple - we *are* doing stuff differently than what is created by `react-native init`. The difference is mainly instead of creating 1 react root view inside 1 single ViewController / Activity, we create multiple, according to what is required by the user. This way you get truly native navigation, and not some JS code **mocking** native by firing certain animations.

Once 2.0.0 is out we will have a simple migration process, and you won't need to do `react-native upgrade` unless you are writing custom native code. In that case, you have no choice but to understand each version what needs to be changed (same thing we are doing in production code which uses RNN)

A general note on the API - the main goal of 2.0.0 is a consistent and simple to use API. This means no more `this.props.navigator` calls. ALL commands will be usable through static function calls. ALL listeners will be assignable statically also. This basically means you can easily use Navigation commands and queries from your actions / thunks / sagas / use-cases.

**Closed by DanielZlotin** 2016-12-04 15:33 UTC

**Comment by henrikra** [comment] 2017-04-06 10:04
@DanielZlotin To your last point here: so basically I could call `navigator` easily from my sagas without passing `navigator` in actions? If yes when is this coming?

**Comment by DanielZlotin** [comment] 2017-04-06 16:26
yes, and "soon".
You can follow the progress under the [v2 branch](https://github.com/wix/react-native-navigation/tree/v2)
or the [milestone](https://github.com/wix/react-native-navigation/milestone/1)
