### ISSUE TITLE
Small button area in navbar on ios

### ISSUE THREAD

**Issue by sorokin0andrey** [wix/react-native-navigation#5723] opened 2019-12-03 13:49 UTC
### Issue Description

Small button area in navbar on ios. With real use cases, it’s very difficult to hit the button.

### Steps to Reproduce / Code Snippets / Screenshots

<img width="361" alt="Снимок экрана 2019-12-03 в 16 44 15" src="https://user-images.githubusercontent.com/3092044/70056538-af8dea80-15ec-11ea-9e24-137b9f8ca14f.png">

---
### Environment
* React Native Navigation version: 4.0.3
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): All ios devices Debug, Release

**Comment by sorokin0andrey** [comment] 2020-01-03 09:19
not stale

**Comment by sorokin0andrey** [comment] 2020-02-02 15:09
Not stale

**Comment by bneigher** [comment] 2020-02-07 11:40
not stale

**Comment by sorokin0andrey** [comment] 2020-03-08 14:17
not stale

**Comment by sorokin0andrey** [comment] 2020-04-07 14:34
not stale lol

**Comment by bneigher** [comment] 2020-04-07 20:52
not stale.

FWIW - I have a post install patch that fixes the issue for me, its just annoying to have to make my own edits to this:  ./node_modules/react-native-navigation/lib/ios/RNNUIBarButtonItem.m

```objective-c
-(instancetype)init:(NSString*)buttonId withIcon:(UIImage*)iconImage {
  // UIButton* button = [[UIButton alloc] init];
  // [button addTarget:self action:@selector(onButtonPressed) forControlEvents:UIControlEventTouchUpInside];
  // [button setImage:iconImage forState:UIControlStateNormal];
  // [button setFrame:CGRectMake(0, 0, iconImage.size.width + 40, iconImage.size.height + 20)];
  // self = [super initWithCustomView:button];
  // self.buttonId = buttonId;
  // button.contentHorizontalAlignment = UIControlContentHorizontalAlignmentLeft;
  self = [super initWithImage:iconImage style:UIBarButtonItemStylePlain target:self action:@selector(onButtonPressed)];
  self.buttonId = buttonId;
  return self;
}
```

@sorokin0andrey lmk if this works for you and hopefully if its legit the wix team can get this changed in the source

**Comment by sorokin0andrey** [comment] 2020-05-08 10:01
Not stale

**Comment by sorokin0andrey** [comment] 2020-06-08 10:03
Not stale

**Comment by danilobuerger** [comment] 2020-09-16 19:57
Duplicate of #5000 , PR at #6482

**Closed by danilobuerger** 2020-09-16 19:57 UTC
Labels: feature: TopBar Buttons, platform: iOS, type: accepted/bug
