### ISSUE TITLE
[iOS] largeTitle styles aren't being applied in iOS 13

### ISSUE THREAD

**Issue by m0wo** [wix/react-native-navigation#6361] opened 2020-07-03 12:28 UTC
### Issue Description

When using largeTitle in iOS 13 custom styling, fonts aren't being applied.

### Steps to Reproduce / Code Snippets / Screenshots

```js
static options() {
  return {
    topBar: {
      title: {
        text: 'Test',
      },
      largeTitle: {
        drawBehind: false,
        visible: true,
        fontFamily: "FSRufus",
        fontSize: 48,
        color: "#b01c2e"
      },  
      background: {
        color: 'white'
      }
    }
  }
}
```

### 13.3 (left) vs 12.0:

<img width="523" alt="Screenshot 2020-07-03 at 13 26 02" src="https://user-images.githubusercontent.com/3648571/86469156-c4705f00-bd30-11ea-8987-fc9fe38c75e8.png">

---
### Environment
* React Native Navigation version: 6.7.5
* React Native version: 0.62.2
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iPhone X @ 13.3

**Comment by jinshin1013** [comment] 2020-07-04 01:44
Hi @m0wo 🙌  , thanks for reporting the issue! Closing as this is a duplicate of #6337.

**Closed by jinshin1013** 2020-07-04 01:44 UTC
