### ISSUE TITLE
Keyboard.dismiss() not work on Android

### ISSUE THREAD

**Issue by Synaric** [wix/react-native-navigation#6447] opened 2020-07-30 10:37 UTC
example:
```
componentWillUnmount() {
    Keyboard.dismiss()
  }
```

---
### Environment
* React Native Navigation version: 6.10.1
* React Native version: 0.62.2

**Comment by Synaric** [comment] 2020-08-28 05:34
I know **blurOnUnmount** blurOnUnmount, but sometimes I want to dismiss the keyboard in a onPress callback, Keyboard.dismiss()  is still not working.

**Comment by karolissaint** [comment] 2020-09-01 09:14
Any progress?

**Comment by jinshin1013** [comment] 2020-09-25 03:19
Hi @Synaric @karolissaint, I cannot reproduce this issue on the playground app. Could you provide a minimal reproduction for us to have a look please? 

Closing this for now.

**Closed by jinshin1013** 2020-09-25 03:19 UTC
