### ISSUE TITLE
App is crashing on start

### ISSUE THREAD

**Issue by aditya21** [wix/react-native-navigation#2992] opened 2018-04-07 19:50 UTC
react-native-cli: 2.0.1
react-native: 0.54.4

I am trying to implement wix naviagation with redux.
The app is crashing on start. Tried many changes but finally gives error.

https://github.com/aditya21/react_native_basic

**Comment by guyca** [comment] 2018-04-08 07:01
Closing as this is not a bug.

**Closed by guyca** 2018-04-08 07:01 UTC
Labels: For Stack Overflow

**Comment by 2n2n** [comment] 2018-08-31 09:46
hi what's the reason for the crash? mine is also the same.
