### ISSUE TITLE
[iOS] Updated RNNUIBarButtonItem.m implementation with constraints causes crash

### ISSUE THREAD

**Issue by chyrta** [wix/react-native-navigation#4960] opened 2019-04-09 11:20 UTC
### Issue Description

After upgrading from 2.11.0 to the latest version (2.17.0), our team started experiencing an issue with updating bar buttons in tab-based React Native application. The app crashed and we couldn't understand the root of the issue.

### Steps to Reproduce / Code Snippets / Screenshots

After calculating values, we called a simple `mergeOptions` where we pass an updated set of buttons and its props: 
```
Navigation.mergeOptions(
  this.props.componentId,
  options.updatedHeader(this.onButtonPress, disabled)
)
```
And then we got the following error:
<img width="813" alt="Screen Shot 2019-04-08 at 14 40 53" src="https://user-images.githubusercontent.com/8209964/55796108-d9305980-5ad1-11e9-887d-5b851c08353b.png">

We started to compare the source code of React Native Navigation 2.11.0 and 2.17.0 and noticed the changes done regarding constraints (RNNUIBarButtonItem.h file) of bar button items after 2.11.0. We removed these lines, and everything worked ok.

<img width="1594" alt="Screen Shot 2019-04-08 at 22 37 31" src="https://user-images.githubusercontent.com/8209964/55796187-0250ea00-5ad2-11e9-8341-9444ab1b28d2.png">

---
### Environment
* React Native Navigation version: 2.17.0
* React Native version: 0.58.6
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, iOS 12

**Comment by yogevbd** [comment] 2019-04-24 11:22
Can you please try to reproduce it in the playground app? I'm trying with no success

**Comment by ItsNoHax** [comment] 2019-06-25 12:12
@chyrta This will be fixed in 2.21.2 as soon as @guyca make's a new release. Specifically this commit: https://github.com/wix/react-native-navigation/commit/29829ae2aa972fa7df20cd50e0d43efa8991fbf2

**Comment by chyrta** [comment] 2019-06-25 20:49
@ItsNoHax Sounds great guys. Looking forward to being able to update to the newest version.

**Comment by ItsNoHax** [comment] 2019-06-25 20:51
Try it out on 2.22.0 already

**Comment by ItsNoHax** [comment] 2019-06-26 07:25
I'm going to go ahead and close the issue because I'm no longer seeing the crash after upgrading to 2.22.0. Please tag me if you are still running into issues.

**Closed by ItsNoHax** 2019-06-26 07:25 UTC
Labels: platform: iOS, type: accepted/bug, 📌 pinned
