### ISSUE TITLE
TopBar buttons not rendered when waitForRender is set to true on iOS

### ISSUE THREAD

**Issue by rosskhanas** [wix/react-native-navigation#6085] opened 2020-03-29 11:47 UTC
### Issue Description

Seems like `mergeOptions` does not work well with `waitForRender: true`.

**Without `showModal: {  waitForRender: true }`**

![image](https://user-images.githubusercontent.com/10609041/77848165-9cbaa980-71cb-11ea-8828-f22e75cb019e.png)

**With `showModal: {  waitForRender: true }`**

![image](https://user-images.githubusercontent.com/10609041/77848184-bc51d200-71cb-11ea-8109-3a27480d793d.png)

### Steps to Reproduce / Code Snippets / Screenshots

1. Set default options:

```
Navigation.setDefaultOptions({
    animations: {
      push: {
        waitForRender: true,
      },
    },
  });
```

2. Open any modal page with top bar buttons added by `mergeOptions`.

---
### Environment
* React Native Navigation version: 6.3.2
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator, 13.2.2

**Comment by rosskhanas** [comment] 2020-03-29 11:52
Seems like wrapping `Navigation.mergeOptions` into  `requestAnimationFrame` can be used as a workaround.

```
requestAnimationFrame(() => {
  requestAnimationFrame(() => {
    Navigation.mergeOptions({ ... })
  });
});
```

**Comment by nimerfarahty** [comment] 2020-04-27 15:53
i have the same issue and it seems i should wait before doing mergeOptions

**Comment by rosskhanas** [comment] 2020-05-29 08:00
Not stale.

**Comment by danilobuerger** [comment] 2020-10-20 11:48
@rosskhanas Where are you calling `mergeOptions` from? Could you please provide some more code on how to reproduce this with the playground app?

**Comment by rosskhanas** [comment] 2020-10-20 12:18
@danilobuerger thank you for looking at this.

So I have a function which opens the modal:
```
modalOpen({
    name: "suite.ModalOrganizationInformationUpdate",
    options: {
      topBar: {
        leftButtons: [
          {
            id: NAVBAR_BUTTON_INFORMATION_MAIN_UPDATE_CANCEL,
            text: "Cancel",
          },
        ],
        rightButtons: [
          {
            enabled: false,
            id: NAVBAR_BUTTON_INFORMATION_MAIN_UPDATE_SAVE,
            text: "Save",
          },
        ],
        title: {
          text: "Edit Information",
        },
      },
    },
    passProps: {
      pageClose: modalClose,
      topBarButtonLeftIconAndroid,
      topBarButtonLeftTextClose,
      topBarButtonRightIconSaveAndroid,
      topBarButtonRightTextSave,
      ...args,
    },
  });
```

Then in the `ModalOrganizationInformationUpdate` I have a `componentDidMount` method implemented:

```
componentDidMount() {
    Navigation.events().bindComponent(this);
    BackHandler.addEventListener("hardwareBackPress", this.onHardwareBackPress);
    const { componentId } = this.props;
    Navigation.mergeOptions(componentId, {
      topBar: {
        rightButtons: [
          {
            enabled: true,
            id: NAVBAR_BUTTON_INFORMATION_MAIN_UPDATE_SAVE,
            text: "Save",
          },
        ],
      },
    });
  }
```

So I just open the page with `Save` button disabled, then I set the `enabled: true` but it is still disabled.

**Comment by danilobuerger** [comment] 2020-10-20 12:20
Is there a reason you are doing this via `Navigation.mergeOptions` instead of `static options`?

**Comment by rosskhanas** [comment] 2020-10-20 12:27
I just simplified the existing code to provide a simpler example. In a full implementation, there is extra validation(like if the user has permission to edit the page or if all required fields are filled) that is stored in a local state. I guess it is not possible to use state values in `static options`... Am I right?

**Comment by danilobuerger** [comment] 2020-10-20 12:29
Afaik only props are passed.

**Comment by guyca** [comment] 2020-10-20 12:49
@rosskhanas You can execute whatever logic you want in static options, there's an example in [the docs](https://wix.github.io/react-native-navigation/docs/style-options#handle-props-in-static-options).

But regardless this should be fixed. Thanks for looking into this @danilobuerger 🙇

**Comment by danilobuerger** [comment] 2020-10-20 14:36
@rosskhanas could you please try with #6702 . Does that solve all your issues?

**Comment by rosskhanas** [comment] 2020-10-20 17:22
> @rosskhanas could you please try with #6702 . Does that solve all your issues?

Could be I messed up and failed to apply changes correctly, but I got a build error:

![image](https://user-images.githubusercontent.com/10609041/96621906-e7d80d80-1311-11eb-998e-077236d74fab.png)

**Comment by danilobuerger** [comment] 2020-10-20 17:24
Doesn't really say much... don't forget to run pod install after applying the patch and optionally to clean the build dir with xcode.

**Comment by rosskhanas** [comment] 2020-10-20 17:50
![image](https://user-images.githubusercontent.com/10609041/96624759-dc86e100-1315-11eb-816e-10f5daafb36e.png)

@danilobuerger is this helpful?

**Comment by danilobuerger** [comment] 2020-10-20 17:52
It looks like you applied the patch onto an older version? The patch will probably only work on the current master.

**Comment by rosskhanas** [comment] 2020-10-21 07:56
@danilobuerger I tried again, seems like your PR fixes the bug! 🥳

**Closed** 2020-10-25 12:31 UTC
Labels: platform: iOS, type: accepted/bug
