### ISSUE TITLE
[V4] Can't set top bar's background color to transparent 

### ISSUE THREAD

**Issue by ShklyaroValera** [wix/react-native-navigation#5691] opened 2019-11-27 17:36 UTC
### Issue Description

Can't set top bar's background color to transparent after updating to 4.0.0

### Steps to Reproduce / Code Snippets / Screenshots

[FILL THIS OUT]

---
### Environment
* React Native Navigation version: 4.0.0
* React Native version: 0.61.1
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator IOS13 Debug

**Comment by jfrolich** [comment] 2019-11-28 07:40
Same here. Also the border is always visible.

**Comment by manuhook** [comment] 2019-11-28 09:06
Same problem on our app, it used to work with : 
```
      topBar: {
        borderHeight: 0,
        background: {
          color: 'transparent',
        },
      }
```

**Comment by jfrolich** [comment] 2019-12-02 02:09
Awesome!

**Comment by manuhook** [comment] 2019-12-02 18:13
Hi @yogevbd , thank you for the fix
But it's working only on iOS 13, it's possible to fix top bar transparency for iOS 12 please ?
Thank you 🙏

**Comment by yogevbd** [comment] 2019-12-03 13:01
What options do you apply on the `topBar`? I'm trying to reproduce it

**Comment by manuhook** [comment] 2019-12-03 13:19
@yogevbd thanks for looking 

I'm testing on the last iOS12 available (12.4.3)

On Navigation.setDefaultOptions :
```
    // NavBar
    topBar: {
      title: {
        color: Colors.TXTDARK,
        ...Platform.select({
          ios: {
            fontWeight: 'semibold',
          },
          android: {
            fontFamily: 'Roboto-Medium',
          },
        }),
      },
      background: {
        color: 'transparent',
      },
      visible: true,
      drawBehind: true,
      buttonColor: Colors.NAVBGLIGHT,
      backButton: {
        color: Colors.TXTDARK,
      },
      ...Platform.select({
        android: {
          borderHeight: 0,
          elevation: 0,
        },
        ios: {
          noBorder: true,
        },
      }),
    },
```

**Comment by manuhook** [comment] 2019-12-03 14:46
On the playground app you can reproduce it on LayoutsScreen  with :

```
class LayoutsScreen extends React.Component {
  static options() {
    return {
      topBar: {
        testID: WELCOME_SCREEN_HEADER,
        title: {
          text: 'React Native Navigation'
        },
        drawBehind: true,
        background: {
            color: 'transparent',
        },
      },
      layout: {
        backgroundColor: "green",
      },
    };
  }
```

![Simulator Screen Shot - iPhone 5s - 2019-12-03 at 15 42 38](https://user-images.githubusercontent.com/531834/70061092-f6c3ad80-15e3-11ea-800e-8c7afb392c88.png)

**Comment by manuhook** [comment] 2019-12-16 20:12
Hi @yogevbd 
the problem was fixed on 4.0.4
but it's not working anymore on 4.0.5 (& 4.0.6) - (we have a black topbar on iOS < 13 when backgroundcolor is set to transparent).
can you reopen please ?

**Comment by guyca** [comment] 2019-12-18 10:30
@manuhook Can you please reproduce in the playground app?

**Comment by yogevbd** [comment] 2019-12-18 10:35
Hey @manuhook, when you want the `topBar` to be transparent, you need to set `topBar.drawBehind: true`. The reason is that when you set the topBar to be transparent and `drawBehind` sets to false, nothing gets rendered behind it and you get the window default black color.
Until latest version we colored the window in white color so this issue wasn't noticeable. iOS 13 new pageSheet modals forced us to stop color the window background color.

In the next release we will remove drawBehind support and instead we will recommend using `SafeAreaView` when you have a view that needs to layout below the `topBar`.

**Comment by manuhook** [comment] 2019-12-18 11:10
@guyca yes it's reproducible on playground app 
@yogevbd topBar.drawBehind is set to true : 
![Capture d’écran 2019-12-18 à 12 09 37](https://user-images.githubusercontent.com/531834/71081343-4e8b1880-218f-11ea-9508-ac1e5c37ca9f.png)

**Closed** 2019-12-18 16:20 UTC
Labels: platform: iOS, type: accepted/bug
