### ISSUE TITLE
Changing enabled of a rightButton is not reflected in app

### ISSUE THREAD

**Issue by eliaslecomte** [wix/react-native-navigation#6245] opened 2020-05-26 06:50 UTC
### Issue Description

When displaying a modal with a rightButton, changing the enabled property, doesn't change the button visually on Android. So if you change enabled from false to true, the button remains unclickable and greyed out.

### Steps to Reproduce / Code Snippets / Screenshots

1. Render a modal with the example container.
2. Changing the enabled state from false to true
3. The rightButton should no longer be greyed out and be clickable. However, it remains greyed out and unclickable on Android.

const ExampleContainer = ({ componentId }: Props) => {
const [canJoin, setCanJoin] = useState(false);
useEffect(() => {
    Navigation.mergeOptions(componentId, {
      topBar: {
        rightButtons: [
          {
            id: 'JOIN',
            icon: checkIcon,
            enabled: canJoin,
          },
        ],
      },
    });
  }, [componentId, canJoin]);
return ( <Text>Example</Text> );
}

ExampleContainer.options = (): Options => ({
  topBar: {
    rightButtons: [
      {
        id: 'JOIN',
        icon: checkIcon,
        enabled: false,
      },
    ],
  },
});

---
### Environment
* React Native Navigation version: 6.5.0
* React Native version: 0.61.5
* Platform: Android
* Device info: Samsung S10

**Comment by jinshin1013** [comment] 2020-05-28 08:31
Hi there, I was not able to reproduce this problem on my boilerplate as you can see in the gif below, I am able to toggle `enabled` of the right button. If you could provide a minimal reproduction on Github I could have a look 😄

![navbutton](https://user-images.githubusercontent.com/17612922/83118098-41486180-a111-11ea-86b4-242267701cb0.gif)

**Comment by eliaslecomte** [comment] 2020-05-28 08:52
That looks correct indeed. I'll make a mini project. The view is a modal. Maybe that is the difference?

**Comment by jinshin1013** [comment] 2020-05-28 09:15
@eliaslecomte I also tried to do this on Stacked modal as well but was able to change the `enabled` of the button.

**Comment by jinshin1013** [comment] 2020-05-28 23:02
@eliaslecomte I'm going to close this issue for now as the issue could not be reproduced. Feel free to post a reproduction that I could have a look :)

**Closed by jinshin1013** 2020-05-28 23:02 UTC
Labels: user: waiting for response

**Comment by eliaslecomte** [comment] 2020-06-03 13:54
Hey,

I just created a minimal project to showcase and was able to reproduce it.
Source code is here: https://github.com/eliaslecomte/react-native-navigation-rightbutton-bug.
Could you have a look @jinshin1013 ?

**Comment by eliaslecomte** [comment] 2020-06-03 13:58
After testing with 6.5.0, i've upgraded to 6.7.1 and can confirm, that is indeed fixed.

**Comment by remstos** [comment] 2020-09-08 08:55
If you're seeing this, changing the button id between enabled/disabled state fixed the issue for me.
Issue happened on Android release build only

```
rightButtons:[
  id: `buttonId-${enabled ? 'enabled' : 'disabled'}`,
  text: 'Button',
  enabled,
]
```

**Comment by eliaslecomte** [comment] 2020-09-08 09:28
Or update to 6.7.1+ ;-).
