### ISSUE TITLE
[v4] Screen mounted twice

### ISSUE THREAD

**Issue by p4kaidu** [wix/react-native-navigation#5801] opened 2019-12-22 20:40 UTC
### Issue Description

When I use Navigation.setRoot the first component of children is mounted 2 times (and calls componentDidMount 2 times)

### Steps to Reproduce / Code Snippets / Screenshot

The problem is repeated if you use "Reload" in debug mode
```js 
export const setNonAuth = () => {
    Navigation.setRoot({
        root: {
            bottomTabs: {
                children: [
                {
                    component: {
                    name: 'Main',
                    options: {
                        bottomTab: {
                        fontSize: 12,
                        text: 'Cart',
                        icon: icons.map
                        }
                    }
                    },
                },
                {
                    component: {
                    name: 'Auth',
                    options: {
                        bottomTab: {
                        text: 'Auth',
                        fontSize: 12,
                        icon: icons.key
                        }
                    }
                    },
                },
               ],
            }
          }
    })
    
}
```
---
### Environment
* React Native Navigation version: 4.0.6
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): BlueStacks. Android 6

**Comment by guyca** [comment] 2019-12-24 12:24
@p4kaidu Perhaps `setNonAuth` is called twice. Closing since I can't reproduce

**Closed by guyca** 2019-12-24 12:24 UTC

**Comment by p4kaidu** [comment] 2019-12-24 13:39
I use reload with attached browser for debugging (chrome). 
The function is called only in 1 place
![image](https://user-images.githubusercontent.com/45810834/71415253-dd0a0900-266b-11ea-9892-9b0ddd0c6faf.png)

**Comment by guyca** [comment] 2019-12-25 04:50
hmmm does this happen only on Android?

**Comment by p4kaidu** [comment] 2019-12-30 06:28
Yes
