### ISSUE TITLE
statusbar style does not applying [6.0.1]

### ISSUE THREAD

**Issue by Natteke** [wix/react-native-navigation#5986] opened 2020-03-01 15:26 UTC
### Issue Description

Cant change status on new boilerplate project.
Any workaround or additional steps for installation?

Looks like react-native `<StatusBar/>` works fine, but i think it would be silly to use it with RNN.
Maybe something wrong with link script?

### Steps to Reproduce / Code Snippets / Screenshots
1) react-native init Test
2) yarn add react-native-navigation
3) react-native link react-native-navigation
3.1) cd ios && pod install
4) write code from dock in App.js
4.1) apply light style 
(it also should be light by default actually)
`node_modules/react-native-navigation/lib/src/interfaces/Options.ts:73`
5) react-native start
6) react-native run-ios

![image](https://user-images.githubusercontent.com/24633723/75628300-99da9200-5be8-11ea-9737-ba6e971fdee1.png)

---
### Environment
* React Native Navigation version: 6.0.1
* React Native version: 0.61.5
* Platform(s) (iOS, Android, or both?): IOS
* Device info (Simulator/Device? OS version? Debug/Release?): DEBUG

**Comment by heroic** [comment] 2020-03-02 04:16
@guyca this is happening to me as well.

**Comment by ItsNoHax** [comment] 2020-03-03 08:24
Hi all, this is a duplicate of: https://github.com/wix/react-native-navigation/issues/5797

Going to go ahead and close it for that issue.

**Closed by ItsNoHax** 2020-03-03 08:24 UTC
