### ISSUE TITLE
Crash on Android (NavigationReactEventEmitter on launch)

### ISSUE THREAD

**Issue by SudoPlz** [wix/react-native-navigation#2217] opened 2017-11-24 07:27 UTC
### Issue Description
We received a crash report from one of our **android** user devices while it launched:

### Stacktrace

```
java.lang.NullPointerException
    NavigationReactEventEmitter.java:17 com.reactnativenavigation.bridge.NavigationReactEventEmitter.<init>
    NavigationReactGateway.java:114 com.reactnativenavigation.react.NavigationReactGateway.onReactContextInitialized
    NavigationReactGateway.java:24 com.reactnativenavigation.react.NavigationReactGateway.access$000
    NavigationReactGateway.java:174 com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl.onReactContextInitialized
    ReactInstanceManager.java:900 com.facebook.react.ReactInstanceManager$5.run
    Handler.java:725 android.os.Handler.handleCallback
    Handler.java:92 android.os.Handler.dispatchMessage
    Looper.java:176 android.os.Looper.loop
    ActivityThread.java:5365 android.app.ActivityThread.main
    Method.java:-2 java.lang.reflect.Method.invokeNative
    Method.java:511 java.lang.reflect.Method.invoke
    ZygoteInit.java:1102 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run
    ZygoteInit.java:869 com.android.internal.os.ZygoteInit.main
    NativeStart.java:-2 dalvik.system.NativeStart.main
```

Here's what happened to the device right before the crash:
<img width="493" alt="screen shot 2017-11-24 at 09 23 44" src="https://user-images.githubusercontent.com/3070948/33199486-40f3bb84-d0f9-11e7-81e3-8a41f2276392.png">

---
### Environment

* React Native Navigation version: 1.1.278
* React Native version: 0.49.5
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device (Samsung 	
SM-T110) Android 4.2.2 (API 17)  Release

### Threads:
<img width="629" alt="screen shot 2017-11-24 at 09 24 51" src="https://user-images.githubusercontent.com/3070948/33199593-9a97a27c-d0f9-11e7-96ca-2d5413037611.png">
<img width="865" alt="screen shot 2017-11-24 at 09 25 03" src="https://user-images.githubusercontent.com/3070948/33199596-9dae6de2-d0f9-11e7-947f-1ef7caade06d.png">
<img width="869" alt="screen shot 2017-11-24 at 09 25 16" src="https://user-images.githubusercontent.com/3070948/33199599-a086af5c-d0f9-11e7-98a5-6aec86d95162.png">
<img width="874" alt="screen shot 2017-11-24 at 09 25 27" src="https://user-images.githubusercontent.com/3070948/33199605-a3a819a0-d0f9-11e7-8dbf-db5b1da7931f.png">
<img width="871" alt="screen shot 2017-11-24 at 09 25 38" src="https://user-images.githubusercontent.com/3070948/33199612-aa60997a-d0f9-11e7-86b5-c5e30e767fd5.png">
<img width="874" alt="screen shot 2017-11-24 at 09 25 46" src="https://user-images.githubusercontent.com/3070948/33199616-ad2c0dba-d0f9-11e7-8d25-808c7e633928.png">
<img width="879" alt="screen shot 2017-11-24 at 09 25 56" src="https://user-images.githubusercontent.com/3070948/33199619-afb51b44-d0f9-11e7-86a0-275eb8056555.png">
<img width="885" alt="screen shot 2017-11-24 at 09 26 06" src="https://user-images.githubusercontent.com/3070948/33199622-b1f7965c-d0f9-11e7-85e0-cb8964e1856c.png">
<img width="882" alt="screen shot 2017-11-24 at 09 26 14" src="https://user-images.githubusercontent.com/3070948/33199628-b4888dc2-d0f9-11e7-9fd5-cb79ad71ab77.png">
<img width="906" alt="screen shot 2017-11-24 at 09 26 21" src="https://user-images.githubusercontent.com/3070948/33199633-b6e179c6-d0f9-11e7-8c48-78d320fb5f91.png">

**Comment by pqkluan** [comment] 2017-11-28 02:39
Sorry that I can't get much info from the crash log, but I notice that the device's version is a bit outdated `Android 4.2.2 (API 17)`. 

You could try test the app on another device with the same version to check if it was the cause.

**Comment by SudoPlz** [comment] 2017-11-28 08:20
Hmm, I wish I had a way to reproduce this. That crash came into our crash reporter (bugsnag) so I'm not sure what the user did. I was hoping that you would know.

**Comment by pqkluan** [comment] 2018-01-22 05:00
I'll close this issue for now due to the lack of information. If the problem still exists with the latest version, feel free to re-open.

**Closed by pqkluan** 2018-01-22 05:00 UTC
Labels: Additional info required, Android

**Comment by marcmo** [comment] 2018-03-01 19:29
same as https://github.com/wix/react-native-navigation/issues/2695

**Comment by ossamaweb** [comment] 2018-03-16 13:25
@SudoPlz any updates on this, please?

**Comment by SudoPlz** [comment] 2018-03-16 13:39
@ossamaweb Nope, no news :/

**Comment by ossamaweb** [comment] 2018-03-16 13:52
I think it happens when launching the app from a custom launcher app. I'm getting this:
![](https://i.gyazo.com/f3562304f249123278e6c581412a8f8d.png)

**Comment by SudoPlz** [comment] 2018-03-16 14:50
Custom launcher app? Not sure what that is, but I'm not using anything custom tbh.

**Comment by ossamaweb** [comment] 2018-03-16 15:59
apps like https://play.google.com/store/apps/details?id=com.teslacoilsw.launcher&hl=en

**Comment by SudoPlz** [comment] 2018-03-16 16:41
Oh got it, not sure how I can check that.

**Comment by danielgreane** [comment] 2018-03-19 20:34
@SudoPlz can you confirm you are still using v 1.1.278 ? We are on 1.1.346 and getting a similar report (also caught via bugsnag)

I don't think it's API specific, as we're getting it on a wide range of OSs (see attached)

<img width="1315" alt="screen shot 2018-03-19 at 20 31 25" src="https://user-images.githubusercontent.com/9444927/37620642-bbd3621c-2bb4-11e8-99b7-4c9154c72f25.png">

<img width="1302" alt="screen shot 2018-03-19 at 20 31 33" src="https://user-images.githubusercontent.com/9444927/37620670-cc42e69a-2bb4-11e8-97fd-259d4e30b9e0.png">


We are going to upgrade to the latest version of RNN this week and see if that changes anything (wee are due to anyway). Unfortunately, because this happens randomly when re-launching the app under unknown conditions, is incredibly difficult to reproduce, and we are pretty much relying on bug reports from production where we have enough volume for bug reports

**Comment by SudoPlz** [comment] 2018-03-19 20:39
Yep I was using `1.1.278` when I first saw that issue. I'm now using `1.1.314` and I still get that issue.

**Comment by danielgreane** [comment] 2018-03-19 20:40
@pqkluan are we able to re-open this given that the crash doesn't seem to be isolated to just one API version?
