### ISSUE TITLE
Content of lightbox not displayed

### ISSUE THREAD

**Issue by jay1337** [wix/react-native-navigation#2288] opened 2017-12-05 22:40 UTC
When showing a lightbox (in a single tab app), the content (just a Text component) is randomly displayed (sometimes it is, sometimes not).

The lightbox background is correctly displayed.
The content's functions componentDidMount/render/componentWillUnmount are correctly called.

```
react@16.0.0
react-native@0.50.4
react-native-navigation@1.1.299 (patched with the fix)
Emulator Genymotion Samsung Galaxy S6 - 5.0.0 - API 21 - 1440x2560
build.gradle :
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
```

**Comment by jay1337** [comment] 2018-01-07 10:06
Still an issue with:

```
react@16.0.0
react-native@0.51.0
react-native-navigation@1.1.334
```

**Comment by sijad** [comment] 2018-01-21 10:12
we have same problem

**Comment by jbettcher** [comment] 2018-01-25 21:16
Same issue here - seems about 1 in 4 calls will render the background blur and shading, but not the content of the root view of the lightbox screen.  This seems to be an issue on Android only.  Tapping to dismiss the invisible root view still works.  Going to have to use a modal or something other on Android.

**Comment by sijad** [comment] 2018-01-25 21:23
We didn't experienced this in physical devices, not even official android emulator, we only have this issue in genymotion. Can be related to screen resolution/ratio?

**Comment by jbettcher** [comment] 2018-01-25 21:45
Update here - I was able to get the lightbox to work consistently on Android, at least with my setup (`react-native-navigation@1.1.354`, `Android 8.1.0`, on-device Pixel 2).  The key seemed to be adding the 'adjustSoftInput' key when showing the lightbox:
```
  Navigation.showLightBox({
    screen: ANY_SCREEN_ID,
    style: {
      tapBackgroundToDismiss: true,
      backgroundBlur: 'dark', // 'dark' / 'light' / 'xlight' / 'none' - the type of blur on the background
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
    },
    passProps: {  },
    adjustSoftInput: 'resize',
  });
```
My main activity in the AndroidManifest also has this attribute: `android:windowSoftInputMode="adjustResize"`

**Comment by kibot914** [comment] 2018-01-27 09:07
Facing the same issue here, can anybody fix it ?

**Comment by sijad** [comment] 2018-01-27 09:18
I guess this can be fixed by wrapping your container in a transparent flex container:

```
export default class Alert extends Component {
  render() {
    return (
      <View style={styles.flexContainer}>
        <View style={styles.container}>
          <Text>
            {title}
          </Text>
        </View>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  flexContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    backgroundColor: '#ffffff',
    borderRadius: 5,
    padding: 16,
    justifyContent: 'center',
    width: Math.max(Dimensions.get('window').width * 0.7, 320),
    minHeight: 120,
  },
});
```

could you please test this?

**Comment by kibot914** [comment] 2018-01-27 09:33
Just Try it and it doesn't work

Is it necessary to set the minHeight and width ?


`{
    width: Math.max(Dimensions.get('window').width * 0.7, 320),
    minHeight: 120
}`

**Comment by sijad** [comment] 2018-01-27 09:36
no, you can set those whatever you want, but it's necessary to wrap your container by `flexContainer`.

**Comment by kibot914** [comment] 2018-01-27 09:44
Ya, I have try it but it doesn't work
Anyway thanks

**Comment by sijad** [comment] 2018-01-27 10:15
I was calling `showLightBox` in a `Promise.then()` function, by moving `showLightBox` outside of `then` function I can no longer reproduce this issue, if you're doing same thing could you please check test this too? also make sure `showLightBox` is not wrapped by any `try/catch`.

**Comment by kibot914** [comment] 2018-01-27 10:24
Thanks for reply again.
After double checking, I am pretty sure that I am not putting the `showLightBox`  function inside either `Promise.then()` or `try/catch`

**Comment by kibot914** [comment] 2018-01-27 10:28
Expected Behaviour : With the Loading Indicator ( Hourglass )

<img width="447" alt="screen shot 2018-01-27 at 6 26 21 pm" src="https://user-images.githubusercontent.com/13725006/35471083-bde71172-038f-11e8-96d6-f6af63792b27.png">

Abnormal Behaviour :

<img width="648" alt="screen shot 2018-01-27 at 6 25 19 pm" src="https://user-images.githubusercontent.com/13725006/35471084-be20a482-038f-11e8-8d3a-81de3311d32b.png">

**Comment by jbettcher** [comment] 2018-01-27 18:30
Got a little further on this one.  Whether or not the lightbox shows seems to be related to the operational complexity of the `render()` method of the component.  Very simple `render()` methods that return quickly _prevent_ the lightbox from showing.  More complex, longer to execute (or layout?) `render()` methods cause the lightbox to show predictably.  This explains why I was finding that only production builds were showing the problem - evidently development builds have enough extra processing going on (perhaps through the tcp bridge?) to cause the lightbox to show every time.  Production builds with performance optimizations exhibit the 'no lightbox content' behavior.  It also explains why adding some view wrappers or complicated styles seems to help some folks above (cc @sijad @kibot914 )

So there seems to be some sort of race condition going on.

In my component, my 'loading' state is very simple, and after the component finishes fetching data, it renders a full display.  This 'loading' state was causing the lightbox to not appear, by being so quick to render.  I can add a little bit of arbitrary complexity, and get the lightbox to show every time on my Pixel 2, production build:
```
const STYLES = StyleSheet.create({
  rootContainer: {
    width: windowDimensions.width * 0.85,
    backgroundColor: 'white',
    padding: 30,
    borderRadius: 5,
    ...Platform.select({
      android: {
        // Android does not seem to compute the height correctly using flex
        height: 335,
      },
    }),
  },
})
```
```
  _operationalComplexity() {
    for (let i = 0; i < 500; i += 1) {
      md5(`message${i}`);
    }
  }

  render() {
    if (this.state.loading) {
      this._operationalComplexity();
    }

    return (
      <View style={STYLES.rootContainer}>
        {this.state.loading ? this._showLoading() : this._showFullComponent()}
      </View>
    );
  }
```

Obviously, this isn't great in terms of a real fix since the arbitrary 'complexity' depends on device characteristics.  I'll keep looking into the internals of the rendering on the lightbox.

**Comment by jbettcher** [comment] 2018-01-27 22:17
Well, I'm about as far as I can get with my debugging skills without knowing more about React Native/ React Native Navigation.  It looks like when things go wrong, the measured dimensions for the ContentView owned by the LightBox are 0.  I've added some logging here in onMeasure in ContentView.java:
```
    @Override
    protected void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int widthSpec = MeasureSpec.makeMeasureSpec(MeasureSpec.getSize(widthMeasureSpec), MeasureSpec.AT_MOST);
        int heightSpec = MeasureSpec.makeMeasureSpec(MeasureSpec.getSize(heightMeasureSpec), MeasureSpec.AT_MOST);

        super.onMeasure(widthSpec, heightSpec);

        final int measuredHeight = viewMeasurer.getMeasuredHeight(heightSpec);
        final int measuredWidth = viewMeasurer.getMeasuredWidth(widthSpec);
        Log.d("ReactNative", "Measured dimensions for " + this.screenId + ": (" + measuredWidth + "," + measuredHeight + ")");
        setMeasuredDimension(measuredWidth, measuredHeight);
    }
```
The 'good' lightbox displays show measured dimensions of (1080,1794), while the instances where the lightbox content fails to display show measurements of (0,1794) and (0,0).

**Comment by kibot914** [comment] 2018-01-28 05:14
@jbettcher Thanks for your work man.
So can we fix this by simply setting the width and height of the lightbox in javascript level ?
Or do we have to fix it in ContentView.java ? Say setting a specific `measuredHeight` and `measuredWidth` in ContentView.java

**Comment by jbettcher** [comment] 2018-01-28 17:36
I've tried several javascript-level fixes like you describe @kibot914.  Unfortunately, this is an issue in the android UI layer.  From what I can tell there's a race at times between the creation of the react ContentView that holds the screen component and the onDisplayListener for that content.  When things go bad, the onDisplayListener seems to fire before the ContentView has created the components.  It takes a measurement ([here](https://github.com/wix/react-native-navigation/blob/master/android/app/src/main/java/com/reactnativenavigation/views/LightBox.java#L73)) and one of those (width, height) numbers comes back 0.  The animateShow then happens on content with a zero width or height, resulting in no content being shown. 

I'm trying to figure out why it needs to make this measurement at all.  Seems to me the content size should be bounded by the display area of the screen and not the child content measurements, but there's probably stuff I'm missing.

**Comment by jbettcher** [comment] 2018-01-28 19:43
Here's a potential fix for this one: jbettcher/react-native-navigation@0b01bb97ad0de049cb4b35349bea871837534158.  It uses an android view tree observer/global layout listener instead of the react onDisplayListener, and holds off on the animation until both the child content screen is present, and its height/width are non-zero.

Obligatory "I have no idea what I'm doing" caveat, but it seems to work well for my use cases.  I'll do more testing with this one tomorrow.

**Comment by wwwdata** [comment] 2018-02-01 14:05
@jbettcher I can confirm the fix is working. This needs to be in a future release 👍

**Comment by jbettcher** [comment] 2018-02-02 20:06
Cool, glad this is working for folks.  It fixed the issues I was having as well, and I haven't found any problems in production.

Happy to submit a PR - Not sure what the project maintainers have as far as recommendations for that go, but I'll start with the request and go from there.

**Comment by guyca** [comment] 2018-02-06 13:12
@jbettcher Thanks for looking into this. I hope 90b47f7910a9631a881ea250545028cb48daf9b3 will fix this, would appreciate if someone can confirm, thanks.

**Comment by mmccartney** [comment] 2018-02-07 05:36
@guyca I too was seeing this problem and just tried 1.1.370 and still reproduced it.  I am displaying the lightbox in response to a `TouchableOpacity.onPress`.  It took about 6 tries but it still eventually failed.  On the bright side, I think the Android lightbox support is better than in 1.1.348 (my previous version)...

In my test case, it is a tab-based app, select 3rd tab, click that shows a modal, click on the modal to display the lightbox.  When it fails, the entire screen is greyed out.

hope this helps,
Mike

**Comment by ODelibalta** [comment] 2018-02-12 00:09
I am having the same issue after the update. Although it definitely has gotten better, it still happens. Particularly when I try to open the lightbox from a side menu row item press. I sometime have to ask for passcode input and I use a lightbox for that. When I want to navigate from the side menu item and lightbox is supposed to show up, all I see is dark overlay. I am on Android emulator Nexus 5X API 23:5554

**Comment by danielang** [comment] 2018-02-15 08:44
@guyca The fix you mentioned doesn't seems to work as supposed. 
45% of the `showLightBox` reders the content correct like this: 
![img_20180215_093403](https://user-images.githubusercontent.com/6752808/36247492-8810ab68-1234-11e8-9846-25ab367951bf.png)

But 45% of the time I got this: 
![img_20180215_093339](https://user-images.githubusercontent.com/6752808/36247527-a2c1d3ec-1234-11e8-91b6-a88c344a773c.png)

And sometimes this: 
![img_20180215_093321](https://user-images.githubusercontent.com/6752808/36247538-af3024c6-1234-11e8-9494-8304c4eeed3b.png)

**Comment by ilovett** [comment] 2018-02-22 00:43
I am on lightbox `"version": "1.1.382"` and still seeing this issue where content doesn't render but backdrop does (sometimes).

**Comment by ComputerWolf** [comment] 2018-02-25 02:53
I am seeing a similar issue with rendering modals where only sometimes the width is reported as 0 and causes weird layout issues. Hopefully a fix can be found across both types of screens.

**Comment by iosandroidwebtopdev** [comment] 2018-03-12 17:58
Still no solution for this?

**Comment by heiheiLqq** [comment] 2018-03-13 09:48
Will there be a good solution now?

**Comment by jbettcher** [comment] 2018-03-13 15:19
Just merged upstream@1.1.407 into [my fork](https://github.com/jbettcher/react-native-navigation); seems to work fine if folks are using that to fix the bug here.  I'm just using the forked version directly with `npm install github:jbettcher/react-native-navigation`

**Comment by ilovett** [comment] 2018-03-23 22:42
Just curious, has anyone tried setting a minimum width & height on the modal content?

**Comment by AdnanRibic** [comment] 2018-04-16 15:05
@jbettcher Tried you fix and it worked. Great job! I am just wondering does the 'tapBackgroundToDismiss' work fo you?

**Comment by doublex** [comment] 2018-04-26 08:48
+1
This patch fixes this issue:
https://github.com/jbettcher/react-native-navigation/commit/0b01bb97ad0de049cb4b35349bea871837534158

**Comment by pqkluan** [comment] 2018-06-07 02:40
The pull request for this issue has was merged.

**Closed by pqkluan** 2018-06-07 02:40 UTC
Labels: platform: Android, v1

**Comment by Seemapadiya** [comment] 2018-08-28 11:33
@jbettcher use your class solve the blank screen but now some time popup not show using showLightBox, i don't know what the issues is but i tried everything but still getting this error , could you please help me to resolve this

**Comment by chrisehlee** [comment] 2018-10-16 10:00
Hi, i'm having
 
```javascript
"react-native-navigation": "^1.1.485",
"react-native": "0.53.3",
```

I have varying visual results in iOS and Android (the iOS showLightBox is a bit messed up). Screenshots attached below
![frame](https://user-images.githubusercontent.com/12748310/47008714-b892d280-d132-11e8-8951-9d13b823319b.png)
