### ISSUE TITLE
Setting a subtitle narrows title space in nav-bar

### ISSUE THREAD

**Issue by d4vidi** [wix/react-native-navigation#1993] opened 2017-10-09 11:39 UTC
### Issue Description

Setting a screen's **subtitle** reduces the width available for the **title** in the `TitleBar`. Thus, if a screen is pushed with a title and then a subtitle is set (i.e. using `navigator.setSubtitle()`), the title gets trimmed down. I believe the newly available width is the one being held by the subtitle's.

Note: this doesn't always happen; seem to happen with short titles more than long ones for whatever reason.

### Steps to Reproduce / Code Snippets / Screenshots

Runtime video: https://slack-files.com/T02T01M9Y-F7F9CRMA7-4b25f7f753

---
### Environment
* React Native Navigation version: Any
* React Native version: 0.44
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): iOS 11 Simulator

**Comment by ropilz** [comment] 2017-10-31 23:49
Any workaround for this?

**Comment by d4vidi** [comment] 2017-11-02 13:19
@ropilz This could turn out to be a nonissue. We're checking.

**Comment by brunolemos** [comment] 2017-12-16 23:52
I can confirm this is a bug.

<div>
<img width="320" alt="image" src="https://user-images.githubusercontent.com/619186/34075334-2066c3b6-e2ab-11e7-80ba-79f29ab14c5a.png">

<img width="320" alt="image" src="https://user-images.githubusercontent.com/619186/34075336-27dd1a46-e2ab-11e7-96dc-e98e461153bb.png">
</div>


cc @guyca

**Comment by mobitar** [comment] 2018-01-03 17:19
The solution is to modify `RCCTitleViewHelper` [line 84](https://github.com/wix/react-native-navigation/blob/master/ios/Helpers/RCCTitleViewHelper.m#L84) 

from:

``` objective-c
self.titleView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin;
```

to:

``` objective-c
self.titleView.autoresizingMask = UIViewAutoresizingFlexibleLeftMargin | UIViewAutoresizingFlexibleRightMargin;
```

(remove `UIViewAutoresizingFlexibleWidth`)

I believe this makes sense since we rely on manual and size-to-fit measurements to appropriately size the titleView according to the bounds, so there's no need for autoresizing to handle width and overwrite what we may have manually set.

(For the record, this issue only occurs if the subtitle text is shorter than the title text.)

**Comment by yogevbd** [comment] 2018-01-22 14:00
Resolved in https://github.com/wix/react-native-navigation/commit/f6d2c334c3defc6bf0851b4182b5bfd860b470eb

**Closed by yogevbd** 2018-01-22 14:00 UTC
Labels: Bug - iOS
