### ISSUE TITLE
TopBar icon button padding

### ISSUE THREAD

**Issue by alpha0010** [wix/react-native-navigation#6779] opened 2020-11-19 15:14 UTC
## 🚀 Feature

Adding padding to the hit target icon buttons in the TopBar.  This could either be a fixed amount (e.g. always pad until icon is at least X-by-X), or a configurable parameter.

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes.

## Motivation

Using `react-native-vector-icons` `Icon.getImageSource()`, sizing the icon to look visually correct results in difficulty pressing.  This is due to a small hit box.

## Pitch

It is possible to work around this hit box issue by using a custom component.  However, custom components take more time to configure (and wire your own event handler) than just being able to pass `{id: 'myID', icon: ...}`.  Also, it is harder to get native feel (e.g. ripple on Android), since the whole button must be simulated.

It is possible to work around by using images padded with transparent pixels (effectively larger, though not visually larger).  This is not really possible when working with `react-native-vector-icons` (a common case, I believe), since padding is defined at the font level.

**Comment by danilobuerger** [comment] 2020-11-20 20:36
Duplicate of #5000

**Closed by danilobuerger** 2020-11-20 20:36 UTC
Labels: needs triage, triage: enhancement
