### ISSUE TITLE
v2 archive fails with `'ReactNativeNavigation/ReactNativeNavigation.h' file not found`

### ISSUE THREAD

**Issue by tim-dev** [wix/react-native-navigation#1933] opened 2017-09-27 02:46 UTC
### Issue Description

Everything works fine in the simulator, but when trying to archive I'm getting an error on line

`#import <ReactNativeNavigation/ReactNativeNavigation.h>`

that reads `'ReactNativeNavigation/ReactNativeNavigation.h' file not found.`

---
### Environment
* React Native Navigation version: v2
* React Native version: 0.48.3
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Generic iOS Device, Debug or Release scheme

My header search paths contain
`$(SRCROOT)/../node_modules/react-native-navigation/lib/ios` recursive

`libReactNativeNavigation.a` is under "Link Binary With Libraries"

**Comment by bogobogo** [comment] 2017-09-27 20:25
Hey @tim-dev,
I will look into it tomorrow. I will let you know if I find the cause or need more information.

**Comment by itsyogesh** [comment] 2017-09-29 15:57
Hi @tim-dev 
I think your header search path should contain 
`$(SRCROOT)/../node_modules/react-native-navigation/ios` - you have an extra `lib` in your example. 
Also, clean the project once you have changed it, that's how I got it working.

**Comment by tim-dev** [comment] 2017-09-29 18:11
v2 has moved the `ios` directory to within a new `lib` directory.  v1 worked as you described, but when I moved to v2 it wasn't working in the simulator and I had to change the header search path.

**Comment by itsyogesh** [comment] 2017-09-29 18:19
@tim-dev Are you using RNN in a new project or are you working with the `playground` app ?

**Comment by tim-dev** [comment] 2017-09-29 19:36
It's a new project.  I was having trouble using `react-native-git-upgrade` so I created a new project at 0.48.3 and used yarn to install all my dependencies.

**Comment by tim-dev** [comment] 2017-10-02 20:11
I put together a tiny test version of this and got the same error.  Attached for reference.
[testnav.tar.gz](https://github.com/wix/react-native-navigation/files/1350240/testnav.tar.gz)

**Comment by tim-dev** [comment] 2017-10-04 19:51
@itsyogesh I know you guys have a lot going on, but have you had a chance to check out my test project? I'd love to know if it's just my environment or if it's actually a real issue.

**Comment by tim-dev** [comment] 2017-10-09 19:12
@bogobogo @itsyogesh is there anything I can do to help with this stuff? I'm not terribly familiar with iOS stuff, and I tried some searches to see if I could uncover anything but I came up empty.  If you have an idea what might be wrong I could take a swing at fixing it myself and creating a pull request.

**Comment by michael-gillett** [comment] 2017-10-20 06:48
I am currently facing the same problem as @tim-dev

**Comment by DanielZlotin** [comment] 2017-10-30 09:48
Our current playground app using RN44, any chance one of you checks the archive step on it so we can zoom in on the problem?

**Comment by michael-gillett** [comment] 2017-10-30 20:31
I was able to fix the problem by changing the import inside of AppDelegate.m from
`#import <ReactNativeNavigation/ReactNativeNavigation.h>` (specified in the install instructions) to `#import "ReactNativeNavigation.h"`

This is on react native 0.49.3, react 16.0.0-beta.5 and react-native-navigation 2.0.2010ish

**Comment by Dexwell** [comment] 2018-01-20 12:38
Still no fix for this? Would like to start using v2 now in order to avoid refactoring later.

**Closed** 2018-03-21 14:26 UTC
Labels: Bug - iOS, v2

**Comment by viotti** [comment] 2018-03-23 14:13
Same here. Setting the headers search path to `$(SRCROOT)/../node_modules/react-native-navigation/lib/ios` and changing the import on `AppDelegate.m` to `#import "ReactNativeNavigation.h"` does indeed fix the archive error.

React 16.2.0, React Native 0.53, React Native Navigation 2.0.2180, and Xcode 9.2.

**Comment by KylePalko** [comment] 2018-06-26 20:32
I also had to Product > Clean the project to get it to properly build 👍🏻

**Comment by gopal052** [comment] 2018-12-07 13:38
i am also getting the same issue

**Comment by aolowude** [comment] 2018-12-18 05:33
@gopal052 For you and whoever else may still be having this problem, I fixed it by:

1. Uninstalling react-native-navigation:
npm remove react-native-navigation

2. Reinstalling the latest version:
npm install --save react-native-navigation

- At this point, if you look in the **"node_modules>react-native-navigation"** folder you should see a **lib** folder which ensures it is the latest version.

3. Under your Target - Build Settings - Header Search Paths, add:
$(SRCROOT)/../node_modules/react-native-navigation/lib/ios

4. Now go ahead and repeat the steps from their site:
https://wix.github.io/react-native-navigation/#/docs/Installing?id=ios

Everything should line up.

**Comment by eran-or** [comment] 2018-12-18 12:06
In my case it was just to rebuild the project after add the library.

**Comment by ialmoqren** [comment] 2018-12-27 21:04
The error disappeared when I changed the destination simulator
(I think) it is because Xcode started the indexing again

**Comment by hamyarbaiat** [comment] 2019-01-16 23:12
it usually happens when there is a conflict between added libs

**Comment by hamyarbaiat** [comment] 2019-01-16 23:13
check out build phases libs , make sure only the main libreactnativenavigation.a is added

**Comment by habibalamin** [comment] 2019-05-11 21:38
I started experiencing this issue after upgrading React Native Navigation from `2.1.3` to `2.18.4`. I could build in Xcode (IIRC), but definitely not through `react-native run-ios`.

I can reliably fix this by checking out the commit right before the upgrade, clearing `node_modules` and `ios/build`, and rebuilding from scratch, then reliably reproduce it by doing the same after checking out the upgrade commit.

After the upgrade, I'm forced to change the RNN iOS import from the form

```objective-c
#import <ReactNativeNavigation/ReactNativeNavigation.h>
```

to

```objective-c
#import "ReactNativeNavigation.h"
```

(and relink, but that's expected)

I'm not sure what the difference is, and I'm uncomfortable with this, as the installation instructions use the first form. Also, the fact that this bug has been around for a while (since before either version, I believe; I'll double check some time), yet I only get it after my upgrade, also makes me uncomfortable, as I can't make sense of it.

**Comment by jsancho** [comment] 2019-06-10 22:57
> @gopal052 For you and whoever else may still be having this problem, I fixed it by:
...
> 1. Under your Target - Build Settings - Header Search Paths, add:
>    $(SRCROOT)/../node_modules/react-native-navigation/lib/ios
> 2. Now go ahead and repeat the steps from their site:
>    https://wix.github.io/react-native-navigation/#/docs/Installing?id=ios
> 

I have just done a fresh install of RNN 2.21.0 on RN 0.59.9

Add the `Header Search Paths` was the key. 
Unless I'm missing something this should be part of the standard installation instructions

**Comment by habibalamin** [comment] 2019-06-20 04:13
Oh, I should probably explain: I avoided @gopal052's method, because opening Xcode always seems to produce a whole bunch of unrelated changes to the `xcodeproj` file, just inconsequential things like reordering some lines for no reason, but it dirties up diffs.

This generally happens after I run a `react-native link`. Opening Xcode after that seems to always screw up my `xcodeproj`. For that reason, I generally don't like making React Native changes through Xcode.

I believe that header search path is supposed to be added for you when you link RNN, anyway.

**Comment by tumanov-alex** [comment] 2019-07-18 13:29
I'm having the same issue. Unfortunately, none of the above solutions helped me. _**Please like this comment if they didn't work for you either. We need more attention on this**_

Besides all the above, I've also tried the next solutions:
- _react-native-git-upgrade_
- _react-native link react-native-navigation_
- cleaning npm's cache
- cleaning Derived Data
- cleaning _~/.rncache/_
- _pod install_
- _cd node_modules/react-native/scripts && ./ios-install-third-party.sh_
- editing import to be: _#import <ReactNativeNavigation.h>_

### Environment
* React Native Navigation version: 3.0.0-alpha.3 / 2.22.3 / 2.10.0
* React Native version: 0.60.3
* Platform: IOS
* Device info: Simulator — iPhone 6 (12.1), Device — iPhone 8 (12.3.1). Both in Debug mode.

**Comment by aniciom** [comment] 2019-07-26 23:03
Got a hard time trying to install the alpha-8 on iOS for those whose are getting the .h's not found issue, make a fresh install from 0 (in my case i'm using react native 0.60.4), follow the installation guide but its not needed to modify the search header path, just remember to open the .xcworkspace file replace the AppDelegate.m, modify the .h, don't add the project as library into Xcode, just link the library using the react-native cli and get into the ios react's native folder and do pod install, after that go to xcode clean the compilation and try again. that worked for me.
