### ISSUE TITLE
Android targetSdkVersion 30 breaks overlay style

### ISSUE THREAD

**Issue by AGreenPlace** [wix/react-native-navigation#7225] opened 2021-08-20 21:46 UTC
## 🐛 Bug Report

When targeting Android sdk version 30 some overlays that should be shown in full screen are not. 

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes, I've read the guidelines. 

## To Reproduce

1. Clone the react-native-navigation repo `git clone https://github.com/wix/react-native-navigation.git`
2. Go to the cloned folder and install dependencies `cd react-native-navigation && npm install --legacy-peer-deps`
3. Start the packager `npm run start`
4. Open the playground android app in Android studio
5. Change the `targetSdkVersion` and `compileSdkVersion` to `30` in the `./playground/android/app/build.gradle` file
6. Build and run the playground app
7. Go to the `Navigation` tab
8. Press the `Overlay` button
9. Press the `Alert` button
10. Alert and backdrop are displayed offset by about 44-45px from the top

## Expected behavior

Alert and backdrop should be correctly centred.

## Actual Behavior

Alert and backdrop are offset by about 44-45px from the top

![Screenshot 2021-08-20 at 23 14 28](https://user-images.githubusercontent.com/12028990/130294005-8dbf91bf-a539-4db7-8e4b-cfba7e1deefc.png)

## Your Environment

Issue appears only when targeting sdk 30, sdk 29 works as intended.

![Screenshot 2021-08-20 at 22 08 40](https://user-images.githubusercontent.com/12028990/130295056-d386b661-0c9e-49f9-8c6c-f97b88c8a6b8.png)

The issue also appears in modals but I've not been able to reproduce it in the playground app.  
In our own project the following code shows a broken modal (same 44-45px offset):
```typescript
Navigation.showModal({
  component: {
    name: 'componentName',
  }
})
```
While the following code correctly shows the modal:
```typescript
Navigation.showModal({
  stack: {
    children: [
      {
        component: {
          name: 'componentName',
        },
      },
    ],
  },
})
```

I wasn't able to find any workaround for the overlays.  

- React Native Navigation version: 7.18.0
- React Native version: 0.63.2
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Pixel4XLAPI30 simulator in Debug

## Reproducible Demo

React-Native-Navigation playground app is presenting the issue

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️  &nbsp; Yes, I have the time, and I know how to start.
 - ✅  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 - ✖️  &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by swabbass** [comment] 2021-08-22 09:06
@AGreenPlace thanks for your sharp eyes, good catch, If upgrading for android 30 gonna break some stuff then we gonna include this change in `v8`, I don't think so but in case, I'm gonna debug that and see what really happens :]

**Comment by AGreenPlace** [comment] 2021-08-22 15:45
Hey @swabbass, thanks for the quick response, let me know if I can do anything to help.

**Comment by geroale** [comment] 2021-08-28 10:17
Same issue here

**Comment by marf** [comment] 2021-08-28 10:17
Hey, we have the same issues and cannot update a new app. Do you know some workaround to solve this pixel offset issue for overlays?

Thank you!

**Comment by Jtavani** [comment] 2021-08-28 13:48
I've got the same issue

**Comment by jeremybarbet** [comment] 2021-08-29 10:06
I was able to make it work with the following config:

```diff
Navigation.showOverlay({
  component: {
    name: 'example.Overlay',
    options: {
      ...
      statusBar: {
+       drawBehind: true,
      },
    },
  },
});
```

**Comment by AGreenPlace** [comment] 2021-08-30 15:18
Writing here to confirm that this is still happening on `7.19.0`.

@jeremybarbet be careful that this will fix the issue only on devices running SDK 30 (Android 11) but will result in a broken interface in lower versions (attaching screenshots), you should only set `drawBehind: true` when `Platform.OS === 'android' && Platform.Version >= 30`, thanks for the workaround though.

![photo_2021-08-30 17 07 32](https://user-images.githubusercontent.com/12028990/131361664-7c42b56f-23fe-49fb-a24a-9ba0969e804a.jpeg) 
![photo_2021-08-30 17 07 35](https://user-images.githubusercontent.com/12028990/131361756-7796868f-4158-4b99-ab45-bfe3a62d034d.jpeg)

@swabbass bear in mind that this issue will affect all new apps since Google forces you to target sdk 30 for all new apps since August 2021 and will affect all new app updates from November 2021 for the same reason.

**Comment by N3TC4T** [comment] 2021-10-06 12:02
Today I spend sometime to find a solution for this issue and I came up with a patch, haven't test it completely but looks like working on both SDK <= 29 and 30

```
diff --git a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
index 3117dcc..863f7cd 100644
--- a/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
+++ b/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
@@ -139,7 +139,7 @@ public class ComponentViewController extends ChildController<ComponentLayout> {
     protected WindowInsetsCompat applyWindowInsets(ViewController<?> view, WindowInsetsCompat insets) {
         ViewCompat.onApplyWindowInsets(view.getView(), insets.replaceSystemWindowInsets(
                 insets.getSystemWindowInsetLeft(),
-                insets.getSystemWindowInsetTop(),
+                Math.max(insets.getSystemWindowInsetTop() - getTopInset(), 0),
                 insets.getSystemWindowInsetRight(),
                 Math.max(insets.getSystemWindowInsetBottom() - getBottomInset(), 0)
         ));
```

**Comment by tarouboy** [comment] 2021-11-03 02:40
Seems it also happens when showModal with `modalPresentationStyle: "overCurrentContext"` and layout's backgroundColor is transparent.

**Comment by BlackCat1397** [comment] 2021-11-04 16:25
@swabbass
As I found out the issue is that with target SDK 30 proper window insets are applied - with inset for `StatusBar` and React Native Navigation also adds inset for `StatusBar` by itself.
Prior to target SDK 30 `insets.getSystemWindowInsetTop()` in `ComponentViewController.applyWindowInsets` is always 0.

Therefore there with fix suggested by @N3TC4T `ComponentViewController` always has inset for `StatusBar` even if we specify `drawBehind: true` - you can check with transparent `StatusBar` and fullscreen overlay - it's not drawn under status bar opposed to target SDK 29.

I suggest to use `insets.getSystemWindowInsetTop()` if target SDK >= 30 and do not `applyTopInsets`.

```
diff --git a/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java b/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
index 3117dcc53..9fca70f57 100644
--- a/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
+++ b/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/component/ComponentViewController.java
@@ -121,7 +121,8 @@ public class ComponentViewController extends ChildController<ComponentLayout> {
 
     @Override
     public void applyTopInset() {
-        if (view != null) presenter.applyTopInsets(view, getTopInset());
+        if (getActivity().getApplicationContext().getApplicationInfo().targetSdkVersion < 30 && view != null)
+            presenter.applyTopInsets(view, getTopInset());
     }
 
     @Override
@@ -139,7 +140,9 @@ public class ComponentViewController extends ChildController<ComponentLayout> {
     protected WindowInsetsCompat applyWindowInsets(ViewController<?> view, WindowInsetsCompat insets) {
         ViewCompat.onApplyWindowInsets(view.getView(), insets.replaceSystemWindowInsets(
                 insets.getSystemWindowInsetLeft(),
-                insets.getSystemWindowInsetTop(),
+                getActivity().getApplicationContext().getApplicationInfo().targetSdkVersion >= 30
+                    && resolveCurrentOptions(presenter.defaultOptions).statusBar.isHiddenOrDrawBehind()
+                    ? 0 : insets.getSystemWindowInsetTop(),
                 insets.getSystemWindowInsetRight(),
                 Math.max(insets.getSystemWindowInsetBottom() - getBottomInset(), 0)
         ));
```

**Comment by swabbass** [comment] 2021-11-08 12:39
> getSystemWindowInsetTop

Thanks for the insights, appreciated it, on RN66 we already upgraded android to 30 SDK, and soon it will be merged with master and a new [PR](https://github.com/wix/react-native-navigation/compare/RN66...RN66_android_fixes?expand=1) will have native android changes and fixed and this will be considered.

**Closed** 2021-11-30 06:55 UTC
Labels: platform: Android, needs triage, triage: bug

**Comment by N3TC4T** [comment] 2021-12-14 10:16
@swabbass With this changes which is already in the latest version `7.24.1`, the views on Android will push up when keyboard appears, the `windowSoftInputMode` is set to `adjustNothing`. tested on Android 11.

**Comment by swabbass** [comment] 2021-12-14 11:34
@N3TC4T can you please create new issue, about soft input modes?
