### ISSUE TITLE
Getting error "android.view.WindowLeaked: Activity com.reactnativenavigation.controllers.NavigationActivity has leaked window DecorView@aea427b[] that was originally added here"

### ISSUE THREAD

**Issue by saxenanickk** [wix/react-native-navigation#1819] opened 2017-09-09 15:45 UTC
### Issue Description

I am getting this error at the start of the application. It requires restart of the application. After restarting rest goes fine.
![screen shot 2017-09-09 at 9 11 18 pm](https://user-images.githubusercontent.com/24573714/30241578-a7c1f98e-95a3-11e7-9ddb-4d60c32cd0e5.png)

---
### Environment
* React Native Navigation version: 1.1.41
* React Native version: 0.45.1
* Platform(s) (iOS, Android, or both?): Android (Currently)
* Device info (Simulator/Device? OS version? Debug/Release?): Device

**Comment by guyca** [comment] 2017-09-11 11:06
Hey there,
Can you please describe the use case which leads to this issue?

**Comment by saxenanickk** [comment] 2017-09-12 11:42
@guyca Hey there, 
Whenever I start my application I got this error. And it requires a restart. After restarting this has two cases: 
- Everything goes fine in application.
- Even after restart I got the same error.

Sometimes it does this for a very long time.

**Comment by tannerhallman** [comment] 2017-10-31 14:44
I am getting this error when I am using RN-Navigation alongside react-native-image-picker. When it prompts the dialog to pick an image, if I click on either of the buttons the app crashes with this same error.

![screenshot_20171031-103657](https://user-images.githubusercontent.com/10327491/32229838-249cf970-be28-11e7-8657-b6f0eef04d62.png)
![screenshot_20171031-103708](https://user-images.githubusercontent.com/10327491/32229840-2533461e-be28-11e7-81bc-34ace4250b54.png)
![screenshot_20171031-103745](https://user-images.githubusercontent.com/10327491/32229841-25ce2bde-be28-11e7-91de-8c029f11e612.png)

`10-31 10:37:41.871 11659-11659/com.myapp.app E/WindowManager: android.view.WindowLeaked: Activity com.reactnativenavigation.controllers.NavigationActivity has leaked window DecorView@c74fed7[] that was originally added here
                                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                    at android.app.Dialog.show(Dialog.java:330)
                                                                    at com.imagepicker.ImagePickerModule.showImagePicker(ImagePickerModule.java:196)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
                                                                    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
                                                                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                    at android.os.Handler.handleCallback(Handler.java:789)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                    at java.lang.Thread.run(Thread.java:764)
`

**Comment by tannerhallman** [comment] 2017-10-31 14:44
I am getting this error when I am using RN-Navigation alongside react-native-image-picker. When it prompts the dialog to pick an image, if I click on either of the buttons the app crashes with this same error.

![screenshot_20171031-103657](https://user-images.githubusercontent.com/10327491/32229838-249cf970-be28-11e7-8657-b6f0eef04d62.png)
![screenshot_20171031-103708](https://user-images.githubusercontent.com/10327491/32229840-2533461e-be28-11e7-81bc-34ace4250b54.png)
![Uploading Screenshot_20171031-103745.png…]()

`10-31 10:37:41.871 11659-11659/com.myapp.app E/WindowManager: android.view.WindowLeaked: Activity com.reactnativenavigation.controllers.NavigationActivity has leaked window DecorView@c74fed7[] that was originally added here
                                                                    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
                                                                    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
                                                                    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:92)
                                                                    at android.app.Dialog.show(Dialog.java:330)
                                                                    at com.imagepicker.ImagePickerModule.showImagePicker(ImagePickerModule.java:196)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)
                                                                    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)
                                                                    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                    at android.os.Handler.handleCallback(Handler.java:789)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
                                                                    at java.lang.Thread.run(Thread.java:764)
`

**Comment by nimamyscreen** [comment] 2017-11-14 04:55
@tannerhallman Did u find any solution?

**Comment by buffaly** [comment] 2017-11-19 18:41
Maybe relate with #2191

**Comment by doananh234** [comment] 2017-12-20 03:22
step to use react-native-image-picker with RNN:

1. open NavigationActivity.java (react-native-navigation).
2. implements OnImagePickerPermissionsCallback.
3. use android studio to fix import issue.
4. overwrite:
    @Override
    public void setPermissionListener(@NonNull PermissionListener listener) {
        mPermissionListener = listener;
    }

It work with me. goodluck for you!

**Comment by aemdy** [comment] 2018-01-04 16:36
Thank you! @doananh234 solution worked for me!

**Comment by stefanedberg** [comment] 2018-01-16 13:50
I'm having the exact same problem with RNN and react-native-image-picker. For me Android Studio doesn't seem to be able to resolve OnImagePickerPermissionsCallback when adding as implementation in NavigationActivitiy.java. Any ideas?

react-native 0.51.0
react-native-navigation 1.1.342
react-native-image-picker 0.26.7

**Comment by tannerhallman** [comment] 2018-02-23 20:04
So what I had to do is actually request the permissions a screen before the image picker is shown so that you don't run into that when you try to launch the picker.

**Comment by stefanedberg** [comment] 2018-02-23 20:41
@tannerhallman Already did that but crashes anyway. Although there is a pull request for react-native-image-picker that seems to solve this problem. Just tested and it works for me.

https://github.com/react-community/react-native-image-picker/pull/761

**Comment by paulbargaoanu** [comment] 2018-05-01 17:36
To anyone still facing this issue because of using react-native-image-picker, I can confirm that @stefanedberg 's comment above fixes the issue. You just have to slightly modify a file within the ImagePicker module.

**Comment by guyca** [comment] 2018-05-02 06:18
I'm closing as it seems the issue is caused by faulty integration between the two libraries. If anyone would like to write a small integration guide for future users [here](https://wix.github.io/react-native-navigation/#/third-party-libraries-support) that would be nice 👍

**Closed by guyca** 2018-05-02 06:18 UTC
Labels: Additional info required
