### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR) On Android dismissModal

### ISSUE THREAD

**Issue by aminosman** [wix/react-native-navigation#5702] opened 2019-12-01 04:54 UTC
### Issue Description

Getting this error when I dismiss a modal on Android. Cant really get to the bottom of this from the trace. Everything seems to work If I debug and slow the navigation events down. Without a breakpoint in `private void emit(String eventName, WritableMap data)` app crashes. Worth noting this started happening after upgrading to V3 and seems to happen in V4 too. Tried going back to V2 but it seems to not play well with RN 0.61. I have tried different JSC 225067 and 245459 as recommended by https://github.com/wix/react-native-navigation/issues/4978 and https://github.com/react-native-community/jsc-android-buildscripts/issues/84.

Just found that disabling hardware acceleration has resolved my issue:
`android:hardwareAccelerated="false"`

 Will update as I gather more info as I continue digging.

### Steps to Reproduce / Code Snippets / Screenshots
> 2019-11-30 23:47:12.858 17373-17373/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2019-11-30 23:47:12.858 17373-17373/? A/DEBUG: Build fingerprint: 'google/sdk_gphone_x86/generic_x86:9/PSR1.180720.093/5456446:userdebug/dev-keys'
2019-11-30 23:47:12.858 17373-17373/? A/DEBUG: Revision: '0'
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG: ABI: 'x86'
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG: pid: 17143, tid: 17235, name: RenderThread  >>> com.minderapps.minder <<<
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1c
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG: Cause: null pointer dereference
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG:     eax e3d30740  ebx ebf5e4a0  ecx ebf4e94c  edx 00000002
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG:     edi edbf9d9c  esi 00000000
2019-11-30 23:47:12.859 17373-17373/? A/DEBUG:     ebp cb6ec968  esp cb6ec950  eip ebcd2eea
2019-11-30 23:47:12.865 2409-2781/com.google.android.dialer I/Dialer: SpamAsyncTaskUtil.getAndUpdateServerSpamList - request:a: "us"
    b: 231341
    c: 231341
    d: 1575159451000
    e: "us"
    f: ""
    p: -1
2019-11-30 23:47:12.884 17374-17374/? I/CalendarProvider2: Created com.android.providers.calendar.CalendarAlarmManager@9d9528c(com.android.providers.calendar.CalendarProvider2@cf6fdd5)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG: backtrace:
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #00 pc 0060ceea  /system/lib/libhwui.so (SkSurface::getCanvas()+26)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #01 pc 0009b53d  /system/lib/libhwui.so (android::uirenderer::skiapipeline::GLFunctorDrawable::onDraw(SkCanvas*)+3357)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #02 pc 005200f7  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+279)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #03 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #04 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #05 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #06 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #07 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #08 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #09 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #10 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #11 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #12 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #13 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #14 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #15 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #16 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #17 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #18 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #19 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #20 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #21 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #22 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #23 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #24 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #25 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #26 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #27 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #28 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #29 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #30 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #31 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #32 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #33 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #34 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #35 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #36 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #37 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #38 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #39 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #40 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #41 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #42 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #43 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #44 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #45 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #46 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #47 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #48 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #49 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #50 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #51 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #52 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #53 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #54 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #55 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #56 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #57 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #58 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #59 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #60 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #61 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #62 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #63 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #64 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #65 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #66 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #67 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #68 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #69 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #70 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #71 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #72 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #73 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #74 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.908 17373-17373/? A/DEBUG:     #75 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #76 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #77 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #78 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #79 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #80 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #81 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #82 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #83 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #84 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #85 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #86 pc 0052006d  /system/lib/libhwui.so (SkDrawable::draw(SkCanvas*, SkMatrix const*)+141)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #87 pc 0051c9a6  /system/lib/libhwui.so (SkCanvas::onDrawDrawable(SkDrawable*, SkMatrix const*)+38)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #88 pc 00178318  /system/lib/libhwui.so (SkCanvas::drawDrawable(SkDrawable*, SkMatrix const*)+344)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #89 pc 005208f5  /system/lib/libhwui.so (SkLiteDL::draw(SkCanvas*) const+229)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #90 pc 004fe090  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::drawContent(SkCanvas*) const+352)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #91 pc 004fe51f  /system/lib/libhwui.so (android::uirenderer::skiapipeline::RenderNodeDrawable::forceDraw(SkCanvas*)+287)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #92 pc 000a655e  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderLayersImpl(android::uirenderer::LayerUpdateQueue const&, bool, bool)+862)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #93 pc 00546e44  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaPipeline::renderFrame(android::uirenderer::LayerUpdateQueue const&, SkRect const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>> const&, bool, bool, android::uirenderer::Rect const&, sk_sp<SkSurface>)+84)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #94 pc 00545e39  /system/lib/libhwui.so (android::uirenderer::skiapipeline::SkiaOpenGLPipeline::draw(android::uirenderer::renderthread::Frame const&, SkRect const&, SkRect const&, android::uirenderer::FrameBuilder::LightGeometry const&, android::uirenderer::LayerUpdateQueue*, android::uirenderer::Rect const&, bool, bool, android::uirenderer::BakedOpRenderer::LightInfo const&, std::__1::vector<android::sp<android::uirenderer::RenderNode>, std::__1::allocator<android::sp<android::uirenderer::RenderNode>>
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #95 pc 000b2e76  /system/lib/libhwui.so (android::uirenderer::renderthread::CanvasContext::draw()+262)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #96 pc 0054bd02  /system/lib/libhwui.so (_ZNSt3__110__function6__funcIZN7android10uirenderer12renderthread13DrawFrameTask11postAndWaitEvE3$_0NS_9allocatorIS6_EEFvvEEclEv$c303f2d2360db58ed70a2d0ac7ed911b+898)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #97 pc 004fd4c2  /system/lib/libhwui.so (android::uirenderer::WorkQueue::process()+242)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #98 pc 000c454a  /system/lib/libhwui.so (android::uirenderer::renderthread::RenderThread::threadLoop()+314)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #99 pc 0000e616  /system/lib/libutils.so (android::Thread::_threadLoop(void*)+326)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #100 pc 0000df76  /system/lib/libutils.so (thread_data_t::trampoline(thread_data_t const*)+246)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #101 pc 0008f065  /system/lib/libc.so (__pthread_start(void*)+53)
2019-11-30 23:47:12.909 17373-17373/? A/DEBUG:     #102 pc 0002485b  /system/lib/libc.so (__start_thread+75)

---
### Environment
* React Native Navigation version: 0.61.2
* React Native version: 4.0.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Sim + S6 Edge Debug

**Comment by manuhook** [comment] 2019-12-02 13:35
Hi,
After dismissing the modal do you display a screen with a webview (by displaying an Ad for example) ?

**Comment by aminosman** [comment] 2019-12-02 16:31
We are not using a web view on screen that pushes the modal however there is a hidden web view (for google recaptcha) in the modal, could this be the cause? I will test without it and let you know.

**Comment by manuhook** [comment] 2019-12-02 16:47
I have a similar issue with react-native-navigation and webview displayed by Admob.
When you disable the animation when pushing/popping the screen it's seems that there is no more bug.
But I never could reproduce this problem on my side with emulators or on real devices, it's just showing only my app crash logs :(

**Comment by aminosman** [comment] 2019-12-02 17:00
You are right! It was the web view in my recaptcha. Removing that has fixed the issue. Now as to why this is happening... do you have an open ticket for this issue?

**Comment by manuhook** [comment] 2019-12-02 18:34
No I didn't open an issue yet as I wasn't sure where the problem was coming from.
I'm using RNN V3 and now V4.
The only way I could reproduce the error on android is by pushing a screen and a webview inside with no height.
On your project, are you sure that when you render modal, the webview's width and height are never null or equals to 0 ?

**Comment by aminosman** [comment] 2019-12-02 19:34
We actually do use a web view with no height and width as the only way to run the recaptcha verification is via a web view. I just bumped the width and hight to 1 and that seemed to solve the issue too. Are you guys using a web view with no width / height or was this a transition state ?

**Comment by aminosman** [comment] 2019-12-02 19:36
BTW Thanks so much for this info, you have been sooo much help! I spent all weekend trying to get to the bottom of this and came up empty handed. This was a great catch.

**Comment by manuhook** [comment] 2019-12-02 19:41
You're welcome :)
With Admob the hard thing is that's almost impossible to say if Google is serving a native Ad or with an Ad through a webview, and if it's with a webview, I'm still looking for a way to be sure that height and width are defined :P

**Comment by ItsNoHax** [comment] 2019-12-10 19:35
Hi @manuhook and @aminosman .

I am going to close the issue as this has been resolved already and is not directly related to RNN. Please follow the following issue: https://github.com/react-native-community/react-native-webview/issues/1069

Also please edit your post and remove your solution to this problem. You only need to disable hardware acceleration for the web view. It is NOT recommended to disable hardware acceleration completely for Android.

**Closed by ItsNoHax** 2019-12-10 19:35 UTC

**Comment by RodolfoGS** [comment] 2021-02-11 16:54
Hi @manuhook, I have the same issue that you, I'm using admob. Could you fixed your issues? Thanks a lot!
