### ISSUE TITLE
Android crashes on startup

### ISSUE THREAD

**Issue by wellyal** [wix/react-native-navigation#2241] opened 2017-11-29 02:16 UTC
### Issue Description

Followed [all the instructions](https://wix.github.io/react-native-navigation/#/installation-android) for android installation but my app got crashed on the first time (no log info). The documentation is also confusing it says "In MainApplication.java, add the following", should I replace the original? merge the original?

### Code Snippets
**MainAplication.java**
```java
package com.beausy_mobile;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import java.util.Arrays;
import java.util.List;

import com.reactnativenavigation.NavigationApplication;

 public class MainApplication extends NavigationApplication {

   @Override
   public boolean isDebug() {
       // Make sure you are using BuildConfig from your own application
       return BuildConfig.DEBUG;
   }

   protected List<ReactPackage> getPackages() {
       // Add additional packages you require here
       // No need to add RnnPackage and MainReactPackage
       return Arrays.<ReactPackage>asList(
        new MainReactPackage()
           // eg. new VectorIconsPackage()
       );
   }

   @Override
   public List<ReactPackage> createAdditionalReactPackages() {
       return getPackages();
   }
}

```
**MainActivity.java**
```java
import com.reactnativenavigation.controllers.SplashActivity;

public class MainActivity extends SplashActivity {

}
```
**index.js**
```javascript
import {Navigation} from 'react-native-navigation';
import {registerScreens} from './src/screens';

registerScreens();

Navigation.startTabBasedApp({
  tabs: [
    {
      label: 'Signin',
      screen: 'page.Signin',
      title: 'Signin'
    },
    {
      label: 'Home',
      screen: 'page.Home',
      title: 'Home'
    }
  ]
});

```
---
### Environment
* React Native Navigation version: 1.1.296
* React Native version: 0.50.4
* React Native CLI version: 2.0.1
* Platform(s) Android

**Comment by pqkluan** [comment] 2017-11-29 03:25
The latest known working version of RN is 0.49.3 at the moment. Although there is a workaround for the issues, I still recommended downgrading.

Also, you need to provide icon assets for each tab. Otherwise, the app will crash.

**Comment by wellyal** [comment] 2017-11-29 11:00
I did what you said. I downgraded RN version, and inserted the icons. Although nothing seems to change. The app is still crashing.

**Comment by pqkluan** [comment] 2017-11-29 11:41
Could you upload the Android crash log?

**Comment by wellyal** [comment] 2017-11-29 13:04
It only crashes with no log. The build succeed. 
![image](https://user-images.githubusercontent.com/3047016/33376494-10135d1c-d4f5-11e7-85b4-34abff2056b0.png)

**Comment by wellyal** [comment] 2017-11-29 13:10
I uploaded the repo [here](https://github.com/wellyal/beausy_mobile)

**Comment by pqkluan** [comment] 2017-11-29 13:36
I mean run-time log, not build log. Use `react-native log-android` at project root or Android Studio to get the run-time log.

I just take a look at your uploaded repo, there are 2 things I see:

- You need to split the `index.js` into two files `index.android.js` and `index.ios.js` to make it work with RN 0.49
- Switch to `png` file instead of `svg` as tab bar asset.

**Comment by wellyal** [comment] 2017-11-29 14:02
Well my build.gradle points to the index.js as entry file, thats why I put it on index.js. I've made the changes suggested. The app craches and the only log I get from log-android is the following.

**react-native log-android**
```
--------- beginning of crash
--------- beginning of system
--------- beginning of main
11-29 11:37:01.304 19128 19128 D ReactNative: ReactInstanceManager.onReloadWithJSDebugger()
11-29 11:37:01.306 19128 19128 D ReactNative: ReactInstanceManager.recreateReactContextInBackground()
11-29 11:37:01.306 19128 19128 D ReactNative: ReactInstanceManager.runCreateReactContextOnNewThread()
11-29 11:37:01.309 19128 19128 D ReactNative: ReactInstanceManager.tearDownReactContext()
11-29 11:37:01.319 19128 19128 D ReactNative: CatalystInstanceImpl.destroy() start
11-29 11:37:01.969 19128 21578 D ReactNative: ReactInstanceManager.createReactContext()
11-29 11:37:02.091 19128 21578 D ReactNative: Initializing React Xplat Bridge.
11-29 11:37:02.093 19128 21578 D ReactNative: Initializing React Xplat Bridge before initializeBridge
11-29 11:37:02.095 19128 21578 D ReactNative: Initializing React Xplat Bridge after initializeBridge
11-29 11:37:02.096 19128 21578 D ReactNative: CatalystInstanceImpl.runJSBundle()
```

**Comment by saudpunjwani101** [comment] 2017-11-30 11:16
Try this,

change your App.js file to what u did in index.android.js:

      import {Navigation} from 'react-native-navigation';
       import {registerScreens} from './src/screens';

      registerScreens();

   Navigation.startTabBasedApp({
       tabs: [
         {
           label: 'Signin',
           screen: 'page.Signin',
           icon: require('./src/images/icons/unlocked.png'),
           title: 'Signin'
          },
        {
          label: 'Home',
          screen: 'page.Home',
          icon: require('./src/images/icons/home.png'),
          title: 'Home'
        }
      ]
    });

and change your index.android.js file to look like this:
       
     import App from './app';

Try this first, also make sure u updated your Android.manifest file like it says in the docs.

**Comment by wellyal** [comment] 2017-12-07 18:08
@saudpunjwani101 thanks for your help but unfortunately its still crashing :(

**Comment by saudpunjwani101** [comment] 2017-12-07 18:14
Only Android is crashing? 
Have you checked ios?

**Comment by wellyal** [comment] 2017-12-07 18:21
This project I uploaded to github is just a mock project I have created as an example. I haven't made the configuration for ios on it. Even though on my original project ios is working great.

**Comment by saudpunjwani101** [comment] 2017-12-07 18:22
Okay so the problem is with android. Let me see

**Comment by pqkluan** [comment] 2017-12-21 11:06
@wellyal Do you get any progress with the Android build?

**Comment by michaelmerrill** [comment] 2017-12-25 22:40
Is there any way we can get this package to work with react-native 0.51?

**Comment by nebsi04** [comment] 2017-12-27 01:03
It would be great if we can get this package to work with react-native 0.51. I have decided not to use react-navigation and am impressed with the react-native-navigation performance so far.

**Comment by pqkluan** [comment] 2018-01-22 05:10
I'll close this issue since the problem was resolved in the latest build version. Feel free to re-open if needed.

**Closed by pqkluan** 2018-01-22 05:10 UTC

**Comment by 3210jr** [comment] 2018-05-23 12:03
Hey, having the same issue. New app keeps crashing. is it something with the recent version?

**Comment by pqkluan** [comment] 2018-05-23 13:59
@3210jr You should check the logs in Android Studio, this might relate to Android maven or an upstream with React-Native.

If the log relates to RNN, you might want to create a new issue.

**Comment by ali-sao** [comment] 2018-06-11 22:38
I am facing the same issue here as well

**Comment by vignes412** [comment] 2018-07-21 06:40
i am facing the same issue

**Comment by wanbok** [comment] 2018-07-22 12:20
+1

**Comment by TheParosIns** [comment] 2018-07-26 15:30
Thank you @maroparo for this solution!! :D :1st_place_medal:

**Comment by Gomechatronics** [comment] 2019-05-22 13:51
In my case the application loads when the phone is connected to the metro-builder, but once the phone is disconnect from the Metro-builder the application crashes.

**Comment by folofse** [comment] 2019-05-28 18:24
Also make sure you have changed package name on the import for BuildConfig in MainApplication.java, if you mistakenly choose to import com.facebook.BuildConfig you will end up with a similar problem.
Like `import com.yourpackage.BuildConfig`

**Comment by Shivendra30** [comment] 2019-06-11 11:04
As @folofse mentioned, I imported the BuildConfig from facebook package but was supposed to import from my app's package

**Comment by SmartArray** [comment] 2019-11-20 17:54
> As @folofse mentioned, I imported the BuildConfig from facebook package but was supposed to import from my app's package

I had the same issue, and it costed me almost a full day to find the cause of the crash. Thanks @Shivendra30 and @folofse

**Comment by bcneves13** [comment] 2019-11-28 20:47
> Also make sure you have changed package name on the import for BuildConfig in MainApplication.java, if you mistakenly choose to import com.facebook.BuildConfig you will end up with a similar problem.
> Like `import com.yourpackage.BuildConfig`

Thank you, this is a life saver

**Comment by KawaljeetSBagga** [comment] 2020-04-16 11:36
> Also make sure you have changed package name on the import for BuildConfig in MainApplication.java, if you mistakenly choose to import com.facebook.BuildConfig you will end up with a similar problem.
> Like `import com.yourpackage.BuildConfig`

Oh Man! You saved my life.

**Comment by kyle-belle** [comment] 2020-05-02 02:44
> Also make sure you have changed package name on the import for BuildConfig in MainApplication.java, if you mistakenly choose to import com.facebook.BuildConfig you will end up with a similar problem.
> Like `import com.yourpackage.BuildConfig`
You little fucking monster.
Damn man. gotta jump on the "Thanks" train too. I dont think i would have EVER figured this out. Thanks
