### ISSUE TITLE
componentDidAppear not invoked when using setRoot on Android

### ISSUE THREAD

**Issue by randomBrainstormer** [wix/react-native-navigation#7061] opened 2021-03-25 13:56 UTC
## 🐛 Bug Report

`componentDidAppear` is not being triggered when the view is presented using `Navigation.setRoot`.  This does not happen when the view is presented using `Navigation.push`, only with `Navigation.setRoot`.  

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

Either clone [my repo](https://github.com/randomBrainstormer/RnnBugExample) and see index.js, or just add componentDidAppear method in any view presented using `Navigation.setRoot`

## Expected behavior

I would expect `componentDidAppear` to be triggered regardless the way is presented

## Actual Behavior

`componentDidAppear` not being invoked, yet`componentDidDisappear` seems to work.

## Your Environment 
- React Native Navigation version: 7.11.3
- React Native version: 0.64.0
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Andriod Simulator using Pixel 4XL/Android 11.0 

## Reproducible Demo

https://github.com/randomBrainstormer/RnnBugExample/blob/main/index.js

**Comment by randomBrainstormer** [comment] 2021-03-25 13:57
Found this related issue: #6858

**Comment by randomBrainstormer** [comment] 2021-03-26 18:19
It seems that if i use `waitForRender` set to `true` as the default option the event works as expected. Using this prop as part of the component options does not seem to work.

```javascript
// this works
Navigation.setDefaultOptions({
  animations: {
    setRoot: {
      waitForRender: true
    },
    push: {
      waitForRender: true
    },
  },
})

// this does NOT work
const loginRoot = {
  root: {
    component: {
      name: 'Login',
      waitForRender: true,
    },
  },
};
 Navigation.setRoot(loginRoot);
```

**Comment by guyca** [comment] 2021-03-27 06:17
@randomBrainstormer The issue is that the componentDidAppear listener is registered in `useEffect` which is called after first-render. If the application does a of initialization on startup, it's possible the root component is already created in native and the appear event is emitted before it's fully mounted.

Setting `waitForRender` in setRoot animations is indeed the right approach.

You might also want to try registering the appear listener in `useMemo` which isn't dependent on layout-lifecycle. Something like this:

```ts
const MyRootComponent: NavigationFunctionComponent<Props> = ({ componentId }) => {
  useMemo(() => {
    const unsubscribe = Navigation.events().registerComponentListener(
      {
        componentDidAppear: () => {
          console.log('RNN', `componentDidAppear`);
        },
        componentDidDisappear: () => {
          console.log('RNN', `componentDidDisappear`);
        },
      },
      componentId
    );
    return () => {
      unsubscribe.remove();
    };
  }, [componentId]);

  ...
}
```

I'm closing the issue as this isn't an RNN bug but more than a quirk related to the async nature of RN.

**Closed by guyca** 2021-03-27 06:17 UTC
Labels: needs triage, triage: bug
