### ISSUE TITLE
Swipe back doesn't work with scrollview IOS

### ISSUE THREAD

**Issue by Tekosawa** [wix/react-native-navigation#1918] opened 2017-09-23 13:55 UTC
### Steps to Reproduce / Description
We can't swipe back from Screen with ScrollView (pageEnabled = true) content to previous screen.

Put this code on the push screen and try to back with gesture back: 
[https://gist.github.com/Tekosawa/4efb40ec2c1dfde159b36cef2c1fe3b4](https://gist.github.com/Tekosawa/4efb40ec2c1dfde159b36cef2c1fe3b4)

### Environment
* React Native Navigation version: The lastest
* React Native version: 0.48 (but bug available on 0.45 too)
* Platform: IOS
* Device info : Similator device (All Iphone version)

**Comment by gran33** [comment] 2017-09-25 12:19
Hi, and thanks for your issue report.
After checking the case, the issue is a collision between the `scrollView` horizontal scroll and the back gesture.
These collisions can happen in pure native and not related to react-native. Anyway, this library cannot decide which horizontal scroll is the one the user wanted to perform.

If u have a better insight into this issue, you are more than welcome to comment.

closing this issue for now.

Thanks again.

**Closed by gran33** 2017-09-25 12:19 UTC

**Comment by emin93** [comment] 2017-09-29 12:57
I solved this issue by creating an empty view as an ios swipe back safe zone:

```
<View>
    <ScrollView>...</ScrollView>
    {Platform.OS === 'ios' && <View style={{ position: 'absolute', top: 0, bottom: 0, left: 0, width: 10 }} />}
</View>
```

**Comment by smooJitter** [comment] 2017-11-28 15:39
@emin93  swipe back safe zone? What is that about?

**Comment by emin93** [comment] 2017-11-28 16:02
@smooJitter Just a simple empty view of 10px width, which is on top of the ScrollView on the left side and only on iOS. This prevents the ScrollView from catching the touch events on the left side of 10px and allows the Navigation to catch the swipe back gesture.

**Comment by smooJitter** [comment] 2017-12-01 05:03
@emin93, are you serious?   lol. That's a bit funny.  What do you mean by "on the left side".  Can you show me a simple composition. 
```
<View style={...10px}></View>
<ScrollView>
    /*somehthing here*/
</ScrollView>
```

**Comment by luatnd** [comment] 2019-08-26 08:48
> I solved this issue by creating an empty view as an ios swipe back safe zone:
> 
> ```
> <View>
>     <ScrollView>...</ScrollView>
>     {Platform.OS === 'ios' && <View style={{ position: 'absolute', top: 0, bottom: 0, left: 0, width: 10 }} />}
> </View>
> ```

Best funny hacking idea :) Save my hours
