### ISSUE TITLE
Android application keeps stopping . Does not work react-native-navigation on Android

### ISSUE THREAD

**Issue by sinevitch** [wix/react-native-navigation#2989] opened 2018-04-07 10:39 UTC
# **Issue Description**
Does not work react-native-navigation on Android
Starting : Intent { …MainActivity }. 

Did everything as indicated in the documentation.  I launch the Android Studio emulator.

![image](https://user-images.githubusercontent.com/35930695/38454051-7e4c4220-3a68-11e8-80ca-720489821f47.png)
On iOS, the same code works fine
**index.ios.js**
`import App from './App';`

**index.android.js**
`import App from './App';`

**app.js:**
```
   import { Navigation } from "react-native-navigation";
   import AuthScreen from "./src/screens/Auth/Auth";
   // Register Screens
   Navigation.registerComponent("awesome-places.AuthScreen", () => AuthScreen);

   // Start a App
     
   Navigation.startSingleScreenApp({
              screen: {
               screen: "awesome-places.AuthScreen",
               title: "Login"
            }
    });
```

**auth.js:**
```
import React, { Component } from 'react';
import { View, Text } from 'react-native';

class AuthScreen extends Component {
    render () {
        return (
            <View>
                <Text>Auth Screen</Text>
            </View>
        );
    }
}
export default AuthScreen;
```

**settings.gradle**
  ```
   rootProject.name = 'rncourse'

   include ':app'



  include ':react-native-vector-icons'
  project(':react-native-vector-icons').projectDir = new File(rootProject.projectDir, 
  '../node_modules/react-native-vector-icons/android')

  include ':react-native-navigation'
  project(':react-native-navigation').projectDir = new File(rootProject.projectDir, 
  '../node_modules/react-native-navigation/android/app/')
```

**build.gradle**
```
dependencies {
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"
    compile project(':react-native-navigation')  // From node_modules
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}


project.ext.vectoricons = [
    iconFontNames: [ 'Ionicons.ttf'] // Name of the font files you want to copy
]

apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
```

**MainActivity.java**

```
 import com.reactnativenavigation.controllers.SplashActivity;

 public class MainActivity extends SplashActivity {

 }
```

**MainApplication.java**

```
package com.rncourse;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;
import com.oblador.vectoricons.VectorIconsPackage;
import com.reactnativenavigation.NavigationApplication;

import java.util.Arrays;
import java.util.List;


public class MainApplication extends NavigationApplication {

     @Override
     public boolean isDebug() {
         // Make sure you are using BuildConfig from your own application
         return BuildConfig.DEBUG;
     }

     protected List<ReactPackage> getPackages() {
         // Add additional packages you require here
         // No need to add RnnPackage and MainReactPackage
         return Arrays.<ReactPackage>asList(
             new VectorIconsPackage()
         );
     }

     @Override
     public List<ReactPackage> createAdditionalReactPackages() {
         return getPackages();
     }
 }
```
I tried to use the version of "react-native": "^ 0.49.5",
The same thing happens
Android does not work
IOS works

---
### Environment
* React Native Navigation version: "^1.1.434",
* React Native version: "0.54.0",
* Platform(s) : Android 8.1
* Device info : Android Simulator 
* Android Studio version 3.1

**Comment by peakyDicers** [comment] 2018-04-07 13:42
I am having a very similar issue. My project builds successfully, but a blank screen appears in the android emulator. I've posted my setup and screenshots in this similar thread. https://github.com/wix/react-native-navigation/issues/2687

**Comment by sinevitch** [comment] 2018-04-09 13:41
error: no devices/emulators found

**Comment by sinevitch** [comment] 2018-04-09 13:48
`adb reverse tcp:8081 tcp:8081`

Did not help

![image](https://user-images.githubusercontent.com/35930695/38501457-bd92ed4a-3c15-11e8-9079-41e4221c8b6a.png)

**Comment by chinmaygit** [comment] 2018-04-09 13:54
@sinevitch  Open Logcat while you are opening the app, and look for crash log and share it here.

**Comment by sinevitch** [comment] 2018-04-09 16:28
![image](https://user-images.githubusercontent.com/35930695/38509951-1c49f458-3c2c-11e8-983c-4ccc1ff5ef3c.png)

**Comment by anuraginwadi** [comment] 2018-05-15 13:29
Facing the same issue. any fix?

**Comment by ashifa454** [comment] 2018-05-16 12:52
Any update on this issue?

**Comment by SirPhemmiey** [comment] 2018-05-31 03:33
Any update on this issue?

**Comment by guyca** [comment] 2018-05-31 08:18
The single crash log which was posted here has nothing to do with RNN. I'm closing as we really can't help you resolve this issue.

**Closed by guyca** 2018-05-31 08:18 UTC

**Comment by NySiya** [comment] 2018-10-17 03:59
I am having this very same problem :(

**Comment by wijaksanapanji** [comment] 2018-10-28 07:46
> The same issue after linking with react-native-firebase. No logs. It's just crashing on the physical device.

any solution for your problem, im new to react-native, i got the same problem after adding react-native-firebase

**Comment by wijaksanapanji** [comment] 2018-10-28 09:46
> > The same issue after linking with react-native-firebase. No logs. It's just crashing on the physical device.
> 
> any solution for your problem, im new to react-native, i got the same problem after adding react-native-firebase

i just moved google() in `android/build.gradle` to the top, and it worked 
```allprojects {  
repositories {
    google()
    mavenLocal()
    jcenter()
    maven {
      // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
      url "$rootDir/../node_modules/react-native/android"
    }
  }
}`

**Comment by marcosgallardo** [comment] 2019-01-03 17:57
@sinevitch 

Try by changing your `MainActivity.java` to:

    package com.rncourse; //<- App package name goes here

    import com.reactnativenavigation.controllers.SplashActivity;

    public class MainActivity extends SplashActivity {

    }

**Comment by potatokoosh** [comment] 2019-04-01 05:31
Corriendo un app con react-native
tube el mismo problema, me estuvo saliendo el mensaje de App keep stopping, el emulador no me mostraba la app,, lo solucione con los siguientes pasos
1. abrir el proyecto en android studio
2. ejecutar el play o el emulador (aqui no me abre el proyecto sale app keep stopping)
3. desde la terminal das         react-native run android

espero ayude

**Comment by potatokoosh** [comment] 2019-04-01 15:33
> `adb reverse tcp:8081 tcp:8081`
> 
> Did not help
> 
> ![image](https://user-images.githubusercontent.com/35930695/38501457-bd92ed4a-3c15-11e8-9079-41e4221c8b6a.png)

try to run from terminal, react-native run-android
but first you have to have open android studio with the project and runing a emulator,, probably the message will apear (app keep stopping),,then in terminal you run react-native run android

this worked for me 

i hope it works for you

**Comment by mohshbool** [comment] 2019-04-11 17:33
@potatokoosh It also didn't work for me, but my message is "myApp keeps stopping". Does anybody have any other solutions?

**Comment by monaye** [comment] 2019-05-03 05:35
having the same error message for the Android release build. 
    "react": "16.6.3",
    "react-native": "0.58.6",

Are there any tools to debug what is going on in the release build?

**Comment by Gomechatronics** [comment] 2019-05-22 13:47
In my case the application loads when the phone is connected to the metro-builder, but once the phone is disconnect from the Metro-builder the application crashes.

**Comment by AntonioMIN** [comment] 2019-05-25 08:01
I had the same problem. But I just fixed it by pressing Ctrl + M a few times. I do not know how it works.

**Comment by planetofcode** [comment] 2019-06-30 20:45
I have the same problem. :|

**Comment by planetofcode** [comment] 2019-06-30 20:49
I closed the app and relaunched it from the Android, it worked for me.

**Comment by AmeraAbdallah** [comment] 2019-07-15 17:57
I had a similar problem, I fixed it by removing component from screen that I wanna navigate to it, and it was nativeBase Picker component

**Comment by maxjf1** [comment] 2019-07-26 04:31
I had this problem with the lib [react-native-pdf-lib](https://github.com/Hopding/react-native-pdf-lib). 

With LogCat i figure it out, i had to ask for `WRITE_EXTERNAL_STORAGE` with [PermissionsAndroid](https://facebook.github.io/react-native/docs/permissionsandroid#example)

**Comment by mrsimply** [comment] 2019-08-08 14:06
Occurred to me as well, just like this without adding packages.
I was trying to find a solution, reading a lot, without luck.
I finally desperately wiped the Android Emulator and - tataaa - that was it. Worked for me.

**Comment by EdersonJunior** [comment] 2019-08-11 21:38
I solved this issue (in my case) using this link: https://medium.com/@impaachu/react-native-android-release-build-crash-on-device-14f2c9eacf18.

**Comment by gorvinsky** [comment] 2019-08-14 01:00
> I solved this issue (in my case) using this link: https://medium.com/@impaachu/react-native-android-release-build-crash-on-device-14f2c9eacf18.

It seems that there could be different reasons for this to happen and the best way to nail the cause is by using this method. I solved mine with this and for my case, it's because of a library that I installed. I solved it by uninstalling that library.

**Comment by raemarcsg30** [comment] 2019-08-14 13:24
Maybe you don't have `index.android.js` and `index.ios.js` with `import App from './App';` ?

**Comment by diebraga** [comment] 2019-09-08 18:50
I could not solve the problem but you can just '' react-native init <newApp>'' and change app.js from the the old app.

**Comment by arthedza** [comment] 2019-10-04 15:28
Maybe you should restart Metro bundler

**Comment by pedromelo98** [comment] 2019-10-31 17:58
same here
"react": "16.8.3",
"react-native": "^0.60.4"

**Comment by rajnishcoder** [comment] 2019-11-29 04:24
> I could not solve the problem but you can just '' react-native init '' and change app.js from the the old app.

Does that solved the problem?

**Comment by PrateekOraon** [comment] 2019-12-06 19:50
See that you don't have two react-native versions installed simultaneously. Do : 
`npm list --depth` 

If there are two RN versions, there will be a version mismatch and the app will keep stopping.

`npm uninstall react-native@<the-version-you-want-to-uninstall>` 
Then run your code again.

**Comment by shahnawazhussain125** [comment] 2019-12-16 21:08
build has been complete and emiulator is working then error  "Keeps Stoping" 

![emilator](https://user-images.githubusercontent.com/37732557/70943175-0de9ad00-2072-11ea-84b3-c86b687b302a.png)

**Comment by yelinag** [comment] 2019-12-21 07:45
Debug/run the project in android studio where you will be able to see error logs. For my case, there are a lot of issues as haven't tested in android for a very long time.

**Comment by ALashchotka** [comment] 2020-01-08 07:52
Works for me: https://github.com/evollu/react-native-fcm/issues/998#issuecomment-404736950

**Comment by marcinkieruzel** [comment] 2020-01-11 11:27
In my case `gradlew clean` on Windows or `./gradle clean` on Linux makes the emulator works again.

**Comment by davyotush** [comment] 2020-01-30 09:20
how can i remove this error..

2020-01-30 01:06:07.156 3396-3396/com.dotundo.androiddoctor E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.dotundo.androiddoctor, PID: 3396
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.dotundo.androiddoctor/com.dotundo.androiddoctor.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2865)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2955)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6747)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.Button.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
        at com.dotundo.androiddoctor.MainActivity.LoginFunction(MainActivity.java:54)
        at com.dotundo.androiddoctor.MainActivity.onCreate(MainActivity.java:33)
        at android.app.Activity.performCreate(Activity.java:7025)
        at android.app.Activity.performCreate(Activity.java:7016)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1217)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2812)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2955) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6747) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:449) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by MartykQ** [comment] 2020-02-27 15:53
For me the problem was I was following steps from react-native docs instead react-navigation official docs. The first one does not mention this step:

_____


To finalize installation of react-native-screens for Android, add the following two lines to dependencies section in android/app/build.gradle:

```
implementation 'androidx.appcompat:appcompat:1.1.0-rc01'
implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0-alpha02'
```

**Comment by PontesVinicius** [comment] 2020-03-16 02:34
I solved this error by updating the version of Android Studio.

**Comment by robauer** [comment] 2020-03-20 19:06
> I solved this error by updating the version of Android Studio.

Updating is what go me into this mess.

**Comment by Cmion** [comment] 2020-05-02 19:12
`gradlew clean` then `yarn run android` solved the problem on windows

**Comment by iankressin** [comment] 2020-07-22 11:13
@Cmion answer works in Ubuntu 20.4 as well

**Comment by WadhahEssam** [comment] 2020-07-24 19:53
what solved it for me was cleaning the project, so it might work for you.
run
`git clean -d -x -f`

then just run
`npm install` or `yarn`

**Comment by YDaskaloff** [comment] 2020-07-29 10:47
Assuming environment is set up correctly and you are not using Expo:
run the following:
~ cd android
~ ./gradlew clean
~ cd ..
~ npm install
~ npm react-native start
~ npm react-native run-android

This worked for me.

**Comment by 0707236659** [comment] 2020-10-23 08:22
I only met is a problem on android but it worked on android 7, 8.1 ,9 and 10

**Comment by TomHessburg** [comment] 2021-03-27 22:50
Just got through this issue after a solid day or two of smacking my face against the wall with it lol. Not sure if this will help anyone, but this was the issue for me:

After ejecting from expo, _src/main/java/.../MainActivity.java and MainApplication.java_ were not generated. For whatever reason, I was still able to run on android using 'expo start' even with this being that case. 

When running _react-native run-android_, I found that first issue (_got a bunch of errors saying that there was no MainApplication file_). Not a problem, just went ahead and added my own. 

After adding my own, I started seeing the issue that this thread is mentioning. I tried a bunch of stuff, but what ended up being the case for me was that the `getMainComponentName` method inside of MainActivity.java was incorrect (_think it was my package name or something, where it was supposed to be "main", at least in my case_).

Again, not saying this will be the issue for everyone, but might be worth it to take a look at your src/main/java/<package>/... files to see if anything looks off. To figure out what these files are supposed to look like, i just checked out some other projects (for instance the [expo bare project templates](https://github.com/expo/expo/tree/master/templates/expo-template-bare-minimum/android/app/src/main/java/com/helloworld) repo) for reference. 

If you're able to run logcat, that'll definitely help, but in my case I don't think the app was even being mounted, thus logcat wasn't showing any errors, so I had to brute force it haha.

**Comment by EshaZaheer** [comment] 2021-08-17 14:22
i was facing he same issue but when I uninstall the app and run it again on my phone then it worked properly

**Comment by mutabazigakuba** [comment] 2021-08-24 14:38
I solved it by deleting the `node_modules` and re running react-native

**Comment by Robogeek95** [comment] 2021-11-03 11:04
> I solved it by deleting the `node_modules` and then re run

Thanks @mutabazigakuba  This worked for me

**Comment by engsan710** [comment] 2022-03-25 21:02
My problem was that one of my styles had the following:
...
padding: '16px',
...
It worked just fine on the web, but the emulator did not like it. The way I found the root cause is I removed all sections until the app started. Then I add one section at a time until I found the one that had the incorrect style. 
The correction was to change it to:
...
padding: 16,
...
I hope this helps somebody.

**Comment by kyrieLiu3** [comment] 2022-09-14 06:40
> `gradlew clean`, uninstalling the app then `yarn run android` solved the problem on windows

It works for me thanks to @iankressin. Actually there is always dependence issues when you install new dependence, so you just clean the cache and restart it. GOOD LUCK!

**Comment by piyushrajput45** [comment] 2023-04-07 08:23
It works for me
Add some  **android:usesCleartextTraffic="true"**  in  ./android/app/src/main/AndroidManifest.xml add

**Comment by JIS-Mary** [comment] 2023-06-22 01:08
In my issues, creating lauchscreen.xml inside layout folder 

<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">
    <ImageView android:layout_width="match_parent" android:layout_height="match_parent" android:src="@drawable/launch_screen" android:scaleType="centerCrop" />
</RelativeLayout>

and it worked
