### ISSUE TITLE
react-native-navigation:compileReactNative57_5DebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by bunny100** [wix/react-native-navigation#5274] opened 2019-07-09 20:31 UTC
I have tried npx jetify and it has solved alot of issues but this is still there:

Android Studio compiler output:
![image](https://user-images.githubusercontent.com/46201508/60920787-77d77c80-a2b2-11e9-8664-96d07fabb9c3.png)

**Comment by igortupini** [comment] 2019-07-09 20:38
This is a duplicate of #5273

**Closed** 2019-07-10 18:22 UTC
