### ISSUE TITLE
Touchable padding topbar when not using systemItem

### ISSUE THREAD

**Issue by AlexDM0** [wix/react-native-navigation#5158] opened 2019-05-27 10:06 UTC
### Issue Description

I have a topbar in my project which I want to use with custom component buttons. I notice that if I use a custom component or an icon, there is some padding on the right for right buttons, and padding on the left for left buttons. This is about 16 pixels. 

I understand this for the layout, the problem is that it is not touchable area. If I use a systemItem (ios) I can tap all the way to the right of the screen to register an event. If it is an icon or custom component, touching the rightmost 16 pixels does not trigger a tap.

I tried using position:relative to shift it 16 pixels to the side, but the touchable area does not move with it.

I prefer having larger hitboxes to make the navigation for my users more intuitive.

### Steps to Reproduce / Code Snippets / Screenshots

```
{
  id: 'edit',
  icon: require("../images/icons/cog.png"),
}

//together with:
constructor(props) {
    super(props);
    Navigation.events().bindComponent(this);
  }

  navigationButtonPressed({ buttonId }) {
    console.log("HERE", buttonId)
  }
```

Try this in the simulator and use the pointer for clicks and look at the console for when it start triggering.

Compare this with: 
```
{
  id: 'edit',
  icon: systemItem: 'edit',
}
```

---
### Environment
* React Native Navigation version: 2.20.2
* React Native version:0.59.8
* Platform(s) (iOS, Android, or both?): tested on iOS only so far
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator for easy testing, device in both debug and release mode.

**Comment by ItsNoHax** [comment] 2019-05-27 11:46
Hi @AlexDM0 

I'm going to go ahead and close this since it's a duplicate of: https://github.com/wix/react-native-navigation/issues/5000

**Closed by ItsNoHax** 2019-05-27 11:46 UTC

**Comment by AlexDM0** [comment] 2019-05-27 12:24
Hi @ItsNoHax,

You're right, sorry!

Cheers
