### ISSUE TITLE
[V2] topBarHeight constant always 0

### ISSUE THREAD

**Issue by steve228uk** [wix/react-native-navigation#4190] opened 2018-10-22 13:30 UTC
### Issue Description

It seems that when accessing the `topBarHeight` from `Navigation.constants()` that the value is always set to `0`. 

I'm not certain if there's another way to access the height of the navigation bar.

### Steps to Reproduce / Code Snippets / Screenshots

```js
const constants = await Navigation.constants();
console.table(constants);
```

---
### Environment
* React Native Navigation version: 2.0.2594
* React Native version: 0.56.0
* Platform(s) (iOS, Android, or both?): iOS
* Device info (Simulator/Device? OS version? Debug/Release?): Simulator / iOS 12 / Debug

**Comment by guyca** [comment] 2018-10-23 06:39
Are you calling `await Navigation.constants()` before setting a root with a stack layout?

IIRC, we get the TopBar height from the inflated `NavigationController` so calling it before a stack was set will return 0.

**Comment by kyledmellander** [comment] 2018-11-05 18:01
Is there a workaround for using KeyboardAvoidingView with a top bar? The Keyboard Avoiding View gets pushed down by the top bar so normally I would use the prop keyboardVerticalOffset along with the top bar height.

**Comment by steve228uk** [comment] 2018-11-07 17:21
@kyledmellander currently I’m using 44 + the status bar height which is being set. It’s not ideal but it works for the time being.

**Comment by kyledmellander** [comment] 2018-11-07 21:35
@steve228uk Thanks! Do you know if this work across all/most IOS devices? We have users ranging from the 5s to the iPhone X/XS/...

**Comment by steve228uk** [comment] 2018-11-07 23:48
@kyledmellander It should do as the status bar height changes for devices that include a safe area inset. The only problem that will arise in the future is if Apple changes the navigation bar height from 44.

**Comment by pakyo-pan** [comment] 2018-12-05 01:19
Any update on this?

**Comment by morelearn1990** [comment] 2018-12-29 02:16
When i ran Navigation.constants() in a page with tabBar and bottomTab, topBarHeight and bottomTabsHeight was correct.
When i ran Navigation.constants() in a page with tabBar and without bottomTab, topBarHeight was correct and bottomTabsHeight was incorrect.
When i ran Navigation.constants() in a page without tabBar and with bottomTab, topBarHeight was incorrect and bottomTabsHeight was correct.

**Comment by ericschaal** [comment] 2019-01-02 18:19
Hi everyone,

I think the Constant API should be modified as Navigation.constants() can only work if the NavigationRoot is a stack layout. i.e. it will not work if you have a side menu layout with a stack layout as the center component (will return topBarHeight: 0). ` UIApplication.sharedApplication.delegate.window.rootViewController.navigationController` will return nil. A solution could be to pass a componentId to Navigation.constants(componentId) and retrieve the appropriate ViewController and NavigationController.

**Comment by ericschaal** [comment] 2019-01-31 12:10
Hi, this issue seems to be about topBarHeight being wrong. It seeems that #4637 is only fixing bottomTabsHeight. Correct me if I’m wrong.

**Comment by ItsNoHax** [comment] 2019-01-31 16:33
Yeah I just tested this myself, still getting a height of 0.

**Comment by preko96** [comment] 2019-02-13 12:04
The problem is still the same. We are always getting the the first initialised root's constants.

**Comment by rh389** [comment] 2019-02-15 00:26
I just came up against this, but one workaround is to use `onLayout` to measure a `<View />` that fills the screen - the difference between that height and `Dimensions.get('window').height` should give you the height of the top bar + status bar.

```js
<View 
  style={StyleSheet.absoluteFill} 
  onLayout={e => this.setState({ 
    keyboardVerticalOffset: Dimensions.get('window').height - e.nativeEvent.layout.height
  })}>
  <KeyboardAvoidingView keyboardVerticalOffset={this.state.keyboardVerticalOffset || 0} /* ... */ >
    // ...
  </KeyboardAvoidingView>
</View>
```
NB: Simplified example - you'll want to make sure you're not calling setState unnecessarily (eg measure once, store offset in your global state), watch out for screen rotation, and test on Android.

**Comment by guyca** [comment] 2019-07-03 03:14
Fixed in version `2.22.3`

**Closed by guyca** 2019-07-03 03:14 UTC
Labels: platform: iOS, type: accepted/bug, 📌 pinned

**Comment by MakhouT** [comment] 2019-07-24 14:47
I can confirm it is working!

**Comment by dreamhb** [comment] 2019-08-05 09:35
@guyca I'm using 2.26.3, but topBarHeight is still 0

**Comment by dreamhb** [comment] 2019-08-05 09:36
@guyca I'm using 2.26.3, but topBarHeight is still 0

**Comment by dreamhb** [comment] 2019-08-05 14:11
@guyca I'm using 2.26.3, but topBarHeight is still 0

**Comment by emilioheinz** [comment] 2020-01-27 18:37
@guyca I'm using 2.27.3 and I'm getting 0 from the topBarHeight in iOS

**Comment by guyca** [comment] 2020-01-28 11:12
@emilioheinz on iOS this was fixed in v4.x.x

**Comment by rodribech20** [comment] 2021-02-19 13:04
I was using v2.27.9 and it was working. But now I updated to v7.8.4 and it is not working . topBarHeight returns 0 for iOS. Thanks

**Comment by cesarolimpio-meutudo** [comment] 2023-05-25 18:11
When I move push to another screen with `animationType: 'fade'`, the `topBarHeight` starts 0 and after try to get constants again couple seconds ago it comes correctly.
