### ISSUE TITLE
BottomTabs text is truncated when icon is present on iPad

### ISSUE THREAD

**Issue by DonovanDeSmedt** [wix/react-native-navigation#6775] opened 2020-11-17 11:07 UTC
## Issue description

When using `BottomTabs` with text & icon on an iPad , the text is truncated with an ellipsis no matter how long or short it is.
In case a badge is present in the bottom tab, only the text of the tab where the badge is present will be truncated when it's not currently selected (see screenshot). This only occurs on iPad, not on iPhone or Android devices.

Text in `BottomTabs` is truncated - playground app
![image](https://user-images.githubusercontent.com/16614702/99381382-64d3b400-28cb-11eb-8b89-1660b52e67f0.png)

In case a badge is present, only the text of the tab where the badge is present will be truncated (when it's not selected)
![image](https://user-images.githubusercontent.com/16614702/99381825-e592b000-28cb-11eb-9373-54e9a3597f67.png)

This issue is present since upgrade to RNN 7.0, RN 0.63 & iOS 14

## Steps to Reproduce / Code Snippets / Screenshots
Issue can be reproduced on iPad with current version of playground (commit: 6c69c8b7f093a989946120f8f826d849eb673cb8)

## Expected behavior
Text in `BottomTabs` should not be truncated on iPad when used in combination with icon.

## Your Environment
- React Native Navigation version: 7.3.0
- React Native version: 0.63.2
- Platform(s) (iOS, Android, or both?): iOS
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator & Device - iOS 14

## Reproducible Demo

https://github.com/wix/react-native-navigation/tree/6c69c8b7f093a989946120f8f826d849eb673cb8

**Comment by danilobuerger** [comment] 2020-11-19 08:27
Duplicate of #6533

**Closed by danilobuerger** 2020-11-19 08:27 UTC
Labels: needs triage, triage: bug
